-- Seed data for the First Century Church Directory:
-- regions, churches, people, and households.
-- Memberships and scripture references are seeded in the next migration;
-- journeys in the one after that.

begin;

-- ── Regions ──────────────────────────────────────────────────────────────────
insert into public."FCC_Regions" (region_id, name, description, sort_order) values
  ('judea',           'Judea',              'The Roman province around Jerusalem, cradle of the first church.', 1),
  ('syria',           'Syria',              'The province north of Judea; Antioch was its capital and a missionary hub.', 2),
  ('cyprus',          'Cyprus',             'The island home of Barnabas and the first stop of the first missionary journey.', 3),
  ('galatia',         'Galatia',            'The interior region of Asia Minor evangelized on the first journey.', 4),
  ('pamphylia',       'Pamphylia',          'The coastal region of southern Asia Minor.', 5),
  ('asia',            'Asia',               'The Roman province of western Asia Minor, centered on Ephesus.', 6),
  ('macedonia',       'Macedonia',          'The northern region of Greece, first European soil to receive the gospel.', 7),
  ('achaia',          'Achaia',             'The southern region of Greece, including Corinth and Athens.', 8),
  ('crete',           'Crete',              'The large Mediterranean island where Titus was left to appoint elders.', 9),
  ('italia',          'Italy',              'The heart of the empire, home of the church at Rome.', 10),
  ('egypt',           'Egypt',              'Home of Apollos and a major center of the Jewish diaspora.', 11),
  ('cyrenaica',       'Cyrenaica',          'The North African region of Cyrene.', 12),
  ('pontus-bithynia', 'Pontus & Bithynia',  'The Black Sea regions addressed in 1 Peter.', 13),
  ('cappadocia',      'Cappadocia',         'The inland region of Asia Minor addressed in 1 Peter.', 14);

-- ── Churches ─────────────────────────────────────────────────────────────────
insert into public."FCC_Churches" (church_id, name, lat, lng, region_id, founded_context, description, church_type, sort_order) values
  ('jerusalem',       'Jerusalem',          31.7683, 35.2137, 'judea',           'Founded at Pentecost when the Spirit was poured out on the apostles.', 'The mother church, led by the apostles and later by James the brother of Jesus.', 'jerusalem', 1),
  ('antioch',         'Antioch',            36.2021, 36.1604, 'syria',           'Founded by believers scattered after Stephen''s martyrdom.', 'The first church to send out missionaries; here disciples were first called Christians.', 'antioch', 2),
  ('damascus',        'Damascus',           33.5138, 36.2765, 'syria',           'An early community of disciples; Saul was converted on the road here.', 'Home of Ananias, who restored Saul''s sight and baptized him.', 'acts-church', 3),
  ('samaria',         'Samaria',            32.2761, 35.1953, 'judea',           'Evangelized by Philip after the scattering from Jerusalem.', 'A Samaritan community that received the Spirit through Peter and John.', 'acts-church', 4),
  ('joppa',           'Joppa',              32.0542, 34.7525, 'judea',           'Home of the disciple Tabitha, raised by Peter.', 'The coastal town where Peter received the vision that opened the gospel to the Gentiles.', 'acts-church', 5),
  ('lydda',           'Lydda',              31.9515, 34.8953, 'judea',           'A community of saints visited by Peter.', 'Where Peter healed the paralyzed Aeneas.', 'acts-church', 6),
  ('caesarea',        'Caesarea',           32.5000, 34.8939, 'judea',           'Founded with the conversion of Cornelius and his household.', 'The Roman provincial capital; later home of Philip the evangelist.', 'acts-church', 7),
  ('ptolemais',       'Ptolemais',          32.9281, 35.0819, 'judea',           'A community of believers Paul greeted on his way to Jerusalem.', 'A coastal stop where Paul spent a day with the brothers.', 'acts-church', 8),
  ('tyre',            'Tyre',               33.2705, 35.2038, 'syria',           'A community of disciples who warned Paul about Jerusalem.', 'Believers here knelt with Paul on the beach to pray.', 'acts-church', 9),
  ('sidon',           'Sidon',              33.5571, 35.3729, 'syria',           'A community of friends who cared for Paul on his voyage to Rome.', 'A coastal city where Paul''s friends provided for his needs.', 'acts-church', 10),
  ('salamis',         'Salamis',            35.1833, 33.9000, 'cyprus',          'First preached in by Paul and Barnabas in the synagogues.', 'The eastern port of Cyprus where the first journey began its preaching.', 'acts-church', 11),
  ('paphos',          'Paphos',             34.7571, 32.4067, 'cyprus',          'Where the proconsul Sergius Paulus believed.', 'The Cypriot capital where Paul confronted the sorcerer Elymas.', 'acts-church', 12),
  ('perga',           'Perga',              36.9614, 30.8536, 'pamphylia',       'A stop on the first and return journeys.', 'The Pamphylian city where John Mark left Paul and Barnabas.', 'acts-church', 13),
  ('antioch-pisidia', 'Pisidian Antioch',   38.3050, 31.1897, 'galatia',         'Evangelized on the first journey with a landmark synagogue sermon.', 'Where Paul announced he would turn to the Gentiles.', 'acts-church', 14),
  ('iconium',         'Iconium',            37.8746, 32.4932, 'galatia',         'Evangelized on the first journey; revisited to strengthen the disciples.', 'A Galatian city where many Jews and Greeks believed.', 'acts-church', 15),
  ('lystra',          'Lystra',             37.5800, 32.4500, 'galatia',         'Evangelized on the first journey; Paul was stoned here.', 'Home of Timothy, his mother Eunice, and grandmother Lois.', 'acts-church', 16),
  ('derbe',           'Derbe',              37.3500, 33.2667, 'galatia',         'Evangelized on the first journey, making many disciples.', 'Home of Gaius, a traveling companion of Paul.', 'acts-church', 17),
  ('galatia',         'Galatia (region)',   39.0000, 32.5000, 'galatia',         'The cluster of churches that received the letter to the Galatians.', 'The Galatian churches Paul warned against turning to a different gospel.', 'pauline', 18),
  ('ephesus',         'Ephesus',            37.9410, 27.3419, 'asia',            'Founded by Paul on the third journey after Priscilla and Aquila prepared the ground.', 'A major center of mission in Asia; later one of the seven churches of Revelation.', 'pauline', 19),
  ('miletus',         'Miletus',            37.5300, 27.2778, 'asia',            'Where Paul gave his farewell to the Ephesian elders.', 'The port where Paul met the elders of Ephesus for the last time.', 'acts-church', 20),
  ('troas',           'Troas',              39.7494, 26.1611, 'asia',            'A community where Paul broke bread and Eutychus was restored to life.', 'The port from which Paul first crossed into Europe.', 'pauline', 21),
  ('colossae',        'Colossae',           37.7906, 29.2589, 'asia',            'Founded by Epaphras, a co-worker of Paul.', 'A Lycus Valley church that received Paul''s letter though he had never visited.', 'pauline', 22),
  ('laodicea',        'Laodicea',           37.8361, 29.1078, 'asia',            'Founded by Epaphras alongside Colossae and Hierapolis.', 'A Lycus Valley church; later the lukewarm church of Revelation.', 'pauline', 23),
  ('hierapolis',      'Hierapolis',         37.9244, 29.1278, 'asia',            'Founded by Epaphras alongside Colossae and Laodicea.', 'A Lycus Valley church for which Epaphras worked hard.', 'pauline', 24),
  ('smyrna',          'Smyrna',             38.4192, 27.1287, 'asia',            'One of the seven churches addressed in Revelation.', 'A persecuted but spiritually rich church promised the crown of life.', 'revelation-seven', 25),
  ('pergamum',        'Pergamum',           39.1320, 27.1840, 'asia',            'One of the seven churches addressed in Revelation.', 'The church living "where Satan''s throne is," home of the martyr Antipas.', 'revelation-seven', 26),
  ('thyatira',        'Thyatira',           38.9167, 27.8333, 'asia',            'One of the seven churches addressed in Revelation; hometown of Lydia.', 'A church commended for love and faith but tolerating "Jezebel."', 'revelation-seven', 27),
  ('sardis',          'Sardis',             38.4881, 28.0403, 'asia',            'One of the seven churches addressed in Revelation.', 'A church with a reputation for life but called to wake up.', 'revelation-seven', 28),
  ('philadelphia',    'Philadelphia',       38.3500, 28.5167, 'asia',            'One of the seven churches addressed in Revelation.', 'A faithful church set before an open door no one can shut.', 'revelation-seven', 29),
  ('philippi',        'Philippi',           41.0136, 24.2864, 'macedonia',       'Founded when Lydia and her household believed; the first church in Europe.', 'A generous, beloved church that partnered with Paul from the first day.', 'pauline', 30),
  ('thessalonica',    'Thessalonica',       40.6401, 22.9444, 'macedonia',       'Founded on the second journey; the gospel rang out from here.', 'A young church praised for faith, love, and hope amid persecution.', 'pauline', 31),
  ('berea',           'Berea',              40.5236, 22.2030, 'macedonia',       'Founded on the second journey; the Bereans examined the Scriptures daily.', 'A noble-minded church that received the word with eagerness.', 'acts-church', 32),
  ('athens',          'Athens',             37.9838, 23.7275, 'achaia',          'Where Paul reasoned in the synagogue and addressed the Areopagus.', 'A community born from Paul''s sermon on the unknown god.', 'acts-church', 33),
  ('corinth',         'Corinth',            37.9061, 22.8786, 'achaia',          'Founded on the second journey; Paul stayed eighteen months.', 'A gifted but divided church that received two of Paul''s most personal letters.', 'pauline', 34),
  ('cenchreae',       'Cenchreae',          37.8861, 22.9886, 'achaia',          'The eastern port of Corinth with its own community of believers.', 'Home of Phoebe, a deacon and benefactor of the church.', 'pauline', 35),
  ('crete',           'Crete',              35.2401, 24.8093, 'crete',           'A cluster of churches where Titus was left to appoint elders.', 'The island churches Paul charged Titus to set in order.', 'pauline', 36),
  ('rome',            'Rome',               41.9028, 12.4964, 'italia',          'A church already thriving when Paul wrote, founded by unnamed believers.', 'The church at the heart of the empire, greeted by name in Romans 16.', 'pauline', 37),
  ('puteoli',         'Puteoli',            40.8231, 14.1222, 'italia',          'A community of believers who hosted Paul on his way to Rome.', 'The Italian port where Paul found brothers and stayed seven days.', 'acts-church', 38),
  ('alexandria',      'Alexandria',         31.2001, 29.9187, 'egypt',           'The diaspora city that produced Apollos.', 'A great center of the Jewish diaspora and home of Apollos.', 'diaspora-region', 39),
  ('cyrene',          'Cyrene',             32.8250, 21.8583, 'cyrenaica',       'The North African city whose men first preached to Greeks at Antioch.', 'Home of Lucius and of the men of Cyrene who founded the Antioch mission.', 'acts-church', 40),
  ('pontus',          'Pontus',             40.6500, 35.8300, 'pontus-bithynia', 'A diaspora region addressed by Peter; native land of Aquila.', 'One of the regions of the dispersion greeted in 1 Peter.', 'diaspora-region', 41),
  ('cappadocia',      'Cappadocia',         38.6500, 34.8500, 'cappadocia',      'A diaspora region addressed by Peter.', 'One of the regions of the dispersion greeted in 1 Peter.', 'diaspora-region', 42),
  ('bithynia',        'Bithynia',           40.4300, 30.0000, 'pontus-bithynia', 'A diaspora region addressed by Peter.', 'One of the regions of the dispersion greeted in 1 Peter.', 'diaspora-region', 43);

-- ── People ───────────────────────────────────────────────────────────────────
insert into public."FCC_People" (person_id, name, also_known_as, gender, description, scripture_refs) values
  -- Apostles and Jerusalem leadership
  ('paul',              'Paul',                       'Saul of Tarsus',          'M', 'Apostle to the Gentiles; planted churches across the Mediterranean and wrote much of the New Testament.', 'Acts 9; Acts 13-28; Romans 16'),
  ('peter',             'Peter',                      'Simon, Cephas',           'M', 'Leading apostle; preached at Pentecost and opened the gospel to the Gentiles at Caesarea.', 'Acts 1-12; 1 Peter 1:1'),
  ('james-jerusalem',   'James',                      'James the Just',          'M', 'Brother of Jesus and leading elder of the Jerusalem church; presided over the Jerusalem council.', 'Acts 12:17; Acts 15:13; Acts 21:18'),
  ('john-apostle',      'John',                       'the Beloved Disciple',    'M', 'Apostle; later exiled to Patmos, where he received Revelation addressed to the seven churches of Asia.', 'Acts 3-4; Acts 8:14; Revelation 1:9'),
  ('james-zebedee',     'James son of Zebedee',       null,                      'M', 'Apostle; the first of the Twelve to be martyred, killed by Herod Agrippa I.', 'Acts 12:2'),
  ('andrew',            'Andrew',                     null,                      'M', 'Apostle and brother of Peter, among those gathered in the upper room.', 'Acts 1:13'),
  ('matthias',          'Matthias',                   null,                      'M', 'Chosen by lot to replace Judas among the Twelve.', 'Acts 1:23-26'),
  ('matthew',           'Matthew',                    'Levi',                    'M', 'Apostle and former tax collector, among those gathered in the upper room.', 'Acts 1:13'),
  ('thomas',            'Thomas',                     'Didymus',                 'M', 'Apostle, among those gathered in the upper room.', 'Acts 1:13'),
  ('philip-apostle',    'Philip the Apostle',         null,                      'M', 'One of the Twelve, among those gathered in the upper room.', 'Acts 1:13'),
  ('bartholomew',       'Bartholomew',                'Nathanael',               'M', 'Apostle, among those gathered in the upper room.', 'Acts 1:13'),
  ('james-alphaeus',    'James son of Alphaeus',      null,                      'M', 'Apostle, among those gathered in the upper room.', 'Acts 1:13'),
  ('simon-zealot',      'Simon the Zealot',           null,                      'M', 'Apostle, among those gathered in the upper room.', 'Acts 1:13'),
  ('judas-thaddaeus',   'Judas son of James',         'Thaddaeus',               'M', 'Apostle, among those gathered in the upper room.', 'Acts 1:13'),
  -- The Seven
  ('stephen',           'Stephen',                    null,                      'M', 'One of the seven chosen to serve; the first Christian martyr, stoned in Jerusalem.', 'Acts 6:5; Acts 7'),
  ('philip-evangelist', 'Philip the Evangelist',      null,                      'M', 'One of the seven; preached in Samaria and to the Ethiopian eunuch, then settled in Caesarea.', 'Acts 6:5; Acts 8; Acts 21:8'),
  ('prochorus',         'Prochorus',                  null,                      'M', 'One of the seven chosen to serve the Jerusalem church.', 'Acts 6:5'),
  ('nicanor',           'Nicanor',                    null,                      'M', 'One of the seven chosen to serve the Jerusalem church.', 'Acts 6:5'),
  ('timon',             'Timon',                      null,                      'M', 'One of the seven chosen to serve the Jerusalem church.', 'Acts 6:5'),
  ('parmenas',          'Parmenas',                   null,                      'M', 'One of the seven chosen to serve the Jerusalem church.', 'Acts 6:5'),
  ('nicolaus',          'Nicolas of Antioch',         null,                      'M', 'A convert to Judaism from Antioch; one of the seven chosen to serve.', 'Acts 6:5'),
  -- Jerusalem others
  ('mary-mother-jesus', 'Mary',                       'mother of Jesus',         'F', 'Mother of Jesus, among the believers gathered in prayer with the early church.', 'Acts 1:14'),
  ('mary-mother-mark',  'Mary, mother of John Mark',  null,                      'F', 'Hosted a house church in Jerusalem where believers gathered to pray for Peter.', 'Acts 12:12'),
  ('john-mark',         'John Mark',                  'Mark',                    'M', 'Cousin of Barnabas; a traveling companion in mission and the writer of a Gospel.', 'Acts 12:25; Acts 15:37-39; Colossians 4:10'),
  ('rhoda',             'Rhoda',                      null,                      'F', 'Servant girl who recognized Peter''s voice at the door of Mary''s house.', 'Acts 12:13-15'),
  ('barnabas',          'Barnabas',                   'Joseph, Son of Encouragement', 'M', 'A Levite from Cyprus who sold his field for the church, vouched for Saul, and partnered in mission.', 'Acts 4:36-37; Acts 11:22-26; Acts 13-15'),
  ('agabus',            'Agabus',                     null,                      'M', 'A prophet from Jerusalem who foretold a famine and later Paul''s arrest.', 'Acts 11:27-28; Acts 21:10-11'),
  ('judas-barsabbas',   'Judas Barsabbas',            null,                      'M', 'A prophet and leader sent from Jerusalem to deliver the council''s letter to Antioch.', 'Acts 15:22,32'),
  ('silas',             'Silas',                      'Silvanus',                'M', 'A prophet and leader from Jerusalem; Paul''s chosen companion on the second journey.', 'Acts 15:22-40; Acts 16-18; 1 Peter 5:12'),
  ('ananias-jerusalem', 'Ananias',                    null,                      'M', 'With his wife Sapphira, lied to the Holy Spirit about the price of a field.', 'Acts 5:1-6'),
  ('sapphira',          'Sapphira',                   null,                      'F', 'With her husband Ananias, lied to the Holy Spirit about the price of a field.', 'Acts 5:1-10'),
  ('joseph-barsabbas',  'Joseph Barsabbas',           'Justus',                  'M', 'Nominated alongside Matthias as a candidate to replace Judas.', 'Acts 1:23'),
  ('gamaliel',          'Gamaliel',                   null,                      'M', 'A respected Pharisee and teacher of the law who urged the Sanhedrin to restraint.', 'Acts 5:34-39'),
  ('mnason',            'Mnason of Cyprus',           null,                      'M', 'An early disciple from Cyprus who hosted Paul''s company in Judea.', 'Acts 21:16'),
  -- Antioch
  ('simeon-niger',      'Simeon called Niger',        null,                      'M', 'A prophet and teacher in the church at Antioch.', 'Acts 13:1'),
  ('lucius-cyrene',     'Lucius of Cyrene',           null,                      'M', 'A prophet and teacher at Antioch, from the North African city of Cyrene.', 'Acts 13:1'),
  ('manaen',            'Manaen',                     null,                      'M', 'A prophet and teacher at Antioch, raised together with Herod the tetrarch.', 'Acts 13:1'),
  -- Damascus
  ('ananias-damascus',  'Ananias of Damascus',        null,                      'M', 'A disciple who, obeying a vision, restored Saul''s sight and baptized him.', 'Acts 9:10-19'),
  ('judas-damascus',    'Judas of Damascus',          null,                      'M', 'Hosted Saul on the street called Straight after his encounter with the risen Christ.', 'Acts 9:11'),
  -- Joppa, Lydda, Caesarea
  ('tabitha',           'Tabitha',                    'Dorcas',                  'F', 'A disciple in Joppa known for good works and charity, raised to life by Peter.', 'Acts 9:36-42'),
  ('simon-tanner',      'Simon the Tanner',           null,                      'M', 'Hosted Peter at his house by the sea in Joppa.', 'Acts 9:43; Acts 10:6'),
  ('aeneas',            'Aeneas',                     null,                      'M', 'A man in Lydda, paralyzed for eight years, healed by Peter.', 'Acts 9:32-35'),
  ('cornelius',         'Cornelius',                  null,                      'M', 'A devout Roman centurion in Caesarea; the first Gentile convert, with his household.', 'Acts 10'),
  ('philip-daughters',  'The daughters of Philip',    null,                      'F', 'The four unmarried daughters of Philip the evangelist, who prophesied at Caesarea.', 'Acts 21:9'),
  -- Samaria
  ('simon-magus',       'Simon the Sorcerer',         'Simon Magus',             'M', 'Practiced magic in Samaria; believed and was baptized but was rebuked by Peter.', 'Acts 8:9-24'),
  -- Cyprus
  ('sergius-paulus',    'Sergius Paulus',             null,                      'M', 'The Roman proconsul of Cyprus who believed after seeing Elymas struck blind.', 'Acts 13:7-12'),
  ('elymas',            'Elymas',                     'Bar-Jesus',               'M', 'A Jewish sorcerer at Paphos who opposed Paul and was struck blind.', 'Acts 13:6-11'),
  -- Lystra (Timothy''s family)
  ('timothy',           'Timothy',                    null,                      'M', 'Paul''s beloved co-worker from Lystra; entrusted with the care of the church at Ephesus.', 'Acts 16:1-3; 1 Timothy 1:2; Philippians 2:19-22'),
  ('eunice',            'Eunice',                     null,                      'F', 'The believing Jewish mother of Timothy, a woman of sincere faith.', '2 Timothy 1:5; Acts 16:1'),
  ('lois',              'Lois',                       null,                      'F', 'The grandmother of Timothy, a woman of sincere faith.', '2 Timothy 1:5'),
  -- Philippi
  ('lydia',             'Lydia',                      null,                      'F', 'A dealer in purple cloth from Thyatira; the first convert in Philippi and host of the church.', 'Acts 16:14-15,40'),
  ('clement',           'Clement',                    null,                      'M', 'A fellow worker of Paul at Philippi whose name is in the book of life.', 'Philippians 4:3'),
  ('euodia',            'Euodia',                     null,                      'F', 'A woman of the Philippian church urged to be of one mind with Syntyche.', 'Philippians 4:2-3'),
  ('syntyche',          'Syntyche',                   null,                      'F', 'A woman of the Philippian church urged to be of one mind with Euodia.', 'Philippians 4:2-3'),
  ('epaphroditus',      'Epaphroditus',               null,                      'M', 'The messenger of the Philippian church who brought their gift to Paul and nearly died.', 'Philippians 2:25-30; Philippians 4:18'),
  ('jailer-philippi',   'The Philippian jailer',      null,                      'M', 'The keeper of the prison who believed and was baptized with his whole household.', 'Acts 16:25-34'),
  -- Thessalonica
  ('jason',             'Jason',                      null,                      'M', 'Hosted Paul and Silas in Thessalonica and was dragged before the city authorities.', 'Acts 17:5-9'),
  ('aristarchus',       'Aristarchus',                null,                      'M', 'A Macedonian from Thessalonica; Paul''s companion, fellow prisoner, and shipmate.', 'Acts 19:29; Acts 20:4; Acts 27:2; Colossians 4:10'),
  ('secundus',          'Secundus',                   null,                      'M', 'A believer from Thessalonica who traveled with Paul on the third journey.', 'Acts 20:4'),
  ('demas',             'Demas',                      null,                      'M', 'A fellow worker who later deserted Paul, having loved the present world.', 'Colossians 4:14; 2 Timothy 4:10'),
  -- Berea
  ('sopater',           'Sopater of Berea',           'Sosipater',               'M', 'A believer from Berea, son of Pyrrhus, who traveled with Paul.', 'Acts 20:4; Romans 16:21'),
  -- Athens
  ('dionysius',         'Dionysius the Areopagite',   null,                      'M', 'A member of the Areopagus council who believed after Paul''s address in Athens.', 'Acts 17:34'),
  ('damaris',           'Damaris',                    null,                      'F', 'A woman of Athens who believed after hearing Paul speak.', 'Acts 17:34'),
  -- Corinth
  ('crispus',           'Crispus',                    null,                      'M', 'A synagogue ruler in Corinth who believed in the Lord with his entire household.', 'Acts 18:8; 1 Corinthians 1:14'),
  ('sosthenes',         'Sosthenes',                  null,                      'M', 'A synagogue ruler at Corinth; later a brother named with Paul in a letter''s greeting.', 'Acts 18:17; 1 Corinthians 1:1'),
  ('gaius-corinth',     'Gaius',                      null,                      'M', 'A Corinthian believer baptized by Paul who hosted him and the whole church.', 'Romans 16:23; 1 Corinthians 1:14'),
  ('stephanas',         'Stephanas',                  null,                      'M', 'Head of the first household won to Christ in Achaia, devoted to serving the saints.', '1 Corinthians 1:16; 1 Corinthians 16:15-17'),
  ('fortunatus',        'Fortunatus',                 null,                      'M', 'A Corinthian believer who refreshed Paul''s spirit with Stephanas and Achaicus.', '1 Corinthians 16:17'),
  ('achaicus',          'Achaicus',                   null,                      'M', 'A Corinthian believer who refreshed Paul''s spirit with Stephanas and Fortunatus.', '1 Corinthians 16:17'),
  ('chloe',             'Chloe',                      null,                      'F', 'A woman whose household reported the divisions in the Corinthian church to Paul.', '1 Corinthians 1:11'),
  ('erastus',           'Erastus',                    null,                      'M', 'The city treasurer of Corinth and a co-worker of Paul.', 'Romans 16:23; Acts 19:22; 2 Timothy 4:20'),
  ('quartus',           'Quartus',                    null,                      'M', 'A brother in Corinth who sent his greetings in the letter to the Romans.', 'Romans 16:23'),
  ('tertius',           'Tertius',                    null,                      'M', 'The scribe who wrote down the letter to the Romans at Paul''s dictation.', 'Romans 16:22'),
  ('titius-justus',     'Titius Justus',              null,                      'M', 'A worshiper of God in Corinth whose house, next to the synagogue, Paul used for teaching.', 'Acts 18:7'),
  ('phoebe',            'Phoebe',                     null,                      'F', 'A deacon of the church at Cenchreae and a benefactor of many, including Paul.', 'Romans 16:1-2'),
  -- Priscilla, Aquila, Apollos
  ('priscilla',         'Priscilla',                  'Prisca',                  'F', 'A tentmaker who, with her husband Aquila, instructed Apollos and hosted churches in three cities.', 'Acts 18:2,18,26; Romans 16:3-5; 1 Corinthians 16:19'),
  ('aquila',            'Aquila',                     null,                      'M', 'A Jewish tentmaker, a native of Pontus; with Priscilla, a co-worker who hosted house churches.', 'Acts 18:2,18,26; Romans 16:3-5; 1 Corinthians 16:19'),
  ('apollos',           'Apollos',                    null,                      'M', 'An eloquent Jew from Alexandria, mighty in the Scriptures, taught more fully by Priscilla and Aquila.', 'Acts 18:24-28; 1 Corinthians 3:5-6; Titus 3:13'),
  -- Ephesus
  ('tychicus',          'Tychicus',                   null,                      'M', 'A beloved co-worker from Asia who carried several of Paul''s letters to the churches.', 'Acts 20:4; Ephesians 6:21; Colossians 4:7; 2 Timothy 4:12'),
  ('trophimus',         'Trophimus',                  null,                      'M', 'An Ephesian companion of Paul whose presence in Jerusalem sparked the riot against him.', 'Acts 20:4; Acts 21:29; 2 Timothy 4:20'),
  ('onesiphorus',       'Onesiphorus',                null,                      'M', 'An Ephesian who often refreshed Paul and searched him out when he was imprisoned in Rome.', '2 Timothy 1:16-18; 2 Timothy 4:19'),
  ('hymenaeus',         'Hymenaeus',                  null,                      'M', 'A teacher at Ephesus whose faith was shipwrecked; handed over by Paul to be disciplined.', '1 Timothy 1:20; 2 Timothy 2:17'),
  ('alexander-ephesus', 'Alexander the coppersmith',  null,                      'M', 'An Ephesian who did Paul great harm and strongly opposed his message.', '2 Timothy 4:14-15; 1 Timothy 1:20'),
  ('demetrius-ephesus', 'Demetrius the silversmith',  null,                      'M', 'An Ephesian craftsman who stirred up a city-wide riot against Paul.', 'Acts 19:24-29'),
  ('sceva-sons',        'The sons of Sceva',          null,                      'M', 'Seven sons of a Jewish high priest who tried to invoke the name of Jesus in Ephesus.', 'Acts 19:13-16'),
  ('epaenetus',         'Epaenetus',                  null,                      'M', 'The first convert to Christ in the province of Asia, greeted warmly by Paul.', 'Romans 16:5'),
  -- Troas
  ('eutychus',          'Eutychus',                   null,                      'M', 'A young man of Troas who fell from a window during Paul''s long sermon and was restored to life.', 'Acts 20:7-12'),
  ('carpus',            'Carpus',                     null,                      'M', 'A believer at Troas with whom Paul left his cloak and scrolls.', '2 Timothy 4:13'),
  -- Colossae and the Lycus Valley
  ('philemon',          'Philemon',                   null,                      'M', 'A wealthy Colossian believer who hosted a church in his home.', 'Philemon 1:1-2'),
  ('apphia',            'Apphia',                     null,                      'F', 'A believer at Colossae, addressed by Paul alongside Philemon.', 'Philemon 1:2'),
  ('archippus',         'Archippus',                  null,                      'M', 'A believer at Colossae urged to complete the ministry he had received in the Lord.', 'Colossians 4:17; Philemon 1:2'),
  ('onesimus',          'Onesimus',                   null,                      'M', 'A runaway slave of Philemon who became a beloved brother through Paul.', 'Philemon 1:10-16; Colossians 4:9'),
  ('epaphras',          'Epaphras',                   null,                      'M', 'A Colossian who founded the churches of the Lycus Valley and labored in prayer for them.', 'Colossians 1:7; Colossians 4:12-13; Philemon 1:23'),
  ('nympha',            'Nympha',                     null,                      'F', 'A believer who hosted a church in her house in the region of Laodicea.', 'Colossians 4:15'),
  -- Crete
  ('titus',             'Titus',                      null,                      'M', 'A Greek co-worker of Paul, left in Crete to appoint elders in every town.', 'Titus 1:4-5; 2 Corinthians 8:23; Galatians 2:1-3'),
  ('zenas',             'Zenas',                      null,                      'M', 'A lawyer whom Paul asked the Cretan churches to help on his way, along with Apollos.', 'Titus 3:13'),
  ('artemas',           'Artemas',                    null,                      'M', 'A co-worker Paul considered sending to Crete to relieve Titus.', 'Titus 3:12'),
  -- Rome (Romans 16 greetings)
  ('mary-rome',         'Mary',                       null,                      'F', 'A worker in the Roman church who labored hard for the believers there.', 'Romans 16:6'),
  ('andronicus',        'Andronicus',                 null,                      'M', 'A kinsman and fellow prisoner of Paul, outstanding among the apostles.', 'Romans 16:7'),
  ('junia',             'Junia',                      null,                      'F', 'A kinswoman and fellow prisoner of Paul, outstanding among the apostles.', 'Romans 16:7'),
  ('ampliatus',         'Ampliatus',                  null,                      'M', 'A beloved friend of Paul in the Roman church.', 'Romans 16:8'),
  ('urbanus',           'Urbanus',                    null,                      'M', 'A fellow worker of Paul in Christ, greeted in Rome.', 'Romans 16:9'),
  ('stachys',           'Stachys',                    null,                      'M', 'A beloved friend of Paul in the Roman church.', 'Romans 16:9'),
  ('apelles',           'Apelles',                    null,                      'M', 'A believer in Rome approved and tested in Christ.', 'Romans 16:10'),
  ('aristobulus-household', 'The household of Aristobulus', null,                'M', 'A household in Rome greeted by Paul.', 'Romans 16:10'),
  ('herodion',          'Herodion',                   null,                      'M', 'A kinsman of Paul in the Roman church.', 'Romans 16:11'),
  ('narcissus-household', 'The household of Narcissus', null,                    'M', 'Those of the household of Narcissus who were in the Lord.', 'Romans 16:11'),
  ('tryphaena',         'Tryphaena',                  null,                      'F', 'A woman who worked hard in the Lord, greeted in Rome.', 'Romans 16:12'),
  ('tryphosa',          'Tryphosa',                   null,                      'F', 'A woman who worked hard in the Lord, greeted in Rome.', 'Romans 16:12'),
  ('persis',            'Persis',                     null,                      'F', 'A beloved woman who worked very hard in the Lord.', 'Romans 16:12'),
  ('rufus',             'Rufus',                      null,                      'M', 'A believer chosen in the Lord, greeted with his mother in Rome.', 'Romans 16:13'),
  ('rufus-mother',      'The mother of Rufus',        null,                      'F', 'A woman who had been like a mother to Paul as well.', 'Romans 16:13'),
  ('asyncritus',        'Asyncritus',                 null,                      'M', 'A believer in Rome greeted by Paul.', 'Romans 16:14'),
  ('phlegon',           'Phlegon',                    null,                      'M', 'A believer in Rome greeted by Paul.', 'Romans 16:14'),
  ('hermes',            'Hermes',                     null,                      'M', 'A believer in Rome greeted by Paul.', 'Romans 16:14'),
  ('patrobas',          'Patrobas',                   null,                      'M', 'A believer in Rome greeted by Paul.', 'Romans 16:14'),
  ('hermas',            'Hermas',                     null,                      'M', 'A believer in Rome greeted by Paul.', 'Romans 16:14'),
  ('philologus',        'Philologus',                 null,                      'M', 'A believer in Rome greeted by Paul.', 'Romans 16:15'),
  ('julia',             'Julia',                      null,                      'F', 'A believer in Rome greeted by Paul.', 'Romans 16:15'),
  ('nereus',            'Nereus',                     null,                      'M', 'A believer in Rome greeted by Paul.', 'Romans 16:15'),
  ('nereus-sister',     'The sister of Nereus',       null,                      'F', 'A believer in Rome greeted alongside her brother.', 'Romans 16:15'),
  ('olympas',           'Olympas',                    null,                      'M', 'A believer in Rome greeted by Paul.', 'Romans 16:15'),
  -- Rome (Paul''s imprisonment circle)
  ('luke',              'Luke',                       'the beloved physician',   'M', 'A physician and Paul''s faithful companion; author of the Gospel of Luke and Acts.', 'Colossians 4:14; 2 Timothy 4:11; Acts 16:10-17'),
  ('jesus-justus',      'Jesus called Justus',        null,                      'M', 'A Jewish co-worker of Paul, a comfort to him during his imprisonment.', 'Colossians 4:11'),
  ('pudens',            'Pudens',                     null,                      'M', 'A believer in Rome who sent greetings to Timothy through Paul.', '2 Timothy 4:21'),
  ('linus',             'Linus',                      null,                      'M', 'A believer in Rome who sent greetings to Timothy through Paul.', '2 Timothy 4:21'),
  ('claudia',           'Claudia',                    null,                      'F', 'A believer in Rome who sent greetings to Timothy through Paul.', '2 Timothy 4:21'),
  ('eubulus',           'Eubulus',                    null,                      'M', 'A believer in Rome who sent greetings to Timothy through Paul.', '2 Timothy 4:21'),
  ('crescens',          'Crescens',                   null,                      'M', 'A co-worker who left Paul to go to Galatia.', '2 Timothy 4:10'),
  ('gaius-derbe',       'Gaius of Derbe',             null,                      'M', 'A believer from Derbe who traveled with Paul on the third journey.', 'Acts 20:4'),
  -- Revelation seven churches
  ('antipas',           'Antipas',                    null,                      'M', 'The faithful witness of Pergamum who was put to death where Satan dwells.', 'Revelation 2:13'),
  ('jezebel-thyatira',  'The woman called Jezebel',   null,                      'F', 'A woman in Thyatira who called herself a prophetess and led believers astray.', 'Revelation 2:20-23'),
  -- Other
  ('theophilus',        'Theophilus',                 null,                      'M', 'The honored recipient of Luke''s Gospel and the Acts of the Apostles.', 'Luke 1:3; Acts 1:1');

-- ── Households ───────────────────────────────────────────────────────────────
insert into public."FCC_Households" (household_id, name, church_id, head_person_id, description, scripture_ref) values
  ('household-mary-mark',   'House church of Mary',                  'jerusalem', 'mary-mother-mark',       'Believers gathered to pray in Mary''s home in Jerusalem the night Peter was freed from prison.', 'Acts 12:12'),
  ('household-cornelius',   'Household of Cornelius',                'caesarea',  'cornelius',              'The centurion''s relatives and close friends, the first Gentiles to receive the Holy Spirit.', 'Acts 10:24-48'),
  ('household-lydia',       'House church of Lydia',                 'philippi',  'lydia',                  'Lydia''s household, baptized together and hosting the gathering of Philippian believers.', 'Acts 16:14-15,40'),
  ('household-jailer',      'Household of the Philippian jailer',    'philippi',  'jailer-philippi',        'The jailer''s household, all baptized the same night they came to believe.', 'Acts 16:31-34'),
  ('household-stephanas',   'Household of Stephanas',                'corinth',   'stephanas',              'The first converts in Achaia, who devoted themselves to the service of the saints.', '1 Corinthians 16:15-17'),
  ('household-crispus',     'Household of Crispus',                  'corinth',   'crispus',                'The synagogue ruler''s household, who believed in the Lord together with him.', 'Acts 18:8'),
  ('household-chloe',       'Household of Chloe',                    'corinth',   'chloe',                  'Chloe''s people, who carried news of the divisions at Corinth to Paul.', '1 Corinthians 1:11'),
  ('household-titius',      'House of Titius Justus',                'corinth',   'titius-justus',          'The house of a God-fearer, next door to the synagogue, where Paul taught.', 'Acts 18:7'),
  ('household-gaius',       'House church of Gaius',                 'corinth',   'gaius-corinth',          'The home of Gaius, host to Paul and to the whole Corinthian church.', 'Romans 16:23'),
  ('household-philemon',    'House church of Philemon',              'colossae',  'philemon',               'The church that gathered in Philemon''s home in Colossae.', 'Philemon 1:1-2'),
  ('household-nympha',      'House church of Nympha',                'laodicea',  'nympha',                 'The church that met in Nympha''s house in the region of Laodicea.', 'Colossians 4:15'),
  ('household-pa-ephesus',  'House church of Priscilla and Aquila (Ephesus)', 'ephesus', 'aquila',          'A church that met in the home of Priscilla and Aquila while they lived in Ephesus.', '1 Corinthians 16:19'),
  ('household-pa-rome',     'House church of Priscilla and Aquila (Rome)',    'rome',    'aquila',          'A church that met in the home of Priscilla and Aquila in Rome.', 'Romans 16:3-5'),
  ('household-aristobulus', 'Household of Aristobulus',              'rome',      'aristobulus-household',  'A Roman household greeted by Paul in his letter.', 'Romans 16:10'),
  ('household-narcissus',   'Household of Narcissus',                'rome',      'narcissus-household',    'Those of the household of Narcissus who were in the Lord.', 'Romans 16:11'),
  ('household-onesiphorus', 'Household of Onesiphorus',              'ephesus',   'onesiphorus',            'A household that often refreshed Paul and was unashamed of his chains.', '2 Timothy 1:16; 2 Timothy 4:19');

commit;
