-- Seed data for the First Century Church Directory:
-- memberships (the person <-> church join) and church-level scripture references.
-- A person who traveled between churches has multiple membership rows here.

begin;

-- ── Memberships ──────────────────────────────────────────────────────────────
insert into public."FCC_Memberships"
  (person_id, church_id, household_id, role, context, scripture_ref, is_primary) values

  -- Paul — the hub of the first-century mission
  ('paul', 'jerusalem',       null, 'apostle',     'Received by the apostles after his conversion and disputed with the Hellenists.', 'Acts 9:26-29', false),
  ('paul', 'damascus',        null, 'member',      'Began to proclaim Jesus in the synagogues right after his conversion.', 'Acts 9:19-22', false),
  ('paul', 'antioch',         null, 'co-worker',   'Taught here for a year and was sent out by the church as a missionary.', 'Acts 11:25-26; Acts 13:1-3', false),
  ('paul', 'salamis',         null, 'co-worker',   'Proclaimed the word of God in the synagogues of Salamis.', 'Acts 13:4-5', false),
  ('paul', 'paphos',          null, 'co-worker',   'Confronted the sorcerer Elymas and saw the proconsul believe.', 'Acts 13:6-12', false),
  ('paul', 'antioch-pisidia', null, 'founder',     'Preached a landmark synagogue sermon and turned to the Gentiles.', 'Acts 13:14-52', false),
  ('paul', 'iconium',         null, 'founder',     'Spoke boldly so that many Jews and Greeks believed.', 'Acts 14:1-7', false),
  ('paul', 'lystra',          null, 'founder',     'Healed a lame man, was mistaken for a god, then stoned.', 'Acts 14:8-20', false),
  ('paul', 'derbe',           null, 'founder',     'Preached the gospel and made many disciples.', 'Acts 14:20-21', false),
  ('paul', 'galatia',         null, 'founder',     'Wrote to the Galatian churches warning against a different gospel.', 'Galatians 1:1-9', true),
  ('paul', 'troas',           null, 'founder',     'Received the vision of the Macedonian man and later raised Eutychus.', 'Acts 16:8-10; Acts 20:5-12', false),
  ('paul', 'philippi',        null, 'founder',     'Planted the first church in Europe, beginning with Lydia.', 'Acts 16:11-40', false),
  ('paul', 'thessalonica',    null, 'founder',     'Reasoned in the synagogue for three Sabbaths before opposition arose.', 'Acts 17:1-9', false),
  ('paul', 'berea',           null, 'founder',     'Found the Bereans noble for examining the Scriptures daily.', 'Acts 17:10-15', false),
  ('paul', 'athens',          null, 'founder',     'Addressed the Areopagus about the unknown god.', 'Acts 17:16-34', false),
  ('paul', 'corinth',         null, 'founder',     'Stayed eighteen months, supporting himself as a tentmaker.', 'Acts 18:1-17', false),
  ('paul', 'cenchreae',       null, 'mentioned',   'Cut his hair here for a vow before sailing for Syria.', 'Acts 18:18', false),
  ('paul', 'ephesus',         null, 'founder',     'Taught for over two years until the word spread through all Asia.', 'Acts 19:1-20', false),
  ('paul', 'miletus',         null, 'mentioned',   'Summoned the Ephesian elders for a final, tearful farewell.', 'Acts 20:15-38', false),
  ('paul', 'tyre',            null, 'mentioned',   'Knelt on the beach to pray with the disciples and their families.', 'Acts 21:3-6', false),
  ('paul', 'caesarea',        null, 'mentioned',   'Stayed with Philip the evangelist on the way to Jerusalem.', 'Acts 21:8-14', false),
  ('paul', 'crete',           null, 'founder',     'Left Titus behind to appoint elders in every town.', 'Titus 1:5', false),
  ('paul', 'puteoli',         null, 'mentioned',   'Found believers here and stayed seven days on the way to Rome.', 'Acts 28:13-14', false),
  ('paul', 'rome',            null, 'apostle',     'Wrote to the Roman church and later reached the city as a prisoner.', 'Romans 1:7-15; Acts 28:16-31', false),
  ('paul', 'colossae',        null, 'mentioned',   'Wrote to the Colossians though he had never seen them face to face.', 'Colossians 2:1', false),

  -- Peter
  ('peter', 'jerusalem',  null, 'apostle', 'Preached at Pentecost and led the apostles in the mother church.', 'Acts 2:14-41', true),
  ('peter', 'samaria',    null, 'apostle', 'Sent with John to lay hands on the Samaritan believers.', 'Acts 8:14-25', false),
  ('peter', 'lydda',      null, 'apostle', 'Healed the paralyzed Aeneas.', 'Acts 9:32-35', false),
  ('peter', 'joppa',      null, 'apostle', 'Raised Tabitha and received the vision opening the gospel to Gentiles.', 'Acts 9:36-43; Acts 10:9-23', false),
  ('peter', 'caesarea',   null, 'apostle', 'Preached to Cornelius and saw the Spirit fall on the Gentiles.', 'Acts 10:24-48', false),
  ('peter', 'antioch',    null, 'apostle', 'Visited Antioch, where Paul opposed him over table fellowship.', 'Galatians 2:11-14', false),
  ('peter', 'pontus',     null, 'apostle', 'Addressed the scattered believers of the dispersion.', '1 Peter 1:1', false),
  ('peter', 'cappadocia', null, 'apostle', 'Addressed the scattered believers of the dispersion.', '1 Peter 1:1', false),
  ('peter', 'bithynia',   null, 'apostle', 'Addressed the scattered believers of the dispersion.', '1 Peter 1:1', false),

  -- James, John, and the Twelve at Jerusalem
  ('james-jerusalem', 'jerusalem', null, 'overseer', 'Led the Jerusalem church and presided over the Jerusalem council.', 'Acts 15:13-21; Acts 21:18', true),
  ('john-apostle', 'jerusalem',    null, 'apostle', 'Stood with Peter before the Sanhedrin in the early days of the church.', 'Acts 3:1-11; Acts 4:1-22', true),
  ('john-apostle', 'samaria',      null, 'apostle', 'Sent with Peter to the Samaritan believers.', 'Acts 8:14-17', false),
  ('john-apostle', 'ephesus',      null, 'prophet', 'Recorded the risen Christ''s message to the church at Ephesus.', 'Revelation 2:1-7', false),
  ('john-apostle', 'smyrna',       null, 'prophet', 'Recorded the risen Christ''s message to the church at Smyrna.', 'Revelation 2:8-11', false),
  ('john-apostle', 'pergamum',     null, 'prophet', 'Recorded the risen Christ''s message to the church at Pergamum.', 'Revelation 2:12-17', false),
  ('john-apostle', 'thyatira',     null, 'prophet', 'Recorded the risen Christ''s message to the church at Thyatira.', 'Revelation 2:18-29', false),
  ('john-apostle', 'sardis',       null, 'prophet', 'Recorded the risen Christ''s message to the church at Sardis.', 'Revelation 3:1-6', false),
  ('john-apostle', 'philadelphia', null, 'prophet', 'Recorded the risen Christ''s message to the church at Philadelphia.', 'Revelation 3:7-13', false),
  ('john-apostle', 'laodicea',     null, 'prophet', 'Recorded the risen Christ''s message to the church at Laodicea.', 'Revelation 3:14-22', false),
  ('james-zebedee',   'jerusalem', null, 'apostle', 'An apostle of the mother church; the first of the Twelve to be martyred.', 'Acts 12:1-2', true),
  ('andrew',          'jerusalem', null, 'apostle', 'Among the apostles gathered in the upper room.', 'Acts 1:13', true),
  ('matthias',        'jerusalem', null, 'apostle', 'Chosen by lot to complete the Twelve.', 'Acts 1:23-26', true),
  ('matthew',         'jerusalem', null, 'apostle', 'Among the apostles gathered in the upper room.', 'Acts 1:13', true),
  ('thomas',          'jerusalem', null, 'apostle', 'Among the apostles gathered in the upper room.', 'Acts 1:13', true),
  ('philip-apostle',  'jerusalem', null, 'apostle', 'Among the apostles gathered in the upper room.', 'Acts 1:13', true),
  ('bartholomew',     'jerusalem', null, 'apostle', 'Among the apostles gathered in the upper room.', 'Acts 1:13', true),
  ('james-alphaeus',  'jerusalem', null, 'apostle', 'Among the apostles gathered in the upper room.', 'Acts 1:13', true),
  ('simon-zealot',    'jerusalem', null, 'apostle', 'Among the apostles gathered in the upper room.', 'Acts 1:13', true),
  ('judas-thaddaeus', 'jerusalem', null, 'apostle', 'Among the apostles gathered in the upper room.', 'Acts 1:13', true),
  ('joseph-barsabbas','jerusalem', null, 'member',  'Nominated alongside Matthias to replace Judas.', 'Acts 1:23', true),

  -- The Seven and other Jerusalem believers
  ('stephen',           'jerusalem', 'household-mary-mark', 'deacon', 'Chosen to serve the widows; became the first Christian martyr.', 'Acts 6:5; Acts 7:54-60', true),
  ('prochorus',         'jerusalem', null, 'deacon', 'One of the seven chosen to serve the Jerusalem church.', 'Acts 6:5', true),
  ('nicanor',           'jerusalem', null, 'deacon', 'One of the seven chosen to serve the Jerusalem church.', 'Acts 6:5', true),
  ('timon',             'jerusalem', null, 'deacon', 'One of the seven chosen to serve the Jerusalem church.', 'Acts 6:5', true),
  ('parmenas',          'jerusalem', null, 'deacon', 'One of the seven chosen to serve the Jerusalem church.', 'Acts 6:5', true),
  ('nicolaus',          'jerusalem', null, 'deacon', 'One of the seven chosen to serve the Jerusalem church.', 'Acts 6:5', true),
  ('nicolaus',          'antioch',   null, 'member', 'A convert to Judaism originally from Antioch.', 'Acts 6:5', false),
  ('philip-evangelist', 'jerusalem', null, 'deacon', 'One of the seven chosen to serve the widows of the church.', 'Acts 6:5', false),
  ('philip-evangelist', 'samaria',   null, 'founder', 'Proclaimed Christ in Samaria with signs and great joy.', 'Acts 8:4-13', false),
  ('philip-evangelist', 'caesarea',  null, 'member',  'Settled in Caesarea with his four prophesying daughters.', 'Acts 21:8-9', true),
  ('mary-mother-jesus', 'jerusalem', null, 'member', 'Joined the believers in constant prayer in the upper room.', 'Acts 1:14', true),
  ('mary-mother-mark',  'jerusalem', 'household-mary-mark', 'host-of-house-church', 'Hosted the church that gathered to pray during Peter''s imprisonment.', 'Acts 12:12', true),
  ('rhoda',             'jerusalem', 'household-mary-mark', 'member', 'A servant girl who recognized Peter''s voice at the gate.', 'Acts 12:13-15', true),
  ('ananias-jerusalem', 'jerusalem', null, 'member', 'Lied with Sapphira about the price of a field they sold.', 'Acts 5:1-6', true),
  ('sapphira',          'jerusalem', null, 'member', 'Lied with Ananias about the price of a field they sold.', 'Acts 5:7-10', true),
  ('gamaliel',          'jerusalem', null, 'teacher', 'A Pharisee who urged the Sanhedrin to leave the apostles alone.', 'Acts 5:34-39', true),
  ('mnason',            'jerusalem', null, 'host-of-house-church', 'An early disciple from Cyprus who hosted Paul''s company in Judea.', 'Acts 21:16', false),
  ('mnason',            'salamis',   null, 'member', 'An early disciple of the Cypriot church.', 'Acts 21:16', true),

  -- Barnabas — Cyprus, Antioch, and the first journey
  ('barnabas', 'jerusalem',       null, 'member',    'A Levite who sold his field and laid the money at the apostles'' feet.', 'Acts 4:36-37', false),
  ('barnabas', 'antioch',         null, 'founder',   'Sent from Jerusalem to nurture the new church, then taught alongside Paul.', 'Acts 11:22-26', true),
  ('barnabas', 'salamis',         null, 'co-worker', 'Began the first journey preaching in his native Cyprus.', 'Acts 13:4-5', false),
  ('barnabas', 'paphos',          null, 'co-worker', 'Stood with Paul as the proconsul of Cyprus believed.', 'Acts 13:6-12', false),
  ('barnabas', 'antioch-pisidia', null, 'founder',   'Helped plant the church and turned with Paul to the Gentiles.', 'Acts 13:14-52', false),
  ('barnabas', 'iconium',         null, 'founder',   'Preached so that many Jews and Greeks believed.', 'Acts 14:1-7', false),
  ('barnabas', 'lystra',          null, 'founder',   'Was mistaken for the god Zeus by the crowd.', 'Acts 14:8-20', false),
  ('barnabas', 'derbe',           null, 'founder',   'Made many disciples before retracing the route to strengthen them.', 'Acts 14:20-21', false),

  -- Prophets and leaders sent between churches
  ('agabus',         'jerusalem', null, 'prophet',        'A prophet of the Jerusalem church.', 'Acts 11:27-28', true),
  ('agabus',         'antioch',   null, 'prophet',        'Foretold a severe famine, prompting the relief collection.', 'Acts 11:27-30', false),
  ('agabus',         'caesarea',  null, 'prophet',        'Foretold Paul''s arrest by binding his own hands with Paul''s belt.', 'Acts 21:10-11', false),
  ('judas-barsabbas','jerusalem', null, 'prophet',        'A leading prophet among the Jerusalem believers.', 'Acts 15:22,32', true),
  ('judas-barsabbas','antioch',   null, 'letter-carrier', 'Carried and confirmed the council''s letter to the church at Antioch.', 'Acts 15:22-33', false),
  ('silas', 'jerusalem',    null, 'prophet',        'A leading prophet chosen to represent the Jerusalem church.', 'Acts 15:22,32', true),
  ('silas', 'antioch',      null, 'letter-carrier', 'Carried the council''s letter and encouraged the church at Antioch.', 'Acts 15:22-35', false),
  ('silas', 'lystra',       null, 'traveling-companion', 'Joined Paul on the second journey, picking up Timothy here.', 'Acts 16:1-5', false),
  ('silas', 'philippi',     null, 'traveling-companion', 'Imprisoned with Paul and sang hymns at midnight.', 'Acts 16:19-40', false),
  ('silas', 'thessalonica', null, 'traveling-companion', 'Reasoned with Paul in the synagogue before the believers sent them away.', 'Acts 17:1-10', false),
  ('silas', 'berea',        null, 'traveling-companion', 'Remained in Berea with Timothy as Paul went ahead to Athens.', 'Acts 17:10-15', false),
  ('silas', 'corinth',      null, 'traveling-companion', 'Rejoined Paul from Macedonia as he preached in Corinth.', 'Acts 18:5', false),
  ('silas', 'rome',         null, 'co-worker',      'Helped Peter write to the dispersion from the city Peter calls "Babylon."', '1 Peter 5:12-13', false),

  -- Antioch leadership
  ('simeon-niger',  'antioch', null, 'teacher', 'A prophet and teacher in the church at Antioch.', 'Acts 13:1', true),
  ('lucius-cyrene', 'antioch', null, 'prophet', 'A prophet and teacher at Antioch, among the men of Cyrene who first preached to Greeks.', 'Acts 11:20; Acts 13:1', true),
  ('lucius-cyrene', 'cyrene',  null, 'member',  'One of the men of Cyrene who carried the gospel to the Greeks of Antioch.', 'Acts 11:20', false),
  ('manaen',        'antioch', null, 'teacher', 'A prophet and teacher at Antioch, raised together with Herod the tetrarch.', 'Acts 13:1', true),

  -- Damascus
  ('ananias-damascus', 'damascus', null, 'member',               'Obeyed a vision to restore Saul''s sight and baptize him.', 'Acts 9:10-19', true),
  ('judas-damascus',   'damascus', null, 'host-of-house-church', 'Hosted the blinded Saul on the street called Straight.', 'Acts 9:11', true),

  -- Joppa, Lydda, Caesarea
  ('tabitha',          'joppa',    null, 'member',               'A disciple full of good works, raised to life by Peter.', 'Acts 9:36-42', true),
  ('simon-tanner',     'joppa',    null, 'host-of-house-church', 'Hosted Peter at his house by the sea.', 'Acts 9:43; Acts 10:6', true),
  ('aeneas',           'lydda',    null, 'member',               'Bedridden eight years until Peter healed him in Jesus'' name.', 'Acts 9:32-35', true),
  ('cornelius',        'caesarea', 'household-cornelius', 'convert', 'A devout centurion; the first Gentile to receive the gospel and the Spirit.', 'Acts 10:1-48', true),
  ('philip-daughters', 'caesarea', null, 'prophet',              'The four unmarried daughters of Philip the evangelist, who prophesied.', 'Acts 21:9', true),

  -- Samaria and Cyprus
  ('simon-magus',   'samaria', null, 'convert',  'A magician who believed and was baptized but was rebuked for his heart.', 'Acts 8:9-24', true),
  ('sergius-paulus','paphos',  null, 'convert',  'The Roman proconsul of Cyprus who believed at Paul''s teaching.', 'Acts 13:7-12', true),
  ('elymas',        'paphos',  null, 'opponent', 'A Jewish sorcerer who opposed Paul and was struck blind.', 'Acts 13:6-11', true),

  -- Lystra: Timothy and his family
  ('timothy', 'lystra',       null, 'member',    'Grew up here, well spoken of, and was chosen by Paul as a co-worker.', 'Acts 16:1-3', true),
  ('timothy', 'iconium',      null, 'mentioned', 'Also well spoken of by the believers at nearby Iconium.', 'Acts 16:2', false),
  ('timothy', 'philippi',     null, 'co-worker', 'Served alongside Paul, who praised his proven worth to the Philippians.', 'Philippians 2:19-22', false),
  ('timothy', 'thessalonica', null, 'co-worker', 'Sent back to strengthen and encourage the young church.', '1 Thessalonians 3:1-6', false),
  ('timothy', 'berea',        null, 'co-worker', 'Remained in Berea with Silas before rejoining Paul.', 'Acts 17:14', false),
  ('timothy', 'corinth',      null, 'co-worker', 'Sent to remind the Corinthians of Paul''s ways in Christ.', '1 Corinthians 4:17; 1 Corinthians 16:10', false),
  ('timothy', 'ephesus',      null, 'overseer',  'Left in charge of the church to guard sound teaching.', '1 Timothy 1:3', false),
  ('timothy', 'troas',        null, 'traveling-companion', 'Went ahead of Paul and waited for him at Troas.', 'Acts 20:4-5', false),
  ('timothy', 'rome',         null, 'co-worker', 'With Paul during his imprisonment and named in his prison letters.', 'Philippians 1:1; Colossians 1:1', false),
  ('eunice',  'lystra', null, 'member', 'Timothy''s believing Jewish mother, a woman of sincere faith.', 'Acts 16:1; 2 Timothy 1:5', true),
  ('lois',    'lystra', null, 'member', 'Timothy''s grandmother, in whom faith first dwelt.', '2 Timothy 1:5', true),

  -- Philippi
  ('lydia',           'philippi', 'household-lydia', 'host-of-house-church', 'A dealer in purple and the first convert in Europe; hosted the church.', 'Acts 16:14-15,40', true),
  ('lydia',           'thyatira', null, 'member',    'A native of Thyatira before her trade brought her to Philippi.', 'Acts 16:14', false),
  ('clement',         'philippi', null, 'co-worker', 'A fellow worker of Paul whose name is in the book of life.', 'Philippians 4:3', true),
  ('euodia',          'philippi', null, 'member',    'A woman urged to be of the same mind as Syntyche.', 'Philippians 4:2-3', true),
  ('syntyche',        'philippi', null, 'member',    'A woman urged to be of the same mind as Euodia.', 'Philippians 4:2-3', true),
  ('epaphroditus',    'philippi', null, 'letter-carrier', 'Brought the church''s gift to Paul and carried his letter back.', 'Philippians 2:25-30; Philippians 4:18', true),
  ('epaphroditus',    'rome',     null, 'co-worker', 'Served Paul in prison and nearly died for the work of Christ.', 'Philippians 2:27-30', false),
  ('jailer-philippi', 'philippi', 'household-jailer', 'convert', 'The keeper of the prison, baptized with his household the night of the earthquake.', 'Acts 16:25-34', true),

  -- Thessalonica
  ('jason',       'thessalonica', null, 'host-of-house-church', 'Hosted Paul and Silas and was dragged before the city authorities.', 'Acts 17:5-9', true),
  ('jason',       'corinth',      null, 'relative',  'A kinsman of Paul who sent greetings from Corinth.', 'Romans 16:21', false),
  ('aristarchus', 'thessalonica', null, 'member',    'A Macedonian believer of the Thessalonian church.', 'Acts 20:4', true),
  ('aristarchus', 'ephesus',      null, 'traveling-companion', 'Seized by the rioting crowd in the theater at Ephesus.', 'Acts 19:29', false),
  ('aristarchus', 'rome',         null, 'co-worker', 'Paul''s fellow prisoner who sent greetings to the Colossians.', 'Colossians 4:10; Acts 27:2', false),
  ('secundus',    'thessalonica', null, 'traveling-companion', 'A Thessalonian who accompanied Paul on the third journey.', 'Acts 20:4', true),
  ('demas',       'rome',         null, 'co-worker', 'A fellow worker during Paul''s imprisonment who later fell away.', 'Colossians 4:14', true),
  ('demas',       'thessalonica', null, 'member',    'Deserted Paul and departed for Thessalonica, in love with the present world.', '2 Timothy 4:10', false),

  -- Berea
  ('sopater', 'berea',   null, 'member',   'A Berean believer, son of Pyrrhus, who traveled with Paul.', 'Acts 20:4', true),
  ('sopater', 'corinth', null, 'relative', 'A kinsman of Paul who sent greetings to Rome from Corinth.', 'Romans 16:21', false),

  -- Athens
  ('dionysius', 'athens', null, 'convert', 'A member of the Areopagus council who believed at Paul''s address.', 'Acts 17:34', true),
  ('damaris',   'athens', null, 'convert', 'A woman of Athens who believed at Paul''s address.', 'Acts 17:34', true),

  -- Corinth
  ('crispus',      'corinth',   'household-crispus', 'convert', 'A synagogue ruler who believed in the Lord with his whole household.', 'Acts 18:8; 1 Corinthians 1:14', true),
  ('sosthenes',    'corinth',   null, 'member',     'A synagogue ruler at Corinth, beaten before the judgment seat.', 'Acts 18:17', true),
  ('sosthenes',    'ephesus',   null, 'co-worker',  'Named with Paul as a brother when he wrote to Corinth from Ephesus.', '1 Corinthians 1:1', false),
  ('gaius-corinth','corinth',   'household-gaius', 'host-of-house-church', 'Baptized by Paul; host to him and to the whole church.', 'Romans 16:23; 1 Corinthians 1:14', true),
  ('stephanas',    'corinth',   'household-stephanas', 'host-of-house-church', 'Head of the first household won in Achaia, devoted to the saints.', '1 Corinthians 1:16; 1 Corinthians 16:15', true),
  ('stephanas',    'ephesus',   null, 'traveling-companion', 'Visited Paul at Ephesus and refreshed his spirit.', '1 Corinthians 16:17-18', false),
  ('fortunatus',   'corinth',   'household-stephanas', 'member', 'A Corinthian believer of the household of Stephanas.', '1 Corinthians 16:17', true),
  ('fortunatus',   'ephesus',   null, 'traveling-companion', 'Visited Paul at Ephesus and refreshed his spirit.', '1 Corinthians 16:17-18', false),
  ('achaicus',     'corinth',   'household-stephanas', 'member', 'A Corinthian believer of the household of Stephanas.', '1 Corinthians 16:17', true),
  ('achaicus',     'ephesus',   null, 'traveling-companion', 'Visited Paul at Ephesus and refreshed his spirit.', '1 Corinthians 16:17-18', false),
  ('chloe',        'corinth',   'household-chloe', 'member', 'A woman whose household reported the church''s divisions to Paul.', '1 Corinthians 1:11', true),
  ('erastus',      'corinth',   null, 'co-worker',  'The city treasurer of Corinth and a co-worker of Paul.', 'Romans 16:23', true),
  ('erastus',      'ephesus',   null, 'co-worker',  'Sent ahead from Ephesus into Macedonia to help Paul.', 'Acts 19:22', false),
  ('quartus',      'corinth',   null, 'member',     'A brother at Corinth who sent his greetings to Rome.', 'Romans 16:23', true),
  ('tertius',      'corinth',   null, 'member',     'Wrote down the letter to the Romans at Paul''s dictation.', 'Romans 16:22', true),
  ('tertius',      'rome',      null, 'greeted',    'Added his own greeting to the believers in Rome.', 'Romans 16:22', false),
  ('titius-justus','corinth',   'household-titius', 'host-of-house-church', 'A God-fearer whose house, next to the synagogue, Paul used for teaching.', 'Acts 18:7', true),
  ('phoebe',       'cenchreae', null, 'deacon',     'A deacon of the church at Cenchreae and a benefactor of many.', 'Romans 16:1-2', true),
  ('phoebe',       'rome',      null, 'letter-carrier', 'Carried Paul''s letter to the church at Rome.', 'Romans 16:1-2', false),

  -- Priscilla, Aquila, Apollos
  ('priscilla', 'corinth',   null, 'co-worker', 'Met Paul here as fellow tentmakers and worked beside him.', 'Acts 18:1-3', false),
  ('priscilla', 'ephesus',   'household-pa-ephesus', 'host-of-house-church', 'Hosted a church and helped instruct Apollos more accurately.', 'Acts 18:18-26; 1 Corinthians 16:19', false),
  ('priscilla', 'rome',      'household-pa-rome', 'host-of-house-church', 'Hosted a church in her home and risked her life for Paul.', 'Romans 16:3-5', true),
  ('aquila',    'pontus',    null, 'member',    'A Jew, a native of Pontus, before he settled in the empire''s cities.', 'Acts 18:2', false),
  ('aquila',    'corinth',   null, 'co-worker', 'Met Paul here as a fellow tentmaker after leaving Rome.', 'Acts 18:1-3', false),
  ('aquila',    'ephesus',   'household-pa-ephesus', 'host-of-house-church', 'Hosted a church and helped instruct Apollos more accurately.', 'Acts 18:18-26; 1 Corinthians 16:19', false),
  ('aquila',    'rome',      'household-pa-rome', 'host-of-house-church', 'Hosted a church in his home and risked his life for Paul.', 'Romans 16:3-5', true),
  ('apollos',   'alexandria',null, 'member',    'An eloquent Jew, mighty in the Scriptures, from the city of Alexandria.', 'Acts 18:24-25', true),
  ('apollos',   'ephesus',   null, 'teacher',   'Taught the way of God more accurately by Priscilla and Aquila.', 'Acts 18:24-28', false),
  ('apollos',   'corinth',   null, 'teacher',   'Watered in Achaia what Paul had planted, refuting the Jews publicly.', 'Acts 18:27-28; 1 Corinthians 3:5-6', false),
  ('apollos',   'crete',     null, 'co-worker', 'To be helped on his way by the Cretan churches with Zenas.', 'Titus 3:13', false),

  -- Ephesus
  ('tychicus',         'ephesus',  null, 'letter-carrier', 'Carried Paul''s letter and news to the church at Ephesus.', 'Ephesians 6:21-22; Acts 20:4', true),
  ('tychicus',         'colossae', null, 'letter-carrier', 'Carried the letter to the Colossians and told them all the news.', 'Colossians 4:7-9', false),
  ('tychicus',         'crete',    null, 'letter-carrier', 'Considered by Paul as a replacement to send to Titus in Crete.', 'Titus 3:12', false),
  ('trophimus',        'ephesus',  null, 'member',    'An Ephesian companion of Paul on the third journey.', 'Acts 20:4', true),
  ('trophimus',        'jerusalem',null, 'mentioned', 'Wrongly assumed to have entered the temple, sparking the riot.', 'Acts 21:27-29', false),
  ('trophimus',        'miletus',  null, 'mentioned', 'Left behind ill at Miletus by Paul.', '2 Timothy 4:20', false),
  ('onesiphorus',      'ephesus',  'household-onesiphorus', 'host-of-house-church', 'Often refreshed Paul; his household greeted in Paul''s last letter.', '2 Timothy 1:16-18; 2 Timothy 4:19', true),
  ('onesiphorus',      'rome',     null, 'co-worker', 'Searched hard for Paul in Rome and was not ashamed of his chains.', '2 Timothy 1:16-17', false),
  ('hymenaeus',        'ephesus',  null, 'opponent',  'A teacher whose faith was shipwrecked; handed over by Paul to be disciplined.', '1 Timothy 1:20; 2 Timothy 2:17-18', true),
  ('alexander-ephesus','ephesus',  null, 'opponent',  'A coppersmith who did Paul great harm and opposed his message.', '2 Timothy 4:14-15', true),
  ('demetrius-ephesus','ephesus',  null, 'opponent',  'A silversmith who stirred the city to riot against Paul.', 'Acts 19:24-29', true),
  ('sceva-sons',       'ephesus',  null, 'mentioned', 'Seven sons of a high priest, overpowered when they misused Jesus'' name.', 'Acts 19:13-16', true),
  ('epaenetus',        'ephesus',  null, 'convert',   'The first convert to Christ in the province of Asia.', 'Romans 16:5', true),
  ('epaenetus',        'rome',     null, 'greeted',   'An Asian believer greeted with affection by Paul in Rome.', 'Romans 16:5', false),

  -- Troas
  ('eutychus', 'troas', null, 'member', 'A young man restored to life after falling from a third-story window.', 'Acts 20:7-12', true),
  ('carpus',   'troas', null, 'member', 'A believer with whom Paul left his cloak, scrolls, and parchments.', '2 Timothy 4:13', true),

  -- Colossae and the Lycus Valley
  ('philemon',  'colossae',  'household-philemon', 'host-of-house-church', 'A wealthy believer who hosted the church in his home.', 'Philemon 1:1-2', true),
  ('apphia',    'colossae',  'household-philemon', 'member',    'A believer at Colossae, addressed by Paul alongside Philemon.', 'Philemon 1:2', true),
  ('archippus', 'colossae',  'household-philemon', 'co-worker', 'Urged to complete the ministry he had received in the Lord.', 'Colossians 4:17; Philemon 1:2', true),
  ('onesimus',  'colossae',  'household-philemon', 'member',    'A runaway slave who became a faithful and beloved brother.', 'Philemon 1:10-16; Colossians 4:9', true),
  ('onesimus',  'rome',      null, 'co-worker', 'Came to faith through Paul in prison and served him there.', 'Philemon 1:10-13', false),
  ('epaphras',  'colossae',  null, 'founder',   'Brought the gospel to Colossae and labored in prayer for the church.', 'Colossians 1:7; Colossians 4:12-13', true),
  ('epaphras',  'laodicea',  null, 'founder',   'Worked hard for the believers of Laodicea.', 'Colossians 4:13', false),
  ('epaphras',  'hierapolis',null, 'founder',   'Worked hard for the believers of Hierapolis.', 'Colossians 4:13', false),
  ('epaphras',  'rome',      null, 'co-worker', 'Paul''s fellow prisoner who sent greetings to Colossae.', 'Philemon 1:23', false),
  ('nympha',    'laodicea',  'household-nympha', 'host-of-house-church', 'Hosted a church in her house in the region of Laodicea.', 'Colossians 4:15', true),

  -- Crete
  ('titus', 'crete',     null, 'overseer',       'Left in Crete to set the churches in order and appoint elders.', 'Titus 1:4-5', true),
  ('titus', 'corinth',   null, 'letter-carrier', 'Carried letters between Paul and Corinth and organized the collection.', '2 Corinthians 7:6-15; 2 Corinthians 8:6,16-23', false),
  ('titus', 'antioch',   null, 'co-worker',      'Accompanied Paul and Barnabas from Antioch to the Jerusalem council.', 'Galatians 2:1-3', false),
  ('titus', 'jerusalem', null, 'mentioned',      'Brought to the council as a Greek who was not compelled to be circumcised.', 'Galatians 2:1-3', false),
  ('zenas',   'crete', null, 'traveling-companion', 'A lawyer to be helped on his way by the Cretan churches.', 'Titus 3:13', true),
  ('artemas', 'crete', null, 'co-worker',           'Considered by Paul as a replacement to send to Titus.', 'Titus 3:12', true),

  -- Rome — the believers greeted in Romans 16
  ('mary-rome',            'rome', null, 'member',   'A worker in the Roman church who labored hard for the believers.', 'Romans 16:6', true),
  ('andronicus',           'rome', null, 'member',   'A kinsman and fellow prisoner of Paul, outstanding among the apostles.', 'Romans 16:7', true),
  ('junia',                'rome', null, 'member',   'A kinswoman and fellow prisoner of Paul, outstanding among the apostles.', 'Romans 16:7', true),
  ('ampliatus',            'rome', null, 'member',   'A beloved friend of Paul in the Roman church.', 'Romans 16:8', true),
  ('urbanus',              'rome', null, 'co-worker','A fellow worker of Paul in Christ, greeted in Rome.', 'Romans 16:9', true),
  ('stachys',              'rome', null, 'member',   'A beloved friend of Paul in the Roman church.', 'Romans 16:9', true),
  ('apelles',              'rome', null, 'member',   'A believer in Rome approved and tested in Christ.', 'Romans 16:10', true),
  ('aristobulus-household','rome', 'household-aristobulus', 'member', 'A household in Rome greeted by Paul.', 'Romans 16:10', true),
  ('herodion',             'rome', null, 'relative', 'A kinsman of Paul in the Roman church.', 'Romans 16:11', true),
  ('narcissus-household',  'rome', 'household-narcissus', 'member', 'Those of the household of Narcissus who were in the Lord.', 'Romans 16:11', true),
  ('tryphaena',            'rome', null, 'member',   'A woman who worked hard in the Lord, greeted in Rome.', 'Romans 16:12', true),
  ('tryphosa',             'rome', null, 'member',   'A woman who worked hard in the Lord, greeted in Rome.', 'Romans 16:12', true),
  ('persis',               'rome', null, 'member',   'A beloved woman who worked very hard in the Lord.', 'Romans 16:12', true),
  ('rufus',                'rome', null, 'member',   'A believer chosen in the Lord, greeted with his mother.', 'Romans 16:13', true),
  ('rufus-mother',         'rome', null, 'member',   'A woman who had been like a mother to Paul as well.', 'Romans 16:13', true),
  ('asyncritus',           'rome', null, 'member',   'A believer in Rome greeted by Paul.', 'Romans 16:14', true),
  ('phlegon',              'rome', null, 'member',   'A believer in Rome greeted by Paul.', 'Romans 16:14', true),
  ('hermes',               'rome', null, 'member',   'A believer in Rome greeted by Paul.', 'Romans 16:14', true),
  ('patrobas',             'rome', null, 'member',   'A believer in Rome greeted by Paul.', 'Romans 16:14', true),
  ('hermas',               'rome', null, 'member',   'A believer in Rome greeted by Paul.', 'Romans 16:14', true),
  ('philologus',           'rome', null, 'member',   'A believer in Rome greeted by Paul.', 'Romans 16:15', true),
  ('julia',                'rome', null, 'member',   'A believer in Rome greeted by Paul.', 'Romans 16:15', true),
  ('nereus',               'rome', null, 'member',   'A believer in Rome greeted by Paul.', 'Romans 16:15', true),
  ('nereus-sister',        'rome', null, 'member',   'A believer in Rome greeted alongside her brother.', 'Romans 16:15', true),
  ('olympas',              'rome', null, 'member',   'A believer in Rome greeted by Paul.', 'Romans 16:15', true),

  -- Rome — Paul''s imprisonment circle
  ('luke',        'rome',      null, 'co-worker', 'Paul''s faithful companion who alone remained with him at the end.', 'Colossians 4:14; 2 Timothy 4:11', true),
  ('luke',        'troas',     null, 'traveling-companion', 'Joined Paul''s company at Troas, beginning the first "we" account.', 'Acts 16:10-11', false),
  ('luke',        'philippi',  null, 'co-worker', 'Apparently remained at Philippi to nurture the new church.', 'Acts 16:12-17', false),
  ('luke',        'miletus',   null, 'traveling-companion', 'Sailed with Paul''s company along the coast of Asia.', 'Acts 20:13-15', false),
  ('luke',        'caesarea',  null, 'traveling-companion', 'Stayed near Paul through his imprisonment in Caesarea.', 'Acts 24:23-27', false),
  ('luke',        'jerusalem', null, 'traveling-companion', 'Accompanied Paul on his final journey up to Jerusalem.', 'Acts 21:15-18', false),
  ('jesus-justus','rome',      null, 'co-worker', 'A Jewish co-worker of Paul, a comfort to him in his imprisonment.', 'Colossians 4:11', true),
  ('pudens',      'rome',      null, 'member',    'A believer in Rome who sent greetings to Timothy through Paul.', '2 Timothy 4:21', true),
  ('linus',       'rome',      null, 'member',    'A believer in Rome who sent greetings to Timothy through Paul.', '2 Timothy 4:21', true),
  ('claudia',     'rome',      null, 'member',    'A believer in Rome who sent greetings to Timothy through Paul.', '2 Timothy 4:21', true),
  ('eubulus',     'rome',      null, 'member',    'A believer in Rome who sent greetings to Timothy through Paul.', '2 Timothy 4:21', true),
  ('crescens',    'rome',      null, 'co-worker', 'A co-worker with Paul in Rome before departing for Galatia.', '2 Timothy 4:10', true),
  ('crescens',    'galatia',   null, 'co-worker', 'Sent from Paul to the churches of Galatia.', '2 Timothy 4:10', false),
  ('gaius-derbe', 'derbe',     null, 'member',    'A believer from Derbe in the churches of Galatia.', 'Acts 20:4', true),
  ('gaius-derbe', 'troas',     null, 'traveling-companion', 'Traveled with Paul''s company and waited at Troas.', 'Acts 20:4-5', false),

  -- Revelation: Pergamum and Thyatira
  ('antipas',          'pergamum', null, 'member',   'The faithful witness of Pergamum, put to death where Satan dwells.', 'Revelation 2:13', true),
  ('jezebel-thyatira', 'thyatira', null, 'opponent', 'A self-styled prophetess who led believers at Thyatira astray.', 'Revelation 2:20-23', true),

  -- Theophilus
  ('theophilus', 'antioch', null, 'member', 'The honored reader to whom Luke addressed his Gospel and the Acts.', 'Luke 1:3; Acts 1:1', true);

-- ── Church-level scripture references ────────────────────────────────────────
-- Reference strings only; verse text is fetched at display time.
insert into public."FCC_ScriptureRefs" (reference, label, church_id) values
  ('Acts 2:1-47',      'The church is born at Pentecost',            'jerusalem'),
  ('Acts 15:1-35',     'The Jerusalem council',                     'jerusalem'),
  ('Acts 11:19-30',    'The gospel comes to Antioch',                'antioch'),
  ('Acts 13:1-3',      'Antioch sends out Barnabas and Saul',        'antioch'),
  ('Acts 9:1-25',      'Saul''s conversion and the Damascus disciples', 'damascus'),
  ('Acts 8:4-25',      'Philip preaches Christ in Samaria',          'samaria'),
  ('Acts 9:36-43',     'Peter raises Tabitha in Joppa',              'joppa'),
  ('Acts 9:32-35',     'Peter heals Aeneas at Lydda',                'lydda'),
  ('Acts 10:1-48',     'Cornelius and his household believe',        'caesarea'),
  ('Acts 21:7',        'Paul greets the believers at Ptolemais',     'ptolemais'),
  ('Acts 21:3-6',      'The disciples of Tyre pray with Paul',       'tyre'),
  ('Acts 27:3',        'Paul''s friends at Sidon care for him',      'sidon'),
  ('Acts 13:4-5',      'Paul and Barnabas preach in Salamis',        'salamis'),
  ('Acts 13:6-12',     'The proconsul of Paphos believes',           'paphos'),
  ('Acts 13:13-14',    'John Mark leaves at Perga',                  'perga'),
  ('Acts 13:14-52',    'Paul''s synagogue sermon at Pisidian Antioch','antioch-pisidia'),
  ('Acts 14:1-7',      'Many believe at Iconium',                    'iconium'),
  ('Acts 14:8-20',     'Paul is stoned at Lystra',                   'lystra'),
  ('Acts 14:20-21',    'Many disciples made at Derbe',               'derbe'),
  ('Galatians 1:1-9',  'A letter to the churches of Galatia',        'galatia'),
  ('Acts 19:1-41',     'Two years of ministry at Ephesus',           'ephesus'),
  ('Revelation 2:1-7', 'The risen Christ''s message to Ephesus',     'ephesus'),
  ('Acts 20:15-38',    'Paul''s farewell to the Ephesian elders',    'miletus'),
  ('Acts 20:5-12',     'Eutychus restored to life at Troas',         'troas'),
  ('Colossians 1:1-8', 'The gospel bears fruit in Colossae',         'colossae'),
  ('Colossians 4:13',  'Epaphras works hard for Hierapolis',         'hierapolis'),
  ('Revelation 3:14-22','The risen Christ''s message to Laodicea',   'laodicea'),
  ('Revelation 2:8-11','The risen Christ''s message to Smyrna',      'smyrna'),
  ('Revelation 2:12-17','The risen Christ''s message to Pergamum',   'pergamum'),
  ('Revelation 2:18-29','The risen Christ''s message to Thyatira',   'thyatira'),
  ('Revelation 3:1-6', 'The risen Christ''s message to Sardis',      'sardis'),
  ('Revelation 3:7-13','The risen Christ''s message to Philadelphia','philadelphia'),
  ('Acts 16:11-40',    'Lydia, the slave girl, and the jailer',      'philippi'),
  ('Acts 17:1-9',      'Paul reasons in the Thessalonian synagogue', 'thessalonica'),
  ('Acts 17:10-15',    'The noble-minded Bereans',                   'berea'),
  ('Acts 17:16-34',    'Paul addresses the Areopagus',               'athens'),
  ('Acts 18:1-17',     'Eighteen months in Corinth',                 'corinth'),
  ('Romans 16:1-16',   'Paul greets the church by name',             'rome'),
  ('Romans 16:1-2',    'Phoebe, deacon of the church at Cenchreae',  'cenchreae'),
  ('Titus 1:5',        'Titus appoints elders in every town',        'crete'),
  ('Acts 28:13-14',    'Believers welcome Paul at Puteoli',          'puteoli'),
  ('Acts 18:24-25',    'Apollos of Alexandria',                      'alexandria'),
  ('Acts 11:20',       'Men of Cyrene preach to the Greeks',         'cyrene'),
  ('1 Peter 1:1',      'Peter writes to the dispersion in Pontus',   'pontus'),
  ('1 Peter 1:1',      'Peter writes to the dispersion in Cappadocia','cappadocia'),
  ('1 Peter 1:1',      'Peter writes to the dispersion in Bithynia', 'bithynia');

commit;
