-- Biblical People expansion — comprehensive OT figures.
-- Organized by primary narrative age.
-- ON CONFLICT DO NOTHING to preserve any existing data.

begin;

insert into public."BP_People" (person_id, name, description, scripture_refs) values

  -- ── Creation & Primeval History ─────────────────────────────────────────
  ('eve',             'Eve',             'The first woman, created from Adam''s side. Mother of Cain, Abel, and Seth.',                   'Genesis 2-4'),
  ('cain',            'Cain',            'Firstborn son of Adam and Eve. Murdered his brother Abel and was cursed to wander.',             'Genesis 4'),
  ('abel',            'Abel',            'Second son of Adam. Offered an acceptable sacrifice to God and was killed by Cain.',             'Genesis 4'),
  ('seth',            'Seth',            'Third son of Adam and Eve, born after Abel''s death. Ancestor of Noah.',                        'Genesis 4:25-26, 5:3-8'),
  ('enoch',           'Enoch',           'Descendant of Seth who walked with God and was taken up without dying.',                         'Genesis 5:21-24'),
  ('methuselah',      'Methuselah',      'Son of Enoch. Longest-lived person in the Bible at 969 years.',                                 'Genesis 5:25-27'),
  ('lamech-cain',     'Lamech (descendant of Cain)', 'Descendant of Cain who boasted of killing a man. Husband of Adah and Zillah.',      'Genesis 4:18-24'),
  ('nimrod',          'Nimrod',          'Mighty hunter and ruler. Built Babel, Erech, Accad, and Nineveh.',                               'Genesis 10:8-12'),
  ('shem',            'Shem',            'Son of Noah. Ancestor of the Semitic peoples including Abraham.',                                'Genesis 5:32, 9:26-27, 10:21-31, 11:10-26'),
  ('ham',             'Ham',             'Son of Noah. Father of Canaan. His descendants include the Egyptians and Canaanites.',           'Genesis 5:32, 9:20-27, 10:6-20'),
  ('japheth',         'Japheth',         'Son of Noah. His descendants spread into the coastlands.',                                       'Genesis 5:32, 9:27, 10:2-5'),

  -- ── Patriarchs ──────────────────────────────────────────────────────────
  ('lot',             'Lot',             'Abraham''s nephew who settled in Sodom. Rescued by angels before its destruction.',              'Genesis 11:27, 13-14, 19'),
  ('hagar',           'Hagar',           'Sarah''s Egyptian servant. Mother of Ishmael. God met her in the wilderness.',                   'Genesis 16, 21:8-21'),
  ('ishmael',         'Ishmael',         'Son of Abraham and Hagar. Father of twelve princes. God promised to make him a great nation.',   'Genesis 16, 17:20, 21:8-21, 25:12-18'),
  ('melchizedek',     'Melchizedek',     'King of Salem and priest of God Most High. Blessed Abraham and received his tithe.',             'Genesis 14:18-20'),
  ('rebekah',         'Rebekah',         'Wife of Isaac, mother of Jacob and Esau. Helped Jacob receive the blessing.',                    'Genesis 24-28'),
  ('esau',            'Esau',            'Elder twin of Isaac and Rebekah. Sold his birthright. Father of the Edomites.',                  'Genesis 25-36'),
  ('laban',           'Laban',           'Rebekah''s brother. Jacob worked for him 20 years to marry his daughters.',                     'Genesis 24, 29-31'),
  ('rachel',          'Rachel',          'Jacob''s beloved wife. Mother of Joseph and Benjamin. Died giving birth to Benjamin.',           'Genesis 29-35, 48:7'),
  ('leah',            'Leah',            'Jacob''s first wife and mother of six sons and a daughter. Buried in Machpelah.',                'Genesis 29-35, 49:31'),
  ('dinah',           'Dinah',           'Daughter of Jacob and Leah. Her assault at Shechem led to her brothers'' violent revenge.',      'Genesis 34'),
  ('reuben',          'Reuben',          'Firstborn son of Jacob. Lost his birthright. Tried to save Joseph from his brothers.',           'Genesis 29:32, 35:22, 37:21-22, 42:37'),
  ('judah',           'Judah',           'Fourth son of Jacob. Ancestor of David and the royal line. Pledged himself for Benjamin.',       'Genesis 29:35, 38, 43:3-10, 44:18-34'),
  ('tamar-genesis',   'Tamar (Genesis)', 'Daughter-in-law of Judah who disguised herself to secure offspring. Ancestor of David.',         'Genesis 38'),
  ('potiphar',        'Potiphar',        'Egyptian officer who bought Joseph as a slave. His wife falsely accused Joseph.',                'Genesis 37:36, 39'),
  ('benjamin',        'Benjamin',        'Youngest son of Jacob and Rachel. His birth caused Rachel''s death.',                            'Genesis 35:16-20, 42-45'),

  -- ── Exodus & Wilderness ─────────────────────────────────────────────────
  ('aaron',           'Aaron',           'Brother of Moses and first high priest of Israel. Spokesman before Pharaoh.',                    'Exodus 4-40, Leviticus, Numbers'),
  ('miriam',          'Miriam',          'Sister of Moses and Aaron. Prophetess who led worship after the Red Sea crossing.',              'Exodus 2:1-10, 15:20-21; Numbers 12, 20:1'),
  ('pharaoh-of-exodus','Pharaoh of the Exodus', 'The Egyptian king who refused to let Israel go despite ten devastating plagues.',          'Exodus 1-15'),
  ('jethro',          'Jethro',          'Moses'' father-in-law, priest of Midian. Advised Moses to delegate leadership.',                'Exodus 2:16-22, 3:1, 18:1-27'),
  ('zipporah',        'Zipporah',        'Wife of Moses and daughter of Jethro the Midianite priest.',                                     'Exodus 2:21-22, 4:24-26, 18:2-6'),
  ('caleb',           'Caleb',           'One of only two spies who gave a good report. Faithful warrior who received Hebron.',            'Numbers 13-14, Joshua 14:6-15, 15:13-19'),
  ('korah',           'Korah',           'Levite who led a rebellion against Moses and Aaron. The earth swallowed him alive.',             'Numbers 16'),
  ('balaam',          'Balaam',          'Mesopotamian prophet hired to curse Israel. His donkey spoke. He blessed Israel instead.',        'Numbers 22-24, 31:16'),
  ('balak',           'Balak',           'King of Moab who hired Balaam to curse Israel.',                                                 'Numbers 22-24'),
  ('phinehas-eleazar','Phinehas (son of Eleazar)', 'Zealous priest who turned away God''s wrath by executing an Israelite and a Midianite.', 'Numbers 25:7-13, Joshua 22:13-32'),
  ('eleazar',         'Eleazar',         'Son of Aaron who became high priest after his father''s death on Mount Hor.',                    'Numbers 20:25-28, Joshua 14:1, 24:33'),
  ('nadab',           'Nadab (son of Aaron)', 'Son of Aaron who died offering unauthorized fire before the Lord.',                         'Leviticus 10:1-3'),
  ('abihu',           'Abihu',           'Son of Aaron who died alongside Nadab for offering unauthorized fire.',                          'Leviticus 10:1-3'),
  ('bezalel',         'Bezalel',         'Spirit-filled craftsman who built the Tabernacle furnishings.',                                  'Exodus 31:1-11, 35:30-36:2'),
  ('dathan',          'Dathan',          'Reubenite who joined Korah''s rebellion against Moses.',                                         'Numbers 16'),
  ('abiram',          'Abiram',          'Reubenite who rebelled with Korah and Dathan. Swallowed by the earth.',                          'Numbers 16'),
  ('og',              'Og',              'Giant king of Bashan defeated by Israel east of the Jordan.',                                    'Numbers 21:33-35, Deuteronomy 3:1-11'),
  ('sihon',           'Sihon',           'Amorite king of Heshbon defeated by Israel before crossing the Jordan.',                         'Numbers 21:21-32, Deuteronomy 2:26-37'),

  -- ── Conquest & Judges ───────────────────────────────────────────────────
  ('rahab',           'Rahab',           'Prostitute of Jericho who hid the Israelite spies. Saved by faith. Ancestor of David and Jesus.', 'Joshua 2, 6:17-25'),
  ('achan',           'Achan',           'Israelite who stole from the devoted things at Jericho, causing Israel''s defeat at Ai.',        'Joshua 7'),
  ('othniel',         'Othniel',         'First judge of Israel. Nephew of Caleb. Delivered Israel from Cushan-Rishathaim.',               'Judges 3:7-11'),
  ('ehud',            'Ehud',            'Left-handed judge who assassinated Eglon king of Moab with a hidden dagger.',                    'Judges 3:12-30'),
  ('shamgar',         'Shamgar',         'Judge who killed 600 Philistines with an ox goad.',                                              'Judges 3:31, 5:6'),
  ('barak',           'Barak',           'Military commander who defeated Sisera''s army with Deborah''s encouragement.',                  'Judges 4-5'),
  ('sisera',          'Sisera',          'Canaanite commander whose army was routed by Barak. Killed by Jael with a tent peg.',            'Judges 4-5'),
  ('jael',            'Jael',            'Wife of Heber the Kenite. Killed Sisera by driving a tent peg through his temple.',              'Judges 4:17-22, 5:24-27'),
  ('gideon',          'Gideon',          'Judge who defeated the Midianites with 300 men using torches and trumpets.',                     'Judges 6-8'),
  ('abimelech',       'Abimelech',       'Son of Gideon who murdered his brothers and made himself king. Killed by a millstone.',          'Judges 9'),
  ('jephthah',        'Jephthah',        'Judge from Gilead who made a rash vow. Defeated the Ammonites.',                                'Judges 11-12'),
  ('samson',          'Samson',          'Judge with supernatural strength from God. Fought the Philistines. Betrayed by Delilah.',        'Judges 13-16'),
  ('delilah',         'Delilah',         'Woman who seduced Samson into revealing the secret of his strength.',                            'Judges 16:4-22'),
  ('manoah',          'Manoah',          'Father of Samson. The angel of the Lord appeared to him and his wife.',                           'Judges 13'),
  ('ruth',            'Ruth',            'Moabite woman who loyally followed her mother-in-law Naomi. Great-grandmother of David.',        'Ruth'),
  ('boaz',            'Boaz',            'Wealthy landowner of Bethlehem who redeemed Ruth as kinsman-redeemer.',                           'Ruth 2-4'),
  ('naomi',           'Naomi',           'Israelite woman who returned from Moab with her daughter-in-law Ruth.',                          'Ruth'),
  ('eli',             'Eli',             'High priest at Shiloh who raised Samuel. His wicked sons brought judgment on his house.',         '1 Samuel 1-4'),
  ('phinehas-eli',    'Phinehas (son of Eli)', 'Wicked son of Eli who abused the priesthood. Died when the Ark was captured.',             '1 Samuel 1-4'),
  ('hophni',          'Hophni',          'Wicked son of Eli who corrupted the worship at Shiloh. Killed in battle with the Philistines.',  '1 Samuel 1-4'),
  ('micah-judges',    'Micah (Judges)',  'Man from Ephraim who set up an idol and hired a Levite as his personal priest.',                 'Judges 17-18'),
  ('ibzan',           'Ibzan',           'Minor judge from Bethlehem who had thirty sons and thirty daughters.',                            'Judges 12:8-10'),
  ('jair',            'Jair',            'Minor judge from Gilead who had thirty sons who rode thirty donkeys.',                            'Judges 10:3-5'),
  ('tola',            'Tola',            'Minor judge from Issachar who judged Israel twenty-three years.',                                 'Judges 10:1-2'),

  -- ── United Monarchy ─────────────────────────────────────────────────────
  ('saul',            'Saul',            'First king of Israel, from the tribe of Benjamin. Tall and handsome but disobeyed God.',          '1 Samuel 9-31'),
  ('jonathan',        'Jonathan',        'Son of Saul and David''s closest friend. Died with his father at Gilboa.',                       '1 Samuel 13-14, 18-20, 23, 31; 2 Samuel 1'),
  ('michal',          'Michal',          'Daughter of Saul and wife of David. Helped David escape Saul but later despised him.',            '1 Samuel 18-19, 25:44; 2 Samuel 3:13-16, 6:16-23'),
  ('abigail',         'Abigail',         'Wise and beautiful wife of Nabal who prevented David from bloodshed. Later married David.',      '1 Samuel 25'),
  ('nabal',           'Nabal',           'Wealthy fool who insulted David. Died of shock when told how close he came to destruction.',      '1 Samuel 25'),
  ('abner',           'Abner',           'Commander of Saul''s army. Later supported David but was murdered by Joab.',                     '1 Samuel 14:50, 17:55; 2 Samuel 2-3'),
  ('ish-bosheth',     'Ish-Bosheth',     'Son of Saul briefly made king over Israel by Abner. Assassinated in his bed.',                   '2 Samuel 2-4'),
  ('joab',            'Joab',            'David''s nephew and commander of his army. Brilliant but ruthless general.',                      '2 Samuel 2-3, 10-12, 14, 18-20, 24; 1 Kings 1-2'),
  ('bathsheba',       'Bathsheba',       'Wife of Uriah, then of David. Mother of Solomon.',                                               '2 Samuel 11-12; 1 Kings 1-2'),
  ('uriah',           'Uriah',           'Hittite soldier, husband of Bathsheba. Faithfully loyal even when David tried to cover his sin.', '2 Samuel 11'),
  ('absalom',         'Absalom',         'David''s handsome son who rebelled and briefly seized the throne. Killed by Joab.',              '2 Samuel 13-19'),
  ('amnon',           'Amnon',           'David''s firstborn who assaulted his half-sister Tamar. Killed by Absalom.',                     '2 Samuel 13'),
  ('tamar-david',     'Tamar (daughter of David)', 'David''s daughter assaulted by her half-brother Amnon.',                                '2 Samuel 13'),
  ('nathan-prophet',  'Nathan',          'Prophet who confronted David about Bathsheba: "You are the man!" Named Solomon Jedidiah.',        '2 Samuel 7, 12; 1 Kings 1'),
  ('zadok',           'Zadok',           'Priest loyal to David. Anointed Solomon as king.',                                               '2 Samuel 15:24-36, 19:11; 1 Kings 1'),
  ('abishai',         'Abishai',         'David''s nephew, brother of Joab. Fierce warrior who wanted to kill Shimei.',                    '1 Samuel 26; 2 Samuel 2-3, 10, 16, 19-21, 23'),
  ('mephibosheth',    'Mephibosheth',    'Jonathan''s crippled son. David showed him kindness for Jonathan''s sake.',                       '2 Samuel 4:4, 9, 16:1-4, 19:24-30'),
  ('shimei',          'Shimei',          'Benjaminite who cursed David during Absalom''s revolt. Pardoned then later executed by Solomon.', '2 Samuel 16:5-14, 19:16-23; 1 Kings 2:36-46'),
  ('adonijah',        'Adonijah',        'David''s son who tried to seize the throne. Executed by Solomon.',                               '1 Kings 1-2'),
  ('hiram-tyre',      'Hiram of Tyre',   'King of Tyre who supplied cedar, gold, and craftsmen for Solomon''s Temple.',                    '2 Samuel 5:11; 1 Kings 5, 9:10-14, 10:22'),
  ('queen-of-sheba',  'Queen of Sheba',  'Ruler who traveled far to test Solomon''s wisdom and was overwhelmed.',                          '1 Kings 10:1-13'),
  ('rehoboam',        'Rehoboam',        'Solomon''s son whose harshness split the kingdom. First king of Judah.',                         '1 Kings 11:43-14:31'),
  ('jeroboam-i',      'Jeroboam I',      'First king of the northern kingdom. Set up golden calves at Dan and Bethel.',                    '1 Kings 11:26-14:20'),
  ('doeg',            'Doeg',            'Edomite servant of Saul who reported David''s visit to Nob and massacred the priests.',           '1 Samuel 21:7, 22:9-23'),
  ('hushai',          'Hushai',          'David''s friend who defeated Ahithophel''s counsel during Absalom''s revolt.',                   '2 Samuel 15:32-37, 16:16-17:16'),
  ('ahithophel',      'Ahithophel',      'David''s counselor who defected to Absalom. Hanged himself when his advice was rejected.',        '2 Samuel 15:12, 16:20-17:23'),

  -- ── Divided Monarchy ────────────────────────────────────────────────────
  ('ahab',            'Ahab',            'King of Israel who married Jezebel and promoted Baal worship. Died in battle at Ramoth-Gilead.', '1 Kings 16:29-22:40'),
  ('jezebel',         'Jezebel',         'Phoenician princess, wife of Ahab. Championed Baal worship and killed prophets of the Lord.',    '1 Kings 16:31, 18-19, 21; 2 Kings 9:30-37'),
  ('naboth',          'Naboth',          'Owner of a vineyard in Jezreel. Murdered by Jezebel''s scheme so Ahab could take his land.',     '1 Kings 21'),
  ('omri',            'Omri',            'King of Israel who built Samaria as the new capital. Powerful but wicked ruler.',                 '1 Kings 16:16-28'),
  ('jehu',            'Jehu',            'Commander anointed king by Elisha''s servant. Destroyed the house of Ahab and Baal worship.',     '2 Kings 9-10'),
  ('athaliah',        'Athaliah',        'Daughter of Ahab who seized Judah''s throne and tried to destroy the royal line.',               '2 Kings 11; 2 Chronicles 22:10-23:21'),
  ('joash-judah',     'Joash (King of Judah)', 'Boy king hidden from Athaliah. Repaired the Temple but later turned from God.',            '2 Kings 11-12; 2 Chronicles 22:11-24:27'),
  ('micaiah',         'Micaiah',         'True prophet who predicted Ahab''s death at Ramoth-Gilead when 400 false prophets promised victory.', '1 Kings 22:1-28'),
  ('obadiah-steward', 'Obadiah (Ahab''s steward)', 'Godly official in Ahab''s court who hid 100 prophets from Jezebel.',                  '1 Kings 18:1-16'),
  ('naaman',          'Naaman',          'Syrian army commander healed of leprosy by washing in the Jordan at Elisha''s command.',          '2 Kings 5'),
  ('gehazi',          'Gehazi',          'Elisha''s servant who greedily took gifts from Naaman and was struck with leprosy.',              '2 Kings 4-5, 8:1-6'),
  ('amos',            'Amos',            'Shepherd from Tekoa called to prophesy against the northern kingdom''s injustice.',               'Amos'),
  ('hosea',           'Hosea',           'Prophet commanded to marry an unfaithful wife as a picture of God''s love for wayward Israel.',   'Hosea'),
  ('jeroboam-ii',     'Jeroboam II',     'Powerful king of Israel who expanded its territory but allowed injustice and idolatry.',          '2 Kings 14:23-29'),
  ('uzziah',          'Uzziah (Azariah)', 'Long-reigning king of Judah. Struck with leprosy for entering the Temple to burn incense.',     '2 Kings 15:1-7; 2 Chronicles 26'),
  ('ahaz',            'Ahaz',            'King of Judah who refused Isaiah''s sign and appealed to Assyria, introducing pagan altars.',     '2 Kings 16; Isaiah 7'),
  ('hezekiah',        'Hezekiah',        'Righteous king of Judah who trusted God during Sennacherib''s siege. Extended life by 15 years.', '2 Kings 18-20; Isaiah 36-39'),
  ('sennacherib',     'Sennacherib',     'Assyrian king who besieged Jerusalem but whose army was destroyed by the angel of the Lord.',    '2 Kings 18:13-19:37; Isaiah 36-37'),
  ('jonah',           'Jonah',           'Prophet who fled from God''s command to preach to Nineveh. Swallowed by a great fish.',           'Jonah; 2 Kings 14:25'),
  ('joel',            'Joel',            'Prophet who called Judah to repentance using a devastating locust plague as his backdrop.',        'Joel'),
  ('micah-prophet',   'Micah',           'Prophet from Moresheth who prophesied the fall of Samaria and the birth of the Messiah in Bethlehem.', 'Micah'),
  ('ben-hadad',       'Ben-Hadad',       'Title for kings of Aram-Damascus. Multiple Ben-Hadads fought against Israel.',                   '1 Kings 15:18-20, 20; 2 Kings 6:24, 8:7-15, 13:3-25'),
  ('elah',            'Elah (king of Israel)', 'Son of Baasha, king of Israel. Assassinated by Zimri while drinking.',                     '1 Kings 16:6-14'),
  ('zimri',           'Zimri',           'Commander who assassinated Elah and reigned seven days before burning the palace on himself.',     '1 Kings 16:9-20'),
  ('baasha',          'Baasha',          'King of Israel who destroyed the house of Jeroboam but continued in sin.',                        '1 Kings 15:16-16:7'),
  ('asa',             'Asa',             'King of Judah who removed idols and relied on God early in his reign but later trusted Aram.',    '1 Kings 15:9-24; 2 Chronicles 14-16'),
  ('jehoshaphat',     'Jehoshaphat',     'Godly king of Judah who allied too closely with Ahab. Appointed judges and sought the Lord.',     '1 Kings 22; 2 Chronicles 17-20'),
  ('jehoram-israel',  'Jehoram (King of Israel)', 'Son of Ahab who continued Baal worship but sought Elisha''s help against Moab.',        '2 Kings 1:17, 3:1-27, 6:8-7:20'),
  ('jehoram-judah',   'Jehoram (King of Judah)', 'Married Athaliah and led Judah into idolatry. Edom and Libnah revolted.',                '2 Kings 8:16-24; 2 Chronicles 21'),
  ('hazael',          'Hazael',          'King of Aram-Damascus who oppressed Israel. Elisha wept foreseeing his cruelty.',                '2 Kings 8:7-15, 10:32-33, 12:17-18, 13:3-7, 22'),
  ('shalmaneser',     'Shalmaneser V',   'Assyrian king who besieged Samaria for three years, ending the northern kingdom.',               '2 Kings 17:3-6, 18:9-10'),
  ('tiglath-pileser', 'Tiglath-Pileser III', 'Assyrian king (Pul) who deported northern Israelite tribes. Ahaz appealed to him.',          '2 Kings 15:19-20, 29, 16:7-10; 1 Chronicles 5:26'),

  -- ── Judah Alone & Exile ─────────────────────────────────────────────────
  ('josiah',          'Josiah',          'Righteous king who found the Book of the Law and led a great reform. Killed at Megiddo.',         '2 Kings 22-23; 2 Chronicles 34-35'),
  ('manasseh',        'Manasseh',        'Wicked king of Judah who filled Jerusalem with blood. Later repented in Babylonian captivity.',   '2 Kings 21:1-18; 2 Chronicles 33:1-20'),
  ('zedekiah',        'Zedekiah',        'Last king of Judah. Rebelled against Babylon, watched his sons killed, then was blinded.',        '2 Kings 24:17-25:7; Jeremiah 37-39, 52'),
  ('jehoiakim',       'Jehoiakim',       'King of Judah who burned Jeremiah''s scroll. Vassal of Babylon who rebelled.',                   '2 Kings 23:34-24:7; Jeremiah 22:18-19, 26, 36'),
  ('jehoiachin',      'Jehoiachin',      'King of Judah exiled to Babylon at age 18. Later released from prison by Evil-Merodach.',         '2 Kings 24:8-17, 25:27-30; Jeremiah 52:31-34'),
  ('nebuchadnezzar',  'Nebuchadnezzar',  'King of Babylon who destroyed Jerusalem and the Temple. Had visions interpreted by Daniel.',      'Daniel 1-4; 2 Kings 24-25; Jeremiah 39, 52'),
  ('baruch',          'Baruch',          'Jeremiah''s faithful scribe who wrote and read aloud the prophet''s words.',                      'Jeremiah 32, 36, 43, 45'),
  ('ebed-melech',     'Ebed-Melech',     'Ethiopian official who rescued Jeremiah from a cistern. Promised protection during the fall.',     'Jeremiah 38:7-13, 39:15-18'),
  ('gedaliah',        'Gedaliah',        'Governor appointed by Babylon over Judah''s remnant. Assassinated by Ishmael.',                  'Jeremiah 40-41; 2 Kings 25:22-26'),
  ('shadrach',        'Shadrach (Hananiah)', 'One of Daniel''s three friends who refused to bow to Nebuchadnezzar''s image.',               'Daniel 1, 3'),
  ('meshach',         'Meshach (Mishael)', 'One of Daniel''s three friends thrown into the fiery furnace.',                                 'Daniel 1, 3'),
  ('abednego',        'Abednego (Azariah)', 'One of Daniel''s three friends who survived the fiery furnace unharmed.',                      'Daniel 1, 3'),
  ('belshazzar',      'Belshazzar',      'Last ruler of Babylon who saw the writing on the wall. Killed the night Babylon fell.',           'Daniel 5'),
  ('habakkuk',        'Habakkuk',        'Prophet who questioned God''s justice and received a vision of the righteous living by faith.',    'Habakkuk'),
  ('zephaniah-prophet','Zephaniah',      'Prophet during Josiah''s reign who warned of the Day of the Lord.',                               'Zephaniah'),
  ('nahum',           'Nahum',           'Prophet who proclaimed God''s judgment on Nineveh for its cruelty.',                              'Nahum'),
  ('obadiah-prophet', 'Obadiah',         'Prophet who proclaimed judgment against Edom for its betrayal of Judah.',                         'Obadiah'),
  ('huldah',          'Huldah',          'Prophetess consulted when the Book of the Law was found. Confirmed its message of judgment.',     '2 Kings 22:14-20; 2 Chronicles 34:22-28'),
  ('pharaoh-neco',    'Pharaoh Neco',    'Egyptian pharaoh who killed Josiah at Megiddo and installed Jehoiakim as vassal king.',           '2 Kings 23:29-35; 2 Chronicles 35:20-36:4'),
  ('ishmael-nethaniah','Ishmael son of Nethaniah', 'Royal descendant who assassinated Gedaliah, the governor appointed by Babylon.',        'Jeremiah 40:13-41:18; 2 Kings 25:25'),
  ('evil-merodach',   'Evil-Merodach',   'Babylonian king who released Jehoiachin from prison and treated him kindly.',                     '2 Kings 25:27-30; Jeremiah 52:31-34'),
  ('nebuzaradan',     'Nebuzaradan',     'Captain of Nebuchadnezzar''s guard who oversaw the destruction of Jerusalem and the deportation.', '2 Kings 25:8-21; Jeremiah 39:9-14, 40:1-6, 52:12-27'),

  -- ── Return & Restoration ────────────────────────────────────────────────
  ('zerubbabel',      'Zerubbabel',      'Descendant of David who led the first return from exile and oversaw rebuilding the Temple.',      'Ezra 1-6; Haggai; Zechariah 4'),
  ('haggai',          'Haggai',          'Prophet who urged the returned exiles to finish rebuilding the Temple.',                          'Haggai; Ezra 5:1, 6:14'),
  ('zechariah-prophet','Zechariah (prophet)', 'Post-exilic prophet with visions of the messianic age. Urged completion of the Temple.',     'Zechariah; Ezra 5:1, 6:14'),
  ('malachi',         'Malachi',         'Last OT prophet who rebuked the people for corrupt worship and promised Elijah''s return.',        'Malachi'),
  ('cyrus',           'Cyrus the Great', 'Persian king who conquered Babylon and decreed that the Jewish exiles could return home.',         'Ezra 1:1-4; Isaiah 44:28-45:7; Daniel 6:28, 10:1'),
  ('darius-i',        'Darius I',        'Persian king who confirmed Cyrus''s decree and supported the Temple''s completion.',              'Ezra 5-6; Haggai 1:1; Zechariah 1:1'),
  ('artaxerxes',      'Artaxerxes',      'Persian king who authorized Ezra''s return and Nehemiah''s mission to rebuild Jerusalem''s walls.', 'Ezra 7; Nehemiah 1-2, 13:6'),
  ('sanballat',       'Sanballat',       'Governor of Samaria who opposed Nehemiah''s rebuilding of Jerusalem''s walls.',                   'Nehemiah 2:10, 4:1-8, 6:1-14, 13:28'),
  ('tobiah',          'Tobiah',          'Ammonite official who mocked and conspired against Nehemiah''s wall-building.',                   'Nehemiah 2:10, 4:3, 6:1-19, 13:4-9'),
  ('geshem',          'Geshem',          'Arab leader who joined Sanballat and Tobiah in opposing Nehemiah.',                                'Nehemiah 2:19, 6:1-6'),
  ('esther',          'Esther',          'Jewish queen of Persia who risked her life to save her people from Haman''s plot.',                'Esther'),
  ('mordecai',        'Mordecai',        'Esther''s cousin who uncovered an assassination plot and opposed Haman.',                         'Esther'),
  ('haman',           'Haman',           'Persian official who plotted to destroy all Jews in the empire. Hanged on his own gallows.',       'Esther 3-7'),
  ('xerxes',          'Xerxes (Ahasuerus)', 'Persian king who made Esther queen and authorized the Jews to defend themselves.',             'Esther'),
  ('jeshua-priest',   'Jeshua (high priest)', 'High priest who returned with Zerubbabel and helped rebuild the altar and Temple.',          'Ezra 2:2, 3:2-9, 5:2; Haggai 1:1; Zechariah 3'),
  ('sheshbazzar',     'Sheshbazzar',     'Prince of Judah who led the first group of exiles back and laid the Temple foundation.',          'Ezra 1:8-11, 5:14-16'),
  ('eliashib',        'Eliashib',        'High priest during Nehemiah''s time who built the Sheep Gate but compromised with Tobiah.',        'Nehemiah 3:1, 13:4-9, 28')

on conflict (person_id) do nothing;

commit;
