-- Seed AK_Events — key events in African kingdoms history
insert into public."AK_Events" (event_id, name, event_year, event_type, kingdom_id, place_id, description) values
  ('kush-conquers-egypt', 'Kush conquers Egypt (25th Dynasty)', -744, 'conquest', 'kush', 'napata', 'Piye conquers Egypt, founding the 25th Dynasty.'),
  ('meroe-capital', 'Capital moves to Meroë', -590, 'founding', 'kush', 'meroe', 'The Kushite capital shifts south to Meroë, launching an era of pyramid building and iron production.'),
  ('carthage-founded', 'Founding of Carthage', -814, 'founding', 'carthage', 'carthage-city', 'According to tradition, Queen Dido founds Carthage as a Phoenician colony.'),
  ('battle-cannae', 'Battle of Cannae', -216, 'battle', 'carthage', null, 'Hannibal''s greatest victory — a double envelopment that destroyed a Roman army of 80,000.'),
  ('fall-carthage', 'Fall of Carthage', -146, 'decline', 'carthage', 'carthage-city', 'Rome destroys Carthage at the end of the Third Punic War.'),
  ('nok-ironworking', 'Nok iron smelting begins', -500, 'cultural', 'nok', 'nok-center', 'Earliest evidence of iron smelting in West Africa.'),
  ('aksum-christianity', 'Aksum adopts Christianity', 340, 'religious', 'aksum', 'aksum-city', 'King Ezana converts to Christianity, making Aksum one of the first Christian states.'),
  ('aksum-conquers-meroe', 'Aksum conquers Meroë', 350, 'conquest', 'aksum', 'meroe', 'Ezana campaigns against Kush, marking the end of Meroitic civilization.'),
  ('aksum-yemen', 'Aksumite invasion of Yemen', 525, 'conquest', 'aksum', null, 'Kaleb invades the Himyarite Kingdom to avenge the persecution of Christians.'),
  ('ghana-peak', 'Ghana Empire at its peak', 1050, 'cultural', 'ghana', 'koumbi-saleh', 'Al-Bakri describes Ghana''s wealth and power.'),
  ('almoravid-ghana', 'Almoravid attacks on Ghana', 1076, 'battle', 'ghana', 'koumbi-saleh', 'Almoravid incursions weaken the Ghana Empire.'),
  ('fatimid-cairo', 'Founding of Cairo', 969, 'founding', 'fatimid', 'cairo', 'The Fatimid general Jawhar founds al-Qahira (Cairo) as the new caliphal capital.'),
  ('al-azhar-founded', 'Al-Azhar University founded', 970, 'cultural', 'fatimid', 'cairo', 'Al-Azhar Mosque and University established, becoming the premier center of Islamic learning.'),
  ('almoravid-marrakech', 'Founding of Marrakech', 1070, 'founding', 'almoravid', 'marrakech', 'Almoravid emir founds Marrakech as the imperial capital.'),
  ('kilwa-gold-trade', 'Kilwa controls gold trade', 1200, 'trade', 'kilwa', 'kilwa-kisiwani', 'Kilwa seizes Sofala and gains control of the Zimbabwean gold trade.'),
  ('battle-kirina', 'Battle of Kirina', 1235, 'battle', 'mali', 'niani', 'Sundiata Keita defeats Sumanguru Kanté, founding the Mali Empire.'),
  ('manden-charter', 'Manden Charter (Kouroukan Fouga)', 1236, 'cultural', 'mali', 'niani', 'One of the earliest declarations of human rights, abolishing slavery.'),
  ('sankore-university', 'University of Sankore flourishes', 1300, 'cultural', 'mali', 'timbuktu', 'Sankore in Timbuktu becomes a major center of learning.'),
  ('mansa-musa-hajj', 'Mansa Musa''s pilgrimage to Mecca', 1324, 'trade', 'mali', 'cairo', 'Mansa Musa''s lavish hajj crashes the Egyptian gold market for a decade.'),
  ('ibn-battuta-mali', 'Ibn Battuta visits Mali', 1352, 'cultural', 'mali', 'niani', 'Ibn Battuta provides detailed accounts of Mali''s government and society.'),
  ('ethiopia-solomonic', 'Solomonic dynasty established', 1270, 'founding', 'ethiopia', null, 'Yekuno Amlak overthrows the Zagwe dynasty and founds the Solomonic dynasty.'),
  ('lalibela-churches', 'Rock-hewn churches of Lalibela', 1200, 'religious', 'ethiopia', 'lalibela', 'King Lalibela commissions eleven monolithic rock-hewn churches.'),
  ('great-zimbabwe-peak', 'Great Zimbabwe at its peak', 1300, 'cultural', 'great-zimbabwe', 'great-zimbabwe', 'Great Zimbabwe reaches its height with 18,000 inhabitants.'),
  ('songhai-timbuktu', 'Songhai conquers Timbuktu', 1468, 'conquest', 'songhai', 'timbuktu', 'Sunni Ali captures Timbuktu from the Tuareg.'),
  ('songhai-djenne', 'Songhai conquers Djenné', 1473, 'conquest', 'songhai', 'djenne', 'After a long siege, Sunni Ali captures Djenné.'),
  ('askia-pilgrimage', 'Askia Muhammad''s pilgrimage', 1496, 'religious', 'songhai', null, 'Askia Muhammad is appointed Caliph of the Western Sudan.'),
  ('battle-tondibi', 'Battle of Tondibi — Fall of Songhai', 1591, 'battle', 'songhai', 'gao', 'A Moroccan army with firearms defeats the Songhai Empire.'),
  ('benin-walls', 'Benin City walls constructed', 1450, 'cultural', 'benin', 'benin-city', 'Oba Ewuare fortifies Benin City with massive earthwork walls.'),
  ('benin-portuguese', 'Portuguese reach Benin', 1485, 'trade', 'benin', 'benin-city', 'Portuguese traders arrive at Benin, beginning trade relations.'),
  ('kongo-christianity', 'Kingdom of Kongo converts to Christianity', 1491, 'religious', 'kongo', 'mbanza-kongo', 'Kongo king is baptized as João I.'),
  ('afonso-letters', 'Afonso I protests slave trade', 1526, 'trade', 'kongo', 'mbanza-kongo', 'King Afonso I writes letters protesting the slave trade.'),
  ('battle-mbwila', 'Battle of Mbwila', 1665, 'battle', 'kongo', null, 'Portuguese defeat the Kongo army, beginning fragmentation.'),
  ('golden-stool', 'Legend of the Golden Stool', 1701, 'founding', 'ashanti', 'kumasi', 'The Golden Stool descends from the sky, unifying the Ashanti.'),
  ('dahomey-coast', 'Dahomey conquers Whydah', 1727, 'conquest', 'dahomey', null, 'King Agaja conquers Whydah, gaining direct Atlantic trade access.'),
  ('gondar-founded', 'Gondar established as capital', 1636, 'founding', 'ethiopia', 'gondar', 'Emperor Fasilides establishes Gondar as the permanent capital.'),
  ('mutapa-portuguese', 'Portuguese contact with Mutapa', 1505, 'trade', 'mutapa', 'sofala', 'Portuguese establish contact seeking gold trade control.'),
  ('rozwi-expel-portuguese', 'Rozwi expel the Portuguese', 1693, 'battle', 'rozwi', null, 'Changamire Dombo defeats the Portuguese.'),
  ('kanem-bornu-firearms', 'Kanem-Bornu modernizes military', 1575, 'cultural', 'kanem-bornu', 'birni-gazargamo', 'Mai Idris Alooma introduces firearms from the Ottoman Empire.')
on conflict (event_id) do nothing;
