-- Events expansion — comprehensive OT events by narrative age.
-- event_type must be one of: event, miracle, battle, covenant, prophecy, judgment
-- sort_within_age orders events chronologically within each age.
-- Existing events' sort values are preserved; new events fill gaps or extend.

begin;

insert into public."BP_Events" (event_id, name, narrative_age_id, place_id, description, event_type, scripture_ref, sort_within_age) values

  -- ── Creation & Primeval History ─────────────────────────────────────────
  ('creation',              'Creation',                           'age-creation', 'garden-of-eden', 'God creates the heavens, the earth, and all living things in six days.',                            'event',     'Genesis 1:1-2:3',       1),
  ('the-fall',              'The Fall',                           'age-creation', 'garden-of-eden', 'Adam and Eve disobey God by eating the forbidden fruit. Sin and death enter the world.',            'judgment',  'Genesis 3',             2),
  ('cain-kills-abel',       'Cain Kills Abel',                    'age-creation', 'land-of-nod',    'Cain murders his brother Abel out of jealousy and is cursed to wander.',                            'judgment',  'Genesis 4:1-16',        4),
  ('the-flood',             'The Flood',                          'age-creation', 'mt-ararat',      'God sends a global flood to judge wickedness. Noah and his family are saved in the ark.',            'judgment',  'Genesis 6-9',           5),
  ('covenant-with-noah',    'Covenant with Noah',                 'age-creation', 'mt-ararat',      'God makes a covenant with Noah never to destroy the earth by flood again. The rainbow is the sign.', 'covenant',  'Genesis 9:1-17',        6),

  -- ── Patriarchs ──────────────────────────────────────────────────────────
  ('abram-leaves-ur',       'Abram Leaves Ur',                    'age-patriarchs', 'ur',           'God calls Abram to leave his homeland for a land He will show him.',                                'covenant',  'Genesis 11:31-12:1',    0),
  ('abraham-in-egypt',      'Abraham in Egypt',                   'age-patriarchs', 'egypt-goshen', 'Abraham goes to Egypt during a famine and passes Sarah off as his sister.',                         'event',     'Genesis 12:10-20',      3),
  ('covenant-of-pieces',    'Covenant of the Pieces',             'age-patriarchs', 'hebron',       'God makes a covenant with Abram, promising him descendants and the land.',                          'covenant',  'Genesis 15',            4),
  ('hagar-flees',           'Hagar Flees to the Wilderness',      'age-patriarchs', 'beer-lahai-roi','Hagar, pregnant with Ishmael, flees Sarah''s mistreatment. God meets her at a well.',              'event',     'Genesis 16',            5),
  ('sodom-destroyed',       'Destruction of Sodom and Gomorrah',  'age-patriarchs', 'sodom',        'God rains fire and brimstone on the cities of the plain for their wickedness. Lot escapes.',         'judgment',  'Genesis 18:16-19:29',   6),
  ('birth-of-isaac',        'Birth of Isaac',                     'age-patriarchs', 'beersheba',    'Sarah bears a son in old age as God promised. Abraham names him Isaac ("laughter").',                'event',     'Genesis 21:1-7',        7),
  ('hagar-in-wilderness',   'Hagar and Ishmael in the Wilderness','age-patriarchs', 'beersheba',    'Abraham sends Hagar and Ishmael away. God provides water and promises to make Ishmael a nation.',   'event',     'Genesis 21:8-21',       8),
  ('rebekah-at-well',       'Rebekah at the Well',                'age-patriarchs', 'haran',        'Abraham''s servant finds Rebekah at a well — God''s providential answer to prayer.',               'event',     'Genesis 24',            9),
  ('esau-sells-birthright', 'Esau Sells His Birthright',          'age-patriarchs', 'beersheba',    'Esau sells his birthright to Jacob for a bowl of stew.',                                            'event',     'Genesis 25:29-34',      10),
  ('jacob-deceives-isaac',  'Jacob Deceives Isaac',               'age-patriarchs', 'beersheba',    'Jacob, with Rebekah''s help, tricks blind Isaac into giving him the firstborn''s blessing.',        'event',     'Genesis 27',            11),
  ('jacob-at-penuel',       'Jacob Wrestles at Penuel',           'age-patriarchs', 'penuel',       'Jacob wrestles with God through the night and is renamed Israel.',                                   'miracle',   'Genesis 32:22-32',      12),
  ('dinah-at-shechem',      'Incident at Shechem',                'age-patriarchs', 'shechem',      'Dinah is assaulted at Shechem; Simeon and Levi take violent revenge.',                               'event',     'Genesis 34',            13),
  ('joseph-sold',           'Joseph Sold by His Brothers',        'age-patriarchs', 'dothan',       'Joseph''s brothers sell him to Ishmaelite traders heading to Egypt.',                               'event',     'Genesis 37:12-36',      14),
  ('judah-and-tamar',       'Judah and Tamar',                    'age-patriarchs', 'timnah',       'Tamar disguises herself to secure offspring from Judah after being denied his son Shelah.',          'event',     'Genesis 38',            15),
  ('joseph-interprets',     'Joseph Interprets Pharaoh''s Dreams','age-patriarchs', 'egypt-goshen', 'Joseph interprets Pharaoh''s dreams of famine and is made vizier over Egypt.',                      'event',     'Genesis 41',            16),
  ('jacob-goes-to-egypt',   'Jacob''s Family Moves to Egypt',     'age-patriarchs', 'egypt-goshen', 'Jacob and his entire family move to Egypt to survive the famine, settling in Goshen.',               'event',     'Genesis 46-47',         17),
  ('jacob-blesses-sons',    'Jacob Blesses His Sons',             'age-patriarchs', 'egypt-goshen', 'Jacob gives prophetic blessings to each of his twelve sons before dying.',                           'prophecy',  'Genesis 49',            18),

  -- ── Exodus & Wilderness ─────────────────────────────────────────────────
  ('burning-bush',          'The Burning Bush',                   'age-exodus',   'sinai',          'God calls Moses from a bush that burns but is not consumed. "I AM WHO I AM."',                      'miracle',   'Exodus 3:1-4:17',      0),
  ('ten-plagues',           'The Ten Plagues',                    'age-exodus',   'raamses',        'God sends ten devastating plagues on Egypt to compel Pharaoh to release Israel.',                    'judgment',  'Exodus 7-12',          0),
  ('crossing-red-sea',      'Crossing the Red Sea',               'age-exodus',   'red-sea',        'God parts the waters for Israel and closes them on the pursuing Egyptian army.',                     'miracle',   'Exodus 14',            3),
  ('water-from-rock',       'Water from the Rock',                'age-exodus',   'rephidim',       'Moses strikes the rock at Horeb and water gushes out for the thirsty people.',                      'miracle',   'Exodus 17:1-7',        4),
  ('battle-of-rephidim',    'Battle with Amalek at Rephidim',     'age-exodus',   'rephidim',       'Israel fights Amalek. As long as Moses holds up his hands, Israel prevails.',                       'battle',    'Exodus 17:8-16',       5),
  ('golden-calf',           'The Golden Calf',                    'age-exodus',   'sinai',          'While Moses is on the mountain, Aaron makes a golden calf and the people worship it.',              'judgment',  'Exodus 32',            3),
  ('tabernacle-built',      'Tabernacle Constructed',             'age-exodus',   'sinai',          'The Tabernacle is built according to God''s pattern. His glory fills it.',                          'event',     'Exodus 35-40',         4),
  ('twelve-spies',          'Twelve Spies Sent to Canaan',        'age-exodus',   'kadesh-barnea',  'Moses sends twelve spies. Ten bring a bad report; only Joshua and Caleb trust God.',                'event',     'Numbers 13-14',        5),
  ('korahs-rebellion',      'Korah''s Rebellion',                 'age-exodus',   'kadesh-barnea',  'Korah, Dathan, and Abiram rebel against Moses. The earth opens and swallows them.',                 'judgment',  'Numbers 16',           6),
  ('bronze-serpent',         'The Bronze Serpent',                 'age-exodus',   'punon',          'Venomous snakes punish Israel. God tells Moses to make a bronze serpent — all who look at it live.','miracle',   'Numbers 21:4-9',       7),
  ('defeat-of-sihon',       'Defeat of Sihon',                   'age-exodus',   'heshbon',        'Israel defeats Sihon king of the Amorites and takes his territory.',                                'battle',    'Numbers 21:21-32',     8),
  ('defeat-of-og',          'Defeat of Og of Bashan',             'age-exodus',   'edrei',          'Israel defeats Og, the giant king of Bashan, and takes his territory.',                             'battle',    'Numbers 21:33-35',     9),
  ('balaams-donkey',        'Balaam''s Donkey Speaks',            'age-exodus',   'plains-of-moab', 'Balaam''s donkey sees the angel of the Lord and speaks to its master.',                             'miracle',   'Numbers 22:21-35',     10),
  ('balaam-blesses-israel', 'Balaam Blesses Israel',              'age-exodus',   'plains-of-moab', 'Hired to curse Israel, Balaam is compelled by God to bless them instead — four times.',             'prophecy',  'Numbers 23-24',        11),
  ('sin-at-peor',           'Sin at Baal-Peor',                   'age-exodus',   'beth-peor',      'Israel sins with Moabite women and worships Baal of Peor. A plague kills 24,000.',                 'judgment',  'Numbers 25',           12),
  ('aarons-death',          'Death of Aaron',                     'age-exodus',   'mt-hor',         'Aaron dies on Mount Hor. His priestly garments are transferred to Eleazar.',                        'event',     'Numbers 20:22-29',     13),
  ('moses-farewell',        'Moses'' Farewell and Death',         'age-exodus',   'mt-nebo',        'Moses delivers his final speeches, views the Promised Land from Nebo, and dies.',                   'event',     'Deuteronomy 31-34',    14),
  ('miriams-leprosy',       'Miriam''s Leprosy',                  'age-exodus',   'hazeroth',       'Miriam and Aaron criticize Moses. Miriam is struck with leprosy for seven days.',                  'judgment',  'Numbers 12',           15),

  -- ── Conquest & Judges ───────────────────────────────────────────────────
  ('spies-and-rahab',       'Spies and Rahab',                    'age-conquest',  'jericho',       'Joshua sends two spies to Jericho. Rahab hides them and is promised safety.',                       'event',     'Joshua 2',             0),
  ('battle-of-ai',          'Battle of Ai',                       'age-conquest',  'ai',            'After Achan''s sin is judged, Israel conquers Ai by ambush.',                                      'battle',    'Joshua 7-8',           3),
  ('gibeonite-deception',   'Gibeonite Deception',                'age-conquest',  'gibeon',        'The Gibeonites trick Joshua into a peace treaty by disguising themselves as travelers.',             'event',     'Joshua 9',             4),
  ('sun-stands-still',      'Sun Stands Still',                   'age-conquest',  'gibeon',        'Joshua commands the sun to stand still while Israel defeats the Amorite coalition.',                 'miracle',   'Joshua 10:1-15',       5),
  ('waters-of-merom',       'Battle of the Waters of Merom',      'age-conquest',  'shiloh-north',  'Joshua defeats a northern Canaanite coalition led by Jabin of Hazor.',                              'battle',    'Joshua 11:1-15',       6),
  ('covenant-at-shechem',   'Covenant at Shechem',                'age-conquest',  'shechem',       'Joshua leads Israel in covenant renewal. "Choose this day whom you will serve."',                    'covenant',  'Joshua 24',            7),
  ('ehud-kills-eglon',      'Ehud Assassinates Eglon',            'age-conquest',  'jericho',       'Left-handed Ehud kills fat King Eglon of Moab with a hidden dagger.',                              'battle',    'Judges 3:12-30',       8),
  ('gideons-fleece',        'Gideon''s Fleece',                   'age-conquest',  'ophrah',        'Gideon tests God with a fleece — wet then dry — before going to battle.',                          'event',     'Judges 6:36-40',       9),
  ('gideons-victory',       'Gideon''s 300 Defeat Midian',        'age-conquest',  'jezreel-spring','Gideon''s 300 men rout the Midianite army with torches and trumpets.',                             'battle',    'Judges 7',             10),
  ('jephthahs-vow',         'Jephthah''s Vow',                   'age-conquest',  'mizpah',        'Jephthah makes a rash vow before defeating the Ammonites.',                                        'battle',    'Judges 11',            11),
  ('samson-at-gaza',        'Samson at Gaza',                     'age-conquest',  'gaza',          'Samson carries the gates of Gaza on his shoulders to the top of a hill.',                           'miracle',   'Judges 16:1-3',        12),
  ('samson-and-delilah',    'Samson and Delilah',                 'age-conquest',  'timnah',        'Delilah betrays Samson to the Philistines. His hair is cut and his strength leaves.',               'event',     'Judges 16:4-22',       13),
  ('samsons-death',         'Samson''s Death',                    'age-conquest',  'gaza',          'Blind Samson pushes apart the pillars of the Philistine temple, killing himself and thousands.',    'battle',    'Judges 16:23-31',      14),
  ('ruth-and-boaz',         'Ruth Meets Boaz',                    'age-conquest',  'bethlehem',     'Ruth gleans in Boaz''s field. He notices her and shows her kindness.',                              'event',     'Ruth 2',               15),
  ('ark-captured',          'The Ark Captured',                   'age-conquest',  'aphek',         'The Philistines capture the Ark of the Covenant. Eli''s sons are killed. Eli dies.',               'battle',    '1 Samuel 4',           16),
  ('ark-returned',          'The Ark Returned',                   'age-conquest',  'bethshemesh',   'The Philistines send the Ark back on a cart pulled by cows. It arrives at Beth-Shemesh.',           'event',     '1 Samuel 6',           17),
  ('samuel-at-mizpah',      'Samuel Leads Revival at Mizpah',     'age-conquest',  'mizpah',        'Samuel calls Israel to repentance. God thunders against the Philistines at Mizpah.',                'battle',    '1 Samuel 7',           18),

  -- ── United Monarchy ─────────────────────────────────────────────────────
  ('saul-anointed',         'Saul Anointed King',                 'age-united-monarchy', 'mizpah',       'Samuel anoints Saul in private, then presents him by lot at Mizpah.',                         'event',     '1 Samuel 9:1-10:27',   0),
  ('saul-rescues-jabesh',   'Saul Rescues Jabesh-Gilead',         'age-united-monarchy', 'jabesh-gilead','Saul rallies Israel and defeats the Ammonites besieging Jabesh-Gilead.',                      'battle',    '1 Samuel 11',          0),
  ('saul-rejected',         'Saul Rejected as King',              'age-united-monarchy', 'bethel-gilgal','Saul offers an unauthorized sacrifice. Samuel declares God has rejected his kingship.',        'judgment',  '1 Samuel 13:1-15',     0),
  ('jonathan-at-michmash',  'Jonathan''s Raid at Michmash',       'age-united-monarchy', 'michmash',    'Jonathan and his armor-bearer attack the Philistine garrison, triggering a rout.',                'battle',    '1 Samuel 14',          0),
  ('david-anointed-by-samuel','David Anointed by Samuel',         'age-united-monarchy', 'bethlehem',   'Samuel secretly anoints the young shepherd David as future king.',                                'event',     '1 Samuel 16:1-13',     0),
  ('david-and-goliath',     'David and Goliath',                  'age-united-monarchy', 'valley-of-elah','Young David kills the Philistine champion Goliath with a sling and a stone.',                 'battle',    '1 Samuel 17',          0),
  ('david-at-nob',          'David at Nob',                       'age-united-monarchy', 'nob',         'Fleeing Saul, David receives showbread and Goliath''s sword from Ahimelech the priest.',        'event',     '1 Samuel 21:1-9',      4),
  ('david-at-gath',         'David Feigns Madness at Gath',       'age-united-monarchy', 'gath',        'David takes refuge with Achish king of Gath and pretends to be insane.',                         'event',     '1 Samuel 21:10-15',    4),
  ('david-at-engedi',       'David Spares Saul at En-Gedi',       'age-united-monarchy', 'en-gedi',     'David secretly cuts Saul''s robe in a cave but refuses to kill the Lord''s anointed.',           'event',     '1 Samuel 24',          4),
  ('david-and-abigail',     'David and Abigail',                  'age-united-monarchy', 'carmel-town', 'Abigail''s wisdom prevents David from taking revenge on her foolish husband Nabal.',             'event',     '1 Samuel 25',          4),
  ('saul-at-endor',         'Saul Consults the Medium at Endor',  'age-united-monarchy', 'endor',       'On the eve of battle, Saul consults a medium who conjures Samuel''s spirit.',                    'event',     '1 Samuel 28',          4),
  ('death-of-saul',         'Death of Saul',                      'age-united-monarchy', 'mt-gilboa',   'Saul and Jonathan die in battle against the Philistines on Mount Gilboa.',                       'battle',    '1 Samuel 31',          4),
  ('david-and-nathan',      'Nathan Confronts David',             'age-united-monarchy', 'jerusalem',   'Nathan tells David a parable and declares "You are the man!" after David''s sin with Bathsheba.','prophecy',  '2 Samuel 12:1-15',     4),
  ('absaloms-revolt',       'Absalom''s Revolt',                  'age-united-monarchy', 'hebron',      'Absalom declares himself king at Hebron and David flees Jerusalem.',                              'event',     '2 Samuel 15',          5),
  ('absaloms-death',        'Absalom''s Death',                   'age-united-monarchy', 'mahanaim',    'Absalom is caught in an oak tree and killed by Joab despite David''s orders to spare him.',       'battle',    '2 Samuel 18',          5),
  ('solomons-wisdom',       'Solomon''s Wisdom',                  'age-united-monarchy', 'gibeon',      'God appears to Solomon at Gibeon. Solomon asks for wisdom and receives it abundantly.',            'event',     '1 Kings 3:1-15',       4),
  ('solomons-judgment',     'Solomon''s Judgment',                'age-united-monarchy', 'jerusalem',   'Solomon resolves the dispute between two mothers, revealing his God-given wisdom.',                'event',     '1 Kings 3:16-28',      4),
  ('visit-of-sheba',        'Visit of the Queen of Sheba',        'age-united-monarchy', 'jerusalem',   'The Queen of Sheba visits Solomon with great wealth, tests his wisdom, and is overwhelmed.',       'event',     '1 Kings 10:1-13',      4),

  -- ── Divided Monarchy ────────────────────────────────────────────────────
  ('jeroboams-calves',      'Jeroboam''s Golden Calves',          'age-divided-monarchy', 'dan',        'Jeroboam sets up golden calves at Dan and Bethel to keep the people from going to Jerusalem.',     'judgment',  '1 Kings 12:25-33',     0),
  ('elijah-fed-by-ravens',  'Elijah Fed by Ravens',               'age-divided-monarchy', 'brook-cherith','During the drought, God sends ravens to feed Elijah at the brook Cherith.',                    'miracle',   '1 Kings 17:1-7',       3),
  ('elijah-at-zarephath',   'Elijah at Zarephath',                'age-divided-monarchy', 'zarephath',  'Elijah stays with a widow. Her flour and oil never run out. He raises her dead son.',              'miracle',   '1 Kings 17:8-24',      4),
  ('elijah-flees-to-sinai', 'Elijah Flees to Sinai',             'age-divided-monarchy', 'sinai',      'After Carmel, Elijah flees to Mount Sinai where God speaks in a still small voice.',               'event',     '1 Kings 19',           4),
  ('naboths-vineyard',      'Naboth''s Vineyard',                 'age-divided-monarchy', 'jezreel',    'Jezebel engineers Naboth''s murder so Ahab can take his vineyard. Elijah pronounces doom.',       'judgment',  '1 Kings 21',           4),
  ('ahabs-death',           'Ahab''s Death at Ramoth-Gilead',     'age-divided-monarchy', 'ramoth-gilead','Ahab dies in battle despite a disguise, fulfilling Micaiah''s prophecy.',                       'battle',    '1 Kings 22:29-40',     4),
  ('elijah-taken-up',       'Elijah Taken Up',                    'age-divided-monarchy', 'jordan-river','Elijah is taken up to heaven in a chariot of fire. Elisha receives a double portion.',           'miracle',   '2 Kings 2:1-18',       5),
  ('elisha-and-naaman',     'Naaman Healed of Leprosy',           'age-divided-monarchy', 'jordan-river','Naaman, the Syrian commander, is healed by washing seven times in the Jordan.',                 'miracle',   '2 Kings 5',            6),
  ('elisha-at-dothan',      'Elisha at Dothan',                   'age-divided-monarchy', 'dothan',     'An Aramean army surrounds Elisha, but he reveals an angelic host. The Arameans are struck blind.', 'miracle',   '2 Kings 6:8-23',       7),
  ('elisha-and-shunammite', 'Elisha Raises the Shunammite''s Son','age-divided-monarchy', 'shunem',     'Elisha raises the Shunammite woman''s dead son back to life.',                                    'miracle',   '2 Kings 4:8-37',       8),
  ('jehus-revolution',      'Jehu''s Revolution',                 'age-divided-monarchy', 'jezreel',    'Jehu is anointed king, kills Joram and Ahaziah, and has Jezebel thrown from a window.',            'battle',    '2 Kings 9-10',         9),
  ('athaliahs-coup',        'Athaliah''s Coup and Fall',          'age-divided-monarchy', 'jerusalem',  'Athaliah seizes Judah''s throne. Years later Joash is revealed and Athaliah executed.',            'event',     '2 Kings 11',           10),
  ('amos-at-bethel',        'Amos Prophesies at Bethel',          'age-divided-monarchy', 'bethel',     'Amos, a shepherd from Tekoa, delivers God''s judgment on Israel at the royal sanctuary.',          'prophecy',  'Amos 7:10-17',         11),
  ('jonah-sent-to-nineveh', 'Jonah Sent to Nineveh',             'age-divided-monarchy', 'joppa',      'Jonah flees from God''s call by boarding a ship at Joppa. Swallowed by a great fish.',            'event',     'Jonah 1',              12),

  -- ── Judah Alone & Exile ─────────────────────────────────────────────────
  ('hezekiahs-tunnel',      'Hezekiah''s Tunnel',                'age-judah-exile',  'jerusalem',    'Hezekiah cuts a tunnel through rock to bring water inside the city walls before the Assyrian siege.', 'event',   '2 Kings 20:20; 2 Chronicles 32:30', 0),
  ('sennacheribs-siege',    'Sennacherib''s Siege of Jerusalem',  'age-judah-exile',  'jerusalem',    'Sennacherib besieges Jerusalem. God sends an angel who kills 185,000 Assyrians in one night.',     'miracle',   '2 Kings 18:13-19:37',  0),
  ('sennacherib-at-lachish','Sennacherib at Lachish',             'age-judah-exile',  'lachish',      'Sennacherib besieges and captures Lachish, Judah''s second most important city.',                  'battle',    '2 Kings 18:14, 17; Isaiah 36:2', 0),
  ('manassehs-repentance',  'Manasseh''s Repentance',             'age-judah-exile',  'babylon',      'Wicked Manasseh is captured and taken to Babylon, where he humbles himself before God.',           'event',     '2 Chronicles 33:10-17', 3),
  ('book-of-law-found',     'Finding the Book of the Law',        'age-judah-exile',  'jerusalem',    'During Temple repairs under Josiah, the Book of the Law is discovered. Josiah tears his robes.',   'event',     '2 Kings 22:3-20',      4),
  ('josiahs-reform',        'Josiah''s Great Reform',             'age-judah-exile',  'jerusalem',    'Josiah destroys pagan shrines, renews the covenant, and celebrates Passover.',                     'event',     '2 Kings 23:1-25',      5),
  ('josiahs-death',         'Death of Josiah at Megiddo',         'age-judah-exile',  'megiddo',      'Josiah is killed in battle against Pharaoh Neco at Megiddo.',                                      'battle',    '2 Kings 23:29-30',     6),
  ('battle-of-carchemish',  'Battle of Carchemish',               'age-judah-exile',  'carchemish',   'Nebuchadnezzar defeats Pharaoh Neco at Carchemish, establishing Babylonian supremacy.',            'battle',    'Jeremiah 46:2',        7),
  ('first-deportation',     'First Deportation to Babylon',       'age-judah-exile',  'babylon',      'Nebuchadnezzar deports the first group of Judean captives including Daniel.',                      'event',     '2 Kings 24:1-4; Daniel 1:1-6', 8),
  ('second-deportation',    'Second Deportation (Jehoiachin)',     'age-judah-exile',  'babylon',      'Nebuchadnezzar deports Jehoiachin, the queen mother, and 10,000 captives.',                       'event',     '2 Kings 24:10-17',     9),
  ('jeremiahs-cistern',     'Jeremiah Thrown into a Cistern',      'age-judah-exile',  'jerusalem',    'Jeremiah is thrown into a muddy cistern for preaching surrender. Ebed-Melech rescues him.',        'event',     'Jeremiah 38:1-13',     10),
  ('fiery-furnace',         'The Fiery Furnace',                  'age-judah-exile',  'babylon',      'Shadrach, Meshach, and Abednego refuse to bow to the golden image. A fourth figure appears in the fire.', 'miracle', 'Daniel 3',     11),
  ('writing-on-wall',       'Writing on the Wall',                'age-judah-exile',  'babylon',      'A hand writes "MENE MENE TEKEL UPHARSIN" on the wall during Belshazzar''s feast.',                'prophecy',  'Daniel 5',             12),
  ('daniel-in-lions-den',   'Daniel in the Lions'' Den',          'age-judah-exile',  'babylon',      'Daniel is thrown into a lions'' den for praying to God. He is untouched.',                         'miracle',   'Daniel 6',             13),
  ('gedaliah-assassinated', 'Gedaliah Assassinated',              'age-judah-exile',  'mizpah',       'Ishmael assassinates Gedaliah, the governor of Judah, scattering the remnant.',                   'event',     'Jeremiah 41; 2 Kings 25:25-26', 14),
  ('remnant-flees-egypt',   'Remnant Flees to Egypt',             'age-judah-exile',  'tahpanhes',    'The surviving remnant flees to Egypt against Jeremiah''s warning, taking the prophet with them.',  'event',     'Jeremiah 42-44',       15),
  ('jehoiachin-released',   'Jehoiachin Released from Prison',    'age-judah-exile',  'babylon',      'Evil-Merodach releases Jehoiachin and gives him a place of honor at the Babylonian court.',        'event',     '2 Kings 25:27-30',     16),

  -- ── Return & Restoration ────────────────────────────────────────────────
  ('decree-of-cyrus',       'Decree of Cyrus',                   'age-return',   'susa',           'Cyrus the Great decrees that the Jews may return and rebuild the Temple in Jerusalem.',              'event',     'Ezra 1:1-4',           0),
  ('first-return',          'First Return under Zerubbabel',      'age-return',   'jerusalem',      'Zerubbabel leads about 50,000 exiles back to Jerusalem.',                                           'event',     'Ezra 2',               0),
  ('altar-rebuilt',         'Altar Rebuilt',                      'age-return',   'jerusalem',      'The returned exiles rebuild the altar and resume sacrifices before the Temple is rebuilt.',           'event',     'Ezra 3:1-6',           3),
  ('temple-foundation',     'Temple Foundation Laid',             'age-return',   'jerusalem',      'The foundation of the second Temple is laid. Older people weep, remembering Solomon''s Temple.',     'event',     'Ezra 3:8-13',          4),
  ('esther-saves-people',   'Esther Saves Her People',            'age-return',   'susa',           'Queen Esther risks her life to expose Haman''s plot. The Jews are authorized to defend themselves.', 'event',     'Esther 4-9',           5),
  ('purim',                 'Feast of Purim Established',         'age-return',   'susa',           'The Jews celebrate their deliverance with the annual feast of Purim.',                               'event',     'Esther 9:20-32',       6),
  ('ezra-reads-law',        'Ezra Reads the Law',                'age-return',   'jerusalem',      'Ezra reads the Torah aloud to the assembled people. They weep, then celebrate.',                     'event',     'Nehemiah 8',           7),
  ('walls-dedicated',       'Dedication of Jerusalem''s Walls',   'age-return',   'jerusalem',      'The completed walls are dedicated with joyful processions and praise.',                              'event',     'Nehemiah 12:27-47',    8),
  ('ezras-reform',          'Ezra''s Reform',                    'age-return',   'jerusalem',      'Ezra confronts the people about intermarriage with pagan nations. They commit to reform.',           'event',     'Ezra 9-10',            9),
  ('nehemiahs-night-ride',  'Nehemiah''s Night Inspection',       'age-return',   'jerusalem',      'Nehemiah secretly inspects Jerusalem''s ruined walls by night before rallying the people to rebuild.', 'event',   'Nehemiah 2:11-20',     10)

on conflict (event_id) do nothing;

commit;
