-- EventPeople expansion — links people to events.
-- References event_ids from both the original seed and the events expansion.

begin;

insert into public."BP_EventPeople" (event_id, person_id) values

  -- ── Creation & Primeval ─────────────────────────────────────────────────
  ('creation',              'adam'),
  ('creation',              'eve'),
  ('the-fall',              'adam'),
  ('the-fall',              'eve'),
  ('cain-kills-abel',       'cain'),
  ('cain-kills-abel',       'abel'),
  ('the-flood',             'noah'),
  ('the-flood',             'shem'),
  ('the-flood',             'ham'),
  ('the-flood',             'japheth'),
  ('covenant-with-noah',    'noah'),
  ('tower-of-babel',        'nimrod'),

  -- ── Patriarchs ──────────────────────────────────────────────────────────
  ('abram-leaves-ur',       'abraham'),
  ('abram-leaves-ur',       'sarah'),
  ('abram-leaves-ur',       'lot'),
  ('abraham-in-egypt',      'abraham'),
  ('abraham-in-egypt',      'sarah'),
  ('covenant-of-pieces',    'abraham'),
  ('hagar-flees',           'hagar'),
  ('hagar-flees',           'angel-of-lord'),
  ('sodom-destroyed',       'lot'),
  ('sodom-destroyed',       'abraham'),
  ('birth-of-isaac',        'abraham'),
  ('birth-of-isaac',        'sarah'),
  ('birth-of-isaac',        'isaac'),
  ('hagar-in-wilderness',   'hagar'),
  ('hagar-in-wilderness',   'ishmael'),
  ('hagar-in-wilderness',   'abraham'),
  ('rebekah-at-well',       'rebekah'),
  ('esau-sells-birthright', 'esau'),
  ('esau-sells-birthright', 'jacob'),
  ('jacob-deceives-isaac',  'jacob'),
  ('jacob-deceives-isaac',  'isaac'),
  ('jacob-deceives-isaac',  'rebekah'),
  ('jacob-deceives-isaac',  'esau'),
  ('jacobs-ladder',         'jacob'),
  ('jacob-at-penuel',       'jacob'),
  ('jacob-at-penuel',       'angel-of-lord'),
  ('dinah-at-shechem',      'dinah'),
  ('joseph-sold',           'joseph'),
  ('joseph-sold',           'judah'),
  ('joseph-sold',           'reuben'),
  ('judah-and-tamar',       'judah'),
  ('judah-and-tamar',       'tamar-genesis'),
  ('joseph-interprets',     'joseph'),
  ('jacob-goes-to-egypt',   'jacob'),
  ('jacob-goes-to-egypt',   'joseph'),
  ('jacob-blesses-sons',    'jacob'),
  ('jacob-blesses-sons',    'judah'),
  ('jacob-blesses-sons',    'joseph'),
  ('jacob-blesses-sons',    'benjamin'),
  ('abraham-at-shechem',    'sarah'),

  -- ── Exodus & Wilderness ─────────────────────────────────────────────────
  ('burning-bush',          'moses'),
  ('ten-plagues',           'moses'),
  ('ten-plagues',           'aaron'),
  ('ten-plagues',           'pharaoh-of-exodus'),
  ('exodus',                'aaron'),
  ('exodus',                'miriam'),
  ('crossing-red-sea',      'moses'),
  ('crossing-red-sea',      'miriam'),
  ('crossing-red-sea',      'pharaoh-of-exodus'),
  ('water-from-rock',       'moses'),
  ('battle-of-rephidim',    'moses'),
  ('battle-of-rephidim',    'aaron'),
  ('battle-of-rephidim',    'joshua'),
  ('giving-of-law',         'aaron'),
  ('golden-calf',           'moses'),
  ('golden-calf',           'aaron'),
  ('tabernacle-built',      'moses'),
  ('tabernacle-built',      'bezalel'),
  ('twelve-spies',          'moses'),
  ('twelve-spies',          'joshua'),
  ('twelve-spies',          'caleb'),
  ('korahs-rebellion',      'moses'),
  ('korahs-rebellion',      'aaron'),
  ('korahs-rebellion',      'korah'),
  ('korahs-rebellion',      'dathan'),
  ('korahs-rebellion',      'abiram'),
  ('bronze-serpent',         'moses'),
  ('defeat-of-sihon',       'moses'),
  ('defeat-of-sihon',       'sihon'),
  ('defeat-of-og',          'moses'),
  ('defeat-of-og',          'og'),
  ('balaams-donkey',        'balaam'),
  ('balaams-donkey',        'angel-of-lord'),
  ('balaam-blesses-israel', 'balaam'),
  ('balaam-blesses-israel', 'balak'),
  ('sin-at-peor',           'phinehas-eleazar'),
  ('aarons-death',          'aaron'),
  ('aarons-death',          'moses'),
  ('aarons-death',          'eleazar'),
  ('moses-farewell',        'moses'),
  ('moses-farewell',        'joshua'),
  ('miriams-leprosy',       'miriam'),
  ('miriams-leprosy',       'aaron'),
  ('miriams-leprosy',       'moses'),

  -- ── Conquest & Judges ───────────────────────────────────────────────────
  ('spies-and-rahab',       'rahab'),
  ('spies-and-rahab',       'joshua'),
  ('crossing-jordan',       'joshua'),
  ('crossing-jordan',       'caleb'),
  ('fall-of-jericho',       'rahab'),
  ('battle-of-ai',          'joshua'),
  ('battle-of-ai',          'achan'),
  ('gibeonite-deception',   'joshua'),
  ('sun-stands-still',      'joshua'),
  ('waters-of-merom',       'joshua'),
  ('covenant-at-shechem',   'joshua'),
  ('tabernacle-at-shiloh',  'joshua'),
  ('tabernacle-at-shiloh',  'eleazar'),
  ('deborahs-victory',      'barak'),
  ('deborahs-victory',      'sisera'),
  ('deborahs-victory',      'jael'),
  ('ehud-kills-eglon',      'ehud'),
  ('gideons-fleece',        'gideon'),
  ('gideons-fleece',        'angel-of-lord'),
  ('gideons-victory',       'gideon'),
  ('jephthahs-vow',         'jephthah'),
  ('samson-at-gaza',        'samson'),
  ('samson-and-delilah',    'samson'),
  ('samson-and-delilah',    'delilah'),
  ('samsons-death',         'samson'),
  ('ruth-and-boaz',         'ruth'),
  ('ruth-and-boaz',         'boaz'),
  ('ruth-and-boaz',         'naomi'),
  ('ark-captured',          'eli'),
  ('ark-captured',          'phinehas-eli'),
  ('ark-captured',          'hophni'),
  ('ark-returned',          'samuel'),
  ('samuel-at-mizpah',      'samuel'),

  -- ── United Monarchy ─────────────────────────────────────────────────────
  ('saul-anointed',         'saul'),
  ('saul-anointed',         'samuel'),
  ('saul-rescues-jabesh',   'saul'),
  ('saul-rejected',         'saul'),
  ('saul-rejected',         'samuel'),
  ('jonathan-at-michmash',  'jonathan'),
  ('jonathan-at-michmash',  'saul'),
  ('david-anointed-by-samuel','david'),
  ('david-anointed-by-samuel','samuel'),
  ('david-and-goliath',     'david'),
  ('david-and-goliath',     'saul'),
  ('david-and-goliath',     'jonathan'),
  ('david-at-nob',          'david'),
  ('david-at-nob',          'doeg'),
  ('david-at-gath',         'david'),
  ('david-at-engedi',       'david'),
  ('david-at-engedi',       'saul'),
  ('david-and-abigail',     'david'),
  ('david-and-abigail',     'abigail'),
  ('david-and-abigail',     'nabal'),
  ('saul-at-endor',         'saul'),
  ('death-of-saul',         'saul'),
  ('death-of-saul',         'jonathan'),
  ('david-anointed-hebron',  'abner'),
  ('david-takes-jerusalem',  'joab'),
  ('david-and-nathan',      'david'),
  ('david-and-nathan',      'nathan-prophet'),
  ('david-and-nathan',      'bathsheba'),
  ('absaloms-revolt',       'absalom'),
  ('absaloms-revolt',       'david'),
  ('absaloms-revolt',       'hushai'),
  ('absaloms-revolt',       'ahithophel'),
  ('absaloms-death',        'absalom'),
  ('absaloms-death',        'joab'),
  ('absaloms-death',        'david'),
  ('solomons-temple',       'hiram-tyre'),
  ('solomons-wisdom',       'solomon'),
  ('solomons-judgment',     'solomon'),
  ('visit-of-sheba',        'solomon'),
  ('visit-of-sheba',        'queen-of-sheba'),
  ('kingdom-divides',       'rehoboam'),
  ('kingdom-divides',       'jeroboam-i'),

  -- ── Divided Monarchy ────────────────────────────────────────────────────
  ('jeroboams-calves',      'jeroboam-i'),
  ('elijah-fed-by-ravens',  'elijah'),
  ('elijah-at-zarephath',   'elijah'),
  ('elijah-on-carmel',      'ahab'),
  ('elijah-flees-to-sinai', 'elijah'),
  ('naboths-vineyard',      'ahab'),
  ('naboths-vineyard',      'jezebel'),
  ('naboths-vineyard',      'naboth'),
  ('naboths-vineyard',      'elijah'),
  ('ahabs-death',           'ahab'),
  ('ahabs-death',           'micaiah'),
  ('ahabs-death',           'jehoshaphat'),
  ('elijah-taken-up',       'elijah'),
  ('elijah-taken-up',       'elisha'),
  ('elisha-and-naaman',     'elisha'),
  ('elisha-and-naaman',     'naaman'),
  ('elisha-and-naaman',     'gehazi'),
  ('elisha-at-dothan',      'elisha'),
  ('elisha-and-shunammite', 'elisha'),
  ('jehus-revolution',      'jehu'),
  ('jehus-revolution',      'jezebel'),
  ('athaliahs-coup',        'athaliah'),
  ('athaliahs-coup',        'joash-judah'),
  ('amos-at-bethel',        'amos'),
  ('amos-at-bethel',        'jeroboam-ii'),
  ('fall-of-samaria',       'shalmaneser'),
  ('fall-of-samaria',       'hosea'),
  ('jonah-sent-to-nineveh', 'jonah'),
  ('jonah-at-nineveh',      'jonah'),

  -- ── Judah Alone & Exile ─────────────────────────────────────────────────
  ('hezekiahs-tunnel',      'hezekiah'),
  ('sennacheribs-siege',    'hezekiah'),
  ('sennacheribs-siege',    'sennacherib'),
  ('sennacheribs-siege',    'isaiah'),
  ('sennacherib-at-lachish','sennacherib'),
  ('manassehs-repentance',  'manasseh'),
  ('book-of-law-found',     'josiah'),
  ('book-of-law-found',     'huldah'),
  ('josiahs-reform',        'josiah'),
  ('josiahs-death',         'josiah'),
  ('josiahs-death',         'pharaoh-neco'),
  ('battle-of-carchemish',  'nebuchadnezzar'),
  ('battle-of-carchemish',  'pharaoh-neco'),
  ('first-deportation',     'nebuchadnezzar'),
  ('first-deportation',     'daniel'),
  ('first-deportation',     'shadrach'),
  ('first-deportation',     'meshach'),
  ('first-deportation',     'abednego'),
  ('second-deportation',    'nebuchadnezzar'),
  ('second-deportation',    'jehoiachin'),
  ('second-deportation',    'ezekiel'),
  ('fall-of-jerusalem',     'nebuchadnezzar'),
  ('fall-of-jerusalem',     'zedekiah'),
  ('fall-of-jerusalem',     'nebuzaradan'),
  ('jeremiahs-cistern',     'jeremiah'),
  ('jeremiahs-cistern',     'ebed-melech'),
  ('fiery-furnace',         'shadrach'),
  ('fiery-furnace',         'meshach'),
  ('fiery-furnace',         'abednego'),
  ('fiery-furnace',         'nebuchadnezzar'),
  ('writing-on-wall',       'daniel'),
  ('writing-on-wall',       'belshazzar'),
  ('daniel-in-babylon',     'nebuchadnezzar'),
  ('daniel-in-lions-den',   'daniel'),
  ('gedaliah-assassinated', 'gedaliah'),
  ('gedaliah-assassinated', 'ishmael-nethaniah'),
  ('remnant-flees-egypt',   'jeremiah'),
  ('remnant-flees-egypt',   'baruch'),
  ('jehoiachin-released',   'jehoiachin'),
  ('jehoiachin-released',   'evil-merodach'),

  -- ── Return & Restoration ────────────────────────────────────────────────
  ('decree-of-cyrus',       'cyrus'),
  ('first-return',          'zerubbabel'),
  ('first-return',          'jeshua-priest'),
  ('first-return',          'sheshbazzar'),
  ('altar-rebuilt',         'zerubbabel'),
  ('altar-rebuilt',         'jeshua-priest'),
  ('temple-foundation',     'zerubbabel'),
  ('temple-foundation',     'jeshua-priest'),
  ('temple-rebuilt',         'zerubbabel'),
  ('temple-rebuilt',         'jeshua-priest'),
  ('temple-rebuilt',         'haggai'),
  ('temple-rebuilt',         'zechariah-prophet'),
  ('temple-rebuilt',         'darius-i'),
  ('esther-saves-people',   'esther'),
  ('esther-saves-people',   'mordecai'),
  ('esther-saves-people',   'haman'),
  ('esther-saves-people',   'xerxes'),
  ('purim',                 'esther'),
  ('purim',                 'mordecai'),
  ('nehemiah-walls',        'sanballat'),
  ('nehemiah-walls',        'tobiah'),
  ('nehemiah-walls',        'geshem'),
  ('ezra-reads-law',        'ezra'),
  ('ezra-reads-law',        'nehemiah'),
  ('walls-dedicated',       'nehemiah'),
  ('ezras-reform',          'ezra'),
  ('nehemiahs-night-ride',  'nehemiah')

on conflict (event_id, person_id) do nothing;

commit;
