-- PersonAges expansion — links new people to their narrative ages.
-- is_primary = true for the person's main age, false for secondary appearances.

begin;

insert into public."BP_PersonAges" (person_id, age_id, is_primary) values

  -- ── Creation & Primeval History ─────────────────────────────────────────
  ('eve',             'age-creation',         true),
  ('cain',            'age-creation',         true),
  ('abel',            'age-creation',         true),
  ('seth',            'age-creation',         true),
  ('enoch',           'age-creation',         true),
  ('methuselah',      'age-creation',         true),
  ('lamech-cain',     'age-creation',         true),
  ('nimrod',          'age-creation',         true),
  ('shem',            'age-creation',         true),
  ('ham',             'age-creation',         true),
  ('japheth',         'age-creation',         true),

  -- ── Patriarchs ──────────────────────────────────────────────────────────
  ('lot',             'age-patriarchs',       true),
  ('hagar',           'age-patriarchs',       true),
  ('ishmael',         'age-patriarchs',       true),
  ('melchizedek',     'age-patriarchs',       true),
  ('rebekah',         'age-patriarchs',       true),
  ('esau',            'age-patriarchs',       true),
  ('laban',           'age-patriarchs',       true),
  ('rachel',          'age-patriarchs',       true),
  ('leah',            'age-patriarchs',       true),
  ('dinah',           'age-patriarchs',       true),
  ('reuben',          'age-patriarchs',       true),
  ('judah',           'age-patriarchs',       true),
  ('tamar-genesis',   'age-patriarchs',       true),
  ('potiphar',        'age-patriarchs',       true),
  ('benjamin',        'age-patriarchs',       true),

  -- ── Exodus & Wilderness ─────────────────────────────────────────────────
  ('aaron',           'age-exodus',           true),
  ('miriam',          'age-exodus',           true),
  ('pharaoh-of-exodus','age-exodus',          true),
  ('jethro',          'age-exodus',           true),
  ('zipporah',        'age-exodus',           true),
  ('caleb',           'age-exodus',           false),
  ('caleb',           'age-conquest',         true),
  ('korah',           'age-exodus',           true),
  ('balaam',          'age-exodus',           true),
  ('balak',           'age-exodus',           true),
  ('phinehas-eleazar','age-exodus',           true),
  ('eleazar',         'age-exodus',           true),
  ('eleazar',         'age-conquest',         false),
  ('nadab',           'age-exodus',           true),
  ('abihu',           'age-exodus',           true),
  ('bezalel',         'age-exodus',           true),
  ('dathan',          'age-exodus',           true),
  ('abiram',          'age-exodus',           true),
  ('og',              'age-exodus',           true),
  ('sihon',           'age-exodus',           true),

  -- ── Conquest & Judges ───────────────────────────────────────────────────
  ('rahab',           'age-conquest',         true),
  ('achan',           'age-conquest',         true),
  ('othniel',         'age-conquest',         true),
  ('ehud',            'age-conquest',         true),
  ('shamgar',         'age-conquest',         true),
  ('barak',           'age-conquest',         true),
  ('sisera',          'age-conquest',         true),
  ('jael',            'age-conquest',         true),
  ('gideon',          'age-conquest',         true),
  ('abimelech',       'age-conquest',         true),
  ('jephthah',        'age-conquest',         true),
  ('samson',          'age-conquest',         true),
  ('delilah',         'age-conquest',         true),
  ('manoah',          'age-conquest',         true),
  ('ruth',            'age-conquest',         true),
  ('boaz',            'age-conquest',         true),
  ('naomi',           'age-conquest',         true),
  ('eli',             'age-conquest',         true),
  ('phinehas-eli',    'age-conquest',         true),
  ('hophni',          'age-conquest',         true),
  ('micah-judges',    'age-conquest',         true),
  ('ibzan',           'age-conquest',         true),
  ('jair',            'age-conquest',         true),
  ('tola',            'age-conquest',         true),

  -- ── United Monarchy ─────────────────────────────────────────────────────
  ('saul',            'age-united-monarchy',  true),
  ('jonathan',        'age-united-monarchy',  true),
  ('michal',          'age-united-monarchy',  true),
  ('abigail',         'age-united-monarchy',  true),
  ('nabal',           'age-united-monarchy',  true),
  ('abner',           'age-united-monarchy',  true),
  ('ish-bosheth',     'age-united-monarchy',  true),
  ('joab',            'age-united-monarchy',  true),
  ('bathsheba',       'age-united-monarchy',  true),
  ('uriah',           'age-united-monarchy',  true),
  ('absalom',         'age-united-monarchy',  true),
  ('amnon',           'age-united-monarchy',  true),
  ('tamar-david',     'age-united-monarchy',  true),
  ('nathan-prophet',  'age-united-monarchy',  true),
  ('zadok',           'age-united-monarchy',  true),
  ('abishai',         'age-united-monarchy',  true),
  ('mephibosheth',    'age-united-monarchy',  true),
  ('shimei',          'age-united-monarchy',  true),
  ('adonijah',        'age-united-monarchy',  true),
  ('hiram-tyre',      'age-united-monarchy',  true),
  ('queen-of-sheba',  'age-united-monarchy',  true),
  ('rehoboam',        'age-united-monarchy',  false),
  ('rehoboam',        'age-divided-monarchy', true),
  ('jeroboam-i',      'age-united-monarchy',  false),
  ('jeroboam-i',      'age-divided-monarchy', true),
  ('doeg',            'age-united-monarchy',  true),
  ('hushai',          'age-united-monarchy',  true),
  ('ahithophel',      'age-united-monarchy',  true),

  -- ── Divided Monarchy ────────────────────────────────────────────────────
  ('ahab',            'age-divided-monarchy', true),
  ('jezebel',         'age-divided-monarchy', true),
  ('naboth',          'age-divided-monarchy', true),
  ('omri',            'age-divided-monarchy', true),
  ('jehu',            'age-divided-monarchy', true),
  ('athaliah',        'age-divided-monarchy', true),
  ('joash-judah',     'age-divided-monarchy', true),
  ('micaiah',         'age-divided-monarchy', true),
  ('obadiah-steward', 'age-divided-monarchy', true),
  ('naaman',          'age-divided-monarchy', true),
  ('gehazi',          'age-divided-monarchy', true),
  ('amos',            'age-divided-monarchy', true),
  ('hosea',           'age-divided-monarchy', true),
  ('jeroboam-ii',     'age-divided-monarchy', true),
  ('uzziah',          'age-divided-monarchy', true),
  ('ahaz',            'age-divided-monarchy', false),
  ('ahaz',            'age-judah-exile',      true),
  ('hezekiah',        'age-divided-monarchy', false),
  ('hezekiah',        'age-judah-exile',      true),
  ('sennacherib',     'age-judah-exile',      true),
  ('jonah',           'age-divided-monarchy', true),
  ('joel',            'age-divided-monarchy', true),
  ('micah-prophet',   'age-divided-monarchy', true),
  ('ben-hadad',       'age-divided-monarchy', true),
  ('elah',            'age-divided-monarchy', true),
  ('zimri',           'age-divided-monarchy', true),
  ('baasha',          'age-divided-monarchy', true),
  ('asa',             'age-divided-monarchy', true),
  ('jehoshaphat',     'age-divided-monarchy', true),
  ('jehoram-israel',  'age-divided-monarchy', true),
  ('jehoram-judah',   'age-divided-monarchy', true),
  ('hazael',          'age-divided-monarchy', true),
  ('shalmaneser',     'age-divided-monarchy', true),
  ('tiglath-pileser', 'age-divided-monarchy', true),

  -- ── Judah Alone & Exile ─────────────────────────────────────────────────
  ('josiah',          'age-judah-exile',      true),
  ('manasseh',        'age-judah-exile',      true),
  ('zedekiah',        'age-judah-exile',      true),
  ('jehoiakim',       'age-judah-exile',      true),
  ('jehoiachin',      'age-judah-exile',      true),
  ('nebuchadnezzar',  'age-judah-exile',      true),
  ('baruch',          'age-judah-exile',      true),
  ('ebed-melech',     'age-judah-exile',      true),
  ('gedaliah',        'age-judah-exile',      true),
  ('shadrach',        'age-judah-exile',      true),
  ('meshach',         'age-judah-exile',      true),
  ('abednego',        'age-judah-exile',      true),
  ('belshazzar',      'age-judah-exile',      true),
  ('habakkuk',        'age-judah-exile',      true),
  ('zephaniah-prophet','age-judah-exile',     true),
  ('nahum',           'age-judah-exile',      true),
  ('obadiah-prophet', 'age-judah-exile',      true),
  ('huldah',          'age-judah-exile',      true),
  ('pharaoh-neco',    'age-judah-exile',      true),
  ('ishmael-nethaniah','age-judah-exile',     true),
  ('evil-merodach',   'age-judah-exile',      true),
  ('nebuzaradan',     'age-judah-exile',      true),

  -- ── Return & Restoration ────────────────────────────────────────────────
  ('zerubbabel',      'age-return',           true),
  ('haggai',          'age-return',           true),
  ('zechariah-prophet','age-return',          true),
  ('malachi',         'age-return',           true),
  ('cyrus',           'age-return',           true),
  ('darius-i',        'age-return',           true),
  ('artaxerxes',      'age-return',           true),
  ('sanballat',       'age-return',           true),
  ('tobiah',          'age-return',           true),
  ('geshem',          'age-return',           true),
  ('esther',          'age-return',           true),
  ('mordecai',        'age-return',           true),
  ('haman',           'age-return',           true),
  ('xerxes',          'age-return',           true),
  ('jeshua-priest',   'age-return',           true),
  ('sheshbazzar',     'age-return',           true),
  ('eliashib',        'age-return',           true)

on conflict (person_id, age_id) do nothing;

commit;
