-- Seed data for Church History tables (CH_ prefix).
-- Generated from timeline-scratch/src/data/churchHistoryData.js and works.js
-- Uses batched multi-row INSERTs for Supabase CLI compatibility.

begin;

-- ── CH_Eras ────────────────────────────────────────────────────────────
INSERT INTO public."CH_Eras" (era_id, name, start_year, end_year, color, description) VALUES
  ('era-apostolic', 'The Apostolic Age', 1, 100, '#00acc1', NULL),
  ('era-ante-nicene', 'The Ante-Nicene Age', 100, 325, '#7b1fa2', NULL),
  ('era-first-four-councils', 'The First Four Councils', 325, 451, '#1976d2', NULL),
  ('era-monks-missionaries', 'Monks & Missionaries', 450, 1000, '#388e3c', NULL),
  ('era-cluniac-reforms', 'The Cluniac Reforms', 950, 1130, '#f57c00', NULL),
  ('era-scholastics', 'Scholastics & Monastics', 1000, 1300, '#c2185b', NULL),
  ('era-proto-reformers', 'Proto-Reformers & Mystics', 1300, 1500, '#5d4037', NULL),
  ('era-reformers', 'Reformers & Humanists', 1500, 1650, '#0097a7', NULL),
  ('era-dissent-discovery', 'Dissent & Discovery', 1650, 1800, '#7c4dff', NULL)
ON CONFLICT DO NOTHING;

-- ── CH_People ──────────────────────────────────────────────────────────
INSERT INTO public."CH_People" (person_id, name, birth_date, death_date, birth_year, death_year, location, role_type, era_id, is_emperor) VALUES
  ('jesus', 'Jesus', '-0003-01-01', '0033-01-01', -3, 33, 'Judea', 'person', 'era-apostolic', false),
  ('john-evangelist', 'John the Evangelist', '0006-01-01', '0100-01-01', 6, 100, 'Ephesus', 'person', 'era-apostolic', false),
  ('paul', 'Paul', '0005-01-01', '0065-01-01', 5, 65, 'Asia Minor', 'person', 'era-apostolic', false),
  ('peter', 'Peter', '0001-01-01', '0066-01-01', 1, 66, 'Rome', 'person', 'era-apostolic', false),
  ('papias', 'Papias of Hieropolis', '0060-01-01', '0130-01-01', 60, 130, 'Hierapolis', 'person', 'era-apostolic', false),
  ('clement-rome', 'Clement of Rome', '0035-01-01', '0099-01-01', 35, 99, 'Rome', 'person', 'era-apostolic', false),
  ('ignatius-antioch', 'Ignatius of Antioch', '0035-01-01', '0107-01-01', 35, 107, 'Antioch', 'person', 'era-apostolic', false),
  ('polycarp', 'Polycarp', '0069-01-01', '0155-01-01', 69, 155, 'Smyrna', 'person', 'era-apostolic', false),
  ('justin-martyr', 'Justin Martyr', '0100-01-01', '0165-01-01', 100, 165, 'Rome', 'person', 'era-ante-nicene', false),
  ('clement-alexandria', 'Clement of Alexandria', '0150-01-01', '0215-01-01', 150, 215, 'Alexandria', 'person', 'era-ante-nicene', false),
  ('tatians', 'Tatian', '0120-01-01', '0180-01-01', 120, 180, 'Rome', 'person', 'era-ante-nicene', false),
  ('irenaeus', 'Irenaeus of Lyons', '0130-01-01', '0202-01-01', 130, 202, 'Lyons, Gaul', 'person', 'era-ante-nicene', false),
  ('tertullian', 'Tertullian', '0155-01-01', '0240-01-01', 155, 240, 'Carthage', 'person', 'era-ante-nicene', false),
  ('hippolytus', 'Hippolytus of Rome', '0170-01-01', '0235-01-01', 170, 235, 'Rome', 'person', 'era-ante-nicene', false),
  ('perpetua', 'Perpetua', '0185-01-01', '0203-01-01', 185, 203, 'Carthage', 'person', 'era-ante-nicene', false),
  ('origen', 'Origen', '0185-01-01', '0254-01-01', 185, 254, 'Alexandria', 'person', 'era-ante-nicene', false),
  ('gregory-thaumaturgus', 'Gregory Thaumaturgus', '0213-01-01', '0270-01-01', 213, 270, 'Neocaesarea, Pontus', 'person', 'era-ante-nicene', false),
  ('dionysius-alexandria', 'Dionysius of Alexandria', '0210-01-01', '0264-01-01', 210, 264, 'Alexandria', 'person', 'era-ante-nicene', false),
  ('cyprian', 'Cyprian', '0210-01-01', '0258-01-01', 210, 258, 'Carthage', 'person', 'era-ante-nicene', false),
  ('anthony-great', 'Anthony the Great', '0251-01-01', '0356-01-01', 251, 356, 'Egyptian Desert', 'person', 'era-ante-nicene', false),
  ('lucian-antioch', 'Lucian of Antioch', '0250-01-01', '0312-01-01', 250, 312, 'Antioch', 'person', 'era-ante-nicene', false),
  ('alexander-alexandria', 'Alexander of Alexandria', '0280-01-01', '0328-01-01', 280, 328, 'Alexandria', 'person', 'era-ante-nicene', false),
  ('athanasius', 'Athanasius', '0296-01-01', '0373-01-01', 296, 373, 'Alexandria', 'person', 'era-ante-nicene', false),
  ('macrina-younger', 'Macrina the Younger', '0327-01-01', '0379-07-19', 327, 379, 'Cappadocia / Pontus', 'person', 'era-first-four-councils', false),
  ('basil-great', 'Basil the Great', '0330-01-01', '0379-01-01', 330, 379, 'Caesarea, Cappadocia', 'person', 'era-first-four-councils', false),
  ('gregory-nazianzus', 'Gregory of Nazianzus', '0330-01-01', '0389-01-01', 330, 389, 'Arianzus, Cappadocia', 'person', 'era-first-four-councils', false),
  ('gregory-nyssa', 'Gregory of Nyssa', '0335-01-01', '0395-01-01', 335, 395, 'Nyssa, Cappadocia', 'person', 'era-first-four-councils', false),
  ('ambrose-milan', 'Ambrose of Milan', '0339-01-01', '0397-01-01', 339, 397, 'Milan', 'person', 'era-first-four-councils', false),
  ('jerome', 'Jerome', '0347-01-01', '0420-01-01', 347, 420, 'Bethlehem', 'person', 'era-first-four-councils', false),
  ('john-chrysostom', 'John Chrysostom', '0349-01-01', '0407-01-01', 349, 407, 'Constantinople', 'person', 'era-first-four-councils', false),
  ('arsenius-great', 'Arsenius the Great', '0350-01-01', '0445-01-01', 350, 445, 'Egyptian Desert', 'person', 'era-first-four-councils', false),
  ('augustine', 'Augustine of Hippo', '0354-01-01', '0430-01-01', 354, 430, 'Hippo Regius', 'person', 'era-first-four-councils', false),
  ('didymus-blind', 'Didymus the Blind', '0313-01-01', '0398-01-01', 313, 398, 'Alexandria', 'person', 'era-ante-nicene', false),
  ('rufinus-aquileia', 'Rufinus of Aquileia', '0345-01-01', '0411-01-01', 345, 411, 'Aquileia / Sicily', 'person', 'era-first-four-councils', false),
  ('olympias', 'Olympias the Deaconess', '0365-01-01', '0408-07-25', 365, 408, 'Constantinople / Nicomedia', 'person', 'era-first-four-councils', false),
  ('theophilus-alexandria', 'Theophilus of Alexandria', '0355-01-01', '0412-10-15', 355, 412, 'Alexandria', 'person', 'era-first-four-councils', false),
  ('cyril-alexandria', 'Cyril of Alexandria', '0376-01-01', '0444-01-01', 376, 444, 'Alexandria', 'person', 'era-first-four-councils', false),
  ('patrick', 'Patrick', '0385-01-01', '0461-01-01', 385, 461, 'Ireland', 'person', 'era-first-four-councils', false),
  ('prosper-aquitaine', 'Prosper of Aquitaine', '0390-01-01', '0455-01-01', 390, 455, 'Aquitaine', 'person', 'era-first-four-councils', false),
  ('pope-leo-1', 'Pope Leo I', '0400-01-01', '0461-01-01', 400, 461, 'Rome', 'person', 'era-first-four-councils', false),
  ('faustus-riez', 'Faustus of Riez', '0408-01-01', '0490-01-01', 408, 490, 'Riez, Gaul', 'person', 'era-first-four-councils', false),
  ('claudianus-mamertus', 'Claudianus Mamertus', '0430-01-01', '0473-01-01', 430, 473, 'Vienne, Gaul', 'person', 'era-first-four-councils', false),
  ('mamertus', 'Mamertus', '0425-01-01', '0475-01-01', 425, 475, 'Vienne, Gaul', 'person', 'era-first-four-councils', false),
  ('lucidus', 'Lucidus', '0425-01-01', '0485-01-01', 425, 485, 'Gaul', 'person', 'era-first-four-councils', false),
  ('pope-simplicius', 'Pope Simplicius', '0430-01-01', '0483-01-01', 430, 483, 'Rome', 'person', 'era-first-four-councils', false),
  ('benedict-nursia', 'Benedict of Nursia', '0480-01-01', '0547-01-01', 480, 547, 'Monte Cassino', 'person', 'era-monks-missionaries', false),
  ('caesarius-arles', 'Caesarius of Arles', '0468-01-01', '0542-01-01', 468, 542, 'Arles, Gaul', 'person', 'era-monks-missionaries', false),
  ('columba', 'Columba', '0521-01-01', '0597-01-01', 521, 597, 'Iona', 'person', 'era-monks-missionaries', false),
  ('pope-gregory-great', 'Pope Gregory the Great', '0540-01-01', '0604-01-01', 540, 604, 'Rome', 'person', 'era-monks-missionaries', false),
  ('isidore-seville', 'Isidore of Seville', '0560-01-01', '0636-01-01', 560, 636, 'Seville', 'person', 'era-monks-missionaries', false),
  ('maximus-confessor', 'Maximus the Confessor', '0580-01-01', '0662-01-01', 580, 662, 'Constantinople', 'person', 'era-monks-missionaries', false),
  ('eligius', 'Eligius', '0588-01-01', '0660-01-01', 588, 660, 'Noyon, Gaul', 'person', 'era-monks-missionaries', false),
  ('audoin', 'Audoin', '0610-01-01', '0684-01-01', 610, 684, 'Rouen, Gaul', 'person', 'era-monks-missionaries', false),
  ('hilda-whitby', 'Hilda of Whitby', '0614-01-01', '0680-01-01', 614, 680, 'Whitby, England', 'person', 'era-monks-missionaries', false),
  ('gertrude-nivelles', 'Gertrude of Nivelles', '0628-01-01', '0659-01-01', 628, 659, 'Nivelles, Belgium', 'person', 'era-monks-missionaries', false),
  ('willibrord', 'Willibrord', '0658-01-01', '0739-01-01', 658, 739, 'Utrecht, Frisia', 'person', 'era-monks-missionaries', false),
  ('boniface', 'Boniface', '0675-01-01', '0754-01-01', 675, 754, 'Mainz, Germania', 'person', 'era-monks-missionaries', false),
  ('bede', 'The Venerable Bede', '0673-01-01', '0735-01-01', 673, 735, 'Jarrow, England', 'person', 'era-monks-missionaries', false),
  ('beatus-liebana', 'Beatus of Liebana', '0730-01-01', '0786-01-01', 730, 786, 'Liébana, Spain', 'person', 'era-monks-missionaries', false),
  ('paulinus-aquileia', 'Paulinus II of Aquileia', '0726-01-01', '0802-01-01', 726, 802, 'Aquileia, Italy', 'person', 'era-monks-missionaries', false),
  ('alcuin-york', 'Alcuin of York', '0735-01-01', '0804-01-01', 735, 804, 'Tours, Francia', 'person', 'era-monks-missionaries', false),
  ('rabanus-maurus', 'Rabanus Maurus', '0780-01-01', '0856-01-01', 780, 856, 'Mainz, Germania', 'person', 'era-monks-missionaries', false),
  ('kassia-byzantium', 'Kassia of Byzantium', '0800-01-01', '0843-01-01', 800, 843, 'Constantinople', 'person', 'era-monks-missionaries', false),
  ('john-scotus-eriugena', 'John Scotus Eriugena', '0800-01-01', '0877-01-01', 800, 877, 'Francia', 'person', 'era-monks-missionaries', false),
  ('photios-constantinople', 'Photios I of Constantinople', '0810-01-01', '0893-01-01', 810, 893, 'Constantinople', 'person', 'era-monks-missionaries', false),
  ('dhuoda-uzes', 'Dhuoda of Uzes', '0810-01-01', '0844-01-01', 810, 844, 'Uzès, Francia', 'person', 'era-monks-missionaries', false),
  ('cyril-methodius', 'Cyril and Methodius', '0815-01-01', '0885-01-01', 815, 885, 'Moravia', 'person', 'era-monks-missionaries', false),
  ('remigius-auxerre', 'Remigius of Auxerre', '0841-01-01', '0908-01-01', 841, 908, 'Auxerre, Francia', 'person', 'era-monks-missionaries', false),
  ('odo-cluny', 'Odo of Cluny', '0878-01-01', '0942-01-01', 878, 942, 'Cluny, Burgundy', 'person', 'era-monks-missionaries', false),
  ('dunstan', 'Dunstan', '0909-01-01', '0988-01-01', 909, 988, 'Canterbury, England', 'person', 'era-monks-missionaries', false),
  ('sylvester-ii', 'Sylvester II / Gerbert of Aurillac', '0946-01-01', '1003-01-01', 946, 1003, 'Rome', 'person', 'era-monks-missionaries', false),
  ('oswald-worcester', 'Oswald of Worcester', '0945-01-01', '0992-01-01', 945, 992, 'Worcester, England', 'person', 'era-monks-missionaries', false),
  ('adalbert-prague', 'Adalbert of Prague', '0956-01-01', '0997-01-01', 956, 997, 'Prague, Bohemia', 'person', 'era-monks-missionaries', false),
  ('herluin-bec', 'Herluin of Bec', '0995-01-01', '1078-01-01', 995, 1078, 'Bec, Normandy', 'person', 'era-monks-missionaries', false),
  ('lanfranc', 'Lanfranc', '1007-01-01', '1089-01-01', 1007, 1089, 'Canterbury, England', 'person', 'era-scholastics', false),
  ('anselm', 'Anselm', '1033-01-01', '1109-01-01', 1033, 1109, 'Canterbury, England', 'person', 'era-scholastics', false),
  ('anselm-laon', 'Anselm of Laon', '1045-01-01', '1117-01-01', 1045, 1117, 'Laon, France', 'person', 'era-scholastics', false),
  ('hildegard-bingen', 'Hildegard of Bingen', '1098-01-01', '1179-01-01', 1098, 1179, 'Bingen, Germany', 'person', 'era-scholastics', false),
  ('bernard-clairvaux', 'Bernard of Clairvaux', '1090-01-01', '1153-01-01', 1090, 1153, 'Clairvaux, France', 'person', 'era-scholastics', false),
  ('peter-waldo', 'Peter Waldo', '1140-01-01', '1205-01-01', 1140, 1205, 'Lyon, France', 'person', 'era-scholastics', false),
  ('william-auxerre', 'William of Auxerre', '1150-01-01', '1231-01-01', 1150, 1231, 'Paris, France', 'person', 'era-scholastics', false),
  ('dominich', 'Dominic', '1172-01-01', '1221-01-01', 1172, 1221, 'Bologna, Italy', 'person', 'era-scholastics', false),
  ('francis-assisi', 'Francis of Assisi', '1182-01-01', '1226-01-01', 1182, 1226, 'Assisi, Italy', 'person', 'era-scholastics', false),
  ('robert-grosseteste', 'Robert Grosseteste', '1175-01-01', '1253-01-01', 1175, 1253, 'Lincoln, England', 'person', 'era-scholastics', false),
  ('nicephorus-blemmydes', 'Nicephorus Blemmydes', '1197-01-01', '1272-01-01', 1197, 1272, 'Nicaea, Byzantine Empire', 'person', 'era-scholastics', false),
  ('william-moerbeke', 'William of Moerbeke', '1215-01-01', '1286-01-01', 1215, 1286, 'Corinth, Greece', 'person', 'era-scholastics', false),
  ('thomas-aquinas', 'Thomas Aquinas', '1225-01-01', '1274-01-01', 1225, 1274, 'Naples, Italy', 'person', 'era-scholastics', false),
  ('duns-scotus', 'Duns Scotus', '1265-01-01', '1308-01-01', 1265, 1308, 'Oxford, England', 'person', 'era-scholastics', false),
  ('dante-alighieri', 'Dante Alighieri', '1265-01-01', '1321-01-01', 1265, 1321, 'Florence, Italy', 'person', 'era-scholastics', false),
  ('thomas-bradwardine', 'Thomas Bradwardine', '1300-01-01', '1349-01-01', 1300, 1349, 'Oxford, England', 'person', 'era-proto-reformers', false),
  ('john-wycliffe', 'John Wycliffe', '1330-01-01', '1384-01-01', 1330, 1384, 'Oxford, England', 'person', 'era-proto-reformers', false),
  ('julian-norwich', 'Julian of Norwich', '1343-01-01', '1416-01-01', 1343, 1416, 'Norwich, England', 'person', 'era-proto-reformers', false),
  ('christine-pisan', 'Christine de Pisan', '1364-01-01', '1430-01-01', 1364, 1430, 'Paris, France', 'person', 'era-proto-reformers', false),
  ('jan-hus', 'Jan Hus', '1369-01-01', '1415-01-01', 1369, 1415, 'Prague, Bohemia', 'person', 'era-proto-reformers', false),
  ('thomas-kempis', 'Thomas a Kempis', '1380-01-01', '1471-01-01', 1380, 1471, 'Zwolle, Netherlands', 'person', 'era-proto-reformers', false),
  ('nicholas-cusa', 'Nicholas of Cusa', '1401-01-01', '1464-01-01', 1401, 1464, 'Kues, Germany', 'person', 'era-proto-reformers', false),
  ('savonarola', 'Savonarola', '1452-01-01', '1498-01-01', 1452, 1498, 'Florence, Italy', 'person', 'era-proto-reformers', false),
  ('desiderius-erasmus', 'Desiderius Erasmus', '1466-01-01', '1536-01-01', 1466, 1536, 'Rotterdam, Netherlands', 'person', 'era-proto-reformers', false),
  ('nicholas-copernicus', 'Nicholas Copernicus', '1473-01-01', '1543-01-01', 1473, 1543, 'Frauenburg, Poland', 'person', 'era-proto-reformers', false),
  ('bartolome-las-casas', 'Bartolome de las Casas', '1474-01-01', '1566-01-01', 1474, 1566, 'Hispaniola', 'person', 'era-proto-reformers', false),
  ('thomas-more', 'Thomas More', '1478-01-01', '1535-01-01', 1478, 1535, 'London, England', 'person', 'era-proto-reformers', false),
  ('martin-luther', 'Martin Luther', '1483-01-01', '1546-01-01', 1483, 1546, 'Wittenberg, Germany', 'person', 'era-proto-reformers', false),
  ('huldrych-zwingli', 'Huldrych Zwingli', '1484-01-01', '1531-10-11', 1484, 1531, 'Zurich, Switzerland', 'person', 'era-proto-reformers', false),
  ('ignatius-loyola', 'Ignatius of Loyola', '1491-10-23', '1556-07-31', 1491, 1556, 'Rome', 'person', 'era-proto-reformers', false),
  ('peter-faber', 'Peter Faber', '1506-04-13', '1546-08-01', 1506, 1546, 'Paris / Rome', 'person', 'era-reformers', false),
  ('francis-xavier', 'Francis Xavier', '1506-04-07', '1552-12-03', 1506, 1552, 'India / Japan / China', 'person', 'era-reformers', false),
  ('john-calvin', 'John Calvin', '1509-01-01', '1564-01-01', 1509, 1564, 'Geneva, Switzerland', 'person', 'era-reformers', false),
  ('teresa-avila', 'Teresa of Avila', '1515-01-01', '1582-01-01', 1515, 1582, 'Ávila, Spain', 'person', 'era-reformers', false),
  ('john-cross', 'John of the Cross', '1542-01-01', '1591-01-01', 1542, 1591, 'Segovia, Spain', 'person', 'era-reformers', false),
  ('william-bradford', 'William Bradford', '1590-01-01', '1657-01-01', 1590, 1657, 'Plymouth, Massachusetts', 'person', 'era-reformers', false),
  ('john-owen', 'John Owen', '1616-01-01', '1683-01-01', 1616, 1683, 'Oxford, England', 'person', 'era-reformers', false),
  ('john-bunyan', 'John Bunyan', '1628-01-01', '1688-01-01', 1628, 1688, 'Bedford, England', 'person', 'era-reformers', false),
  ('thomas-traherne', 'Thomas Traherne', '1636-01-01', '1674-01-01', 1636, 1674, 'Herefordshire, England', 'person', 'era-reformers', false),
  ('isaac-newton', 'Sir Isaac Newton', '1642-01-01', '1727-01-01', 1642, 1727, 'Cambridge, England', 'person', 'era-reformers', false),
  ('charles-wesley', 'Charles Wesley', '1707-01-01', '1788-01-01', 1707, 1788, 'England', 'person', 'era-dissent-discovery', false),
  ('john-wesley', 'John Wesley', '1703-01-01', '1791-01-01', 1703, 1791, 'England', 'person', 'era-dissent-discovery', false),
  ('pope-damasus-1', 'Pope Damasus I', '0305-01-01', '0384-01-01', 305, 384, 'Rome', 'person', 'era-ante-nicene', false),
  ('monica', 'Monica of Hippo', '0331-01-01', '0387-01-01', 331, 387, 'North Africa', 'person', 'era-first-four-councils', false),
  ('alypius', 'Alypius of Thagaste', '0354-01-01', '0430-01-01', 354, 430, 'North Africa', 'person', 'era-first-four-councils', false),
  ('possidius', 'Possidius', '0350-01-01', '0437-01-01', 350, 437, 'Calama, Numidia', 'person', 'era-first-four-councils', false),
  ('pope-cornelius', 'Pope Cornelius', '0180-01-01', '0253-01-01', 180, 253, 'Rome', 'person', 'era-ante-nicene', false),
  ('pope-stephen-1', 'Pope Stephen I', '0200-01-01', '0257-01-01', 200, 257, 'Rome', 'person', 'era-ante-nicene', false),
  ('germanus-auxerre', 'Germanus of Auxerre', '0378-01-01', '0448-01-01', 378, 448, 'Auxerre, Gaul', 'person', 'era-first-four-councils', false),
  ('augustine-canterbury', 'Augustine of Canterbury', '0534-01-01', '0604-01-01', 534, 604, 'Canterbury', 'person', 'era-monks-missionaries', false),
  ('leander-seville', 'Leander of Seville', '0534-01-01', '0600-01-01', 534, 600, 'Seville', 'person', 'era-monks-missionaries', false),
  ('pope-martin-1', 'Pope Martin I', '0590-01-01', '0655-01-01', 590, 655, 'Rome', 'person', 'era-monks-missionaries', false),
  ('pope-gregory-ii', 'Pope Gregory II', '0669-01-01', '0731-01-01', 669, 731, 'Rome', 'person', 'era-monks-missionaries', false),
  ('charlemagne', 'Charlemagne', '0742-01-01', '0814-01-01', 742, 814, 'Aachen, Francia', 'person', 'era-monks-missionaries', false),
  ('peter-abelard', 'Peter Abelard', '1079-01-01', '1142-01-01', 1079, 1142, 'Paris, France', 'person', 'era-scholastics', false),
  ('pope-eugenius-iii', 'Pope Eugenius III', '1080-01-01', '1153-01-01', 1080, 1153, 'Rome', 'person', 'era-scholastics', false),
  ('clare-assisi', 'Clare of Assisi', '1194-01-01', '1253-01-01', 1194, 1253, 'Assisi, Italy', 'person', 'era-scholastics', false),
  ('bonaventure', 'Bonaventure', '1221-01-01', '1274-01-01', 1221, 1274, 'Paris, France', 'person', 'era-scholastics', false),
  ('pico-mirandola', 'Giovanni Pico della Mirandola', '1463-01-01', '1494-01-01', 1463, 1494, 'Florence, Italy', 'person', 'era-proto-reformers', false),
  ('philipp-melanchthon', 'Philipp Melanchthon', '1497-01-01', '1560-01-01', 1497, 1560, 'Wittenberg, Germany', 'person', 'era-proto-reformers', false),
  ('william-farel', 'William Farel', '1489-01-01', '1565-01-01', 1489, 1565, 'Geneva, Switzerland', 'person', 'era-proto-reformers', false),
  ('george-whitefield', 'George Whitefield', '1714-01-01', '1770-01-01', 1714, 1770, 'England', 'person', 'era-dissent-discovery', false),
  ('saturus', 'Saturus (martyr; companion of Perpetua)', '0170-01-01', '0203-01-01', 170, 203, 'Carthage', 'person', 'era-ante-nicene', false),
  ('callixtus-i', 'Pope Callixtus I', '0165-01-01', '0222-01-01', 165, 222, 'Rome', 'person', 'era-ante-nicene', false),
  ('flavian-constantinople', 'Flavian of Constantinople', '0381-01-01', '0449-01-01', 381, 449, 'Constantinople', 'person', 'era-first-four-councils', false),
  ('aeonius-arles', 'Aeonius of Arles', '0450-01-01', '0502-01-01', 450, 502, 'Arles, Gaul', 'person', 'era-first-four-councils', false),
  ('maurus', 'Saint Maurus', '0512-01-01', '0584-01-01', 512, 584, 'Italy', 'person', 'era-monks-missionaries', false),
  ('finnian-moville', 'Finnian of Moville', '0495-01-01', '0589-01-01', 495, 589, 'Ireland', 'person', 'era-monks-missionaries', false),
  ('caedmon', 'Caedmon', '0620-01-01', '0680-01-01', 620, 680, 'Northumbria, England', 'person', 'era-monks-missionaries', false),
  ('itta-metz', 'Itta of Metz', '0592-01-01', '0652-01-01', 592, 652, 'Frankish Kingdom', 'person', 'era-monks-missionaries', false),
  ('benedict-biscop', 'Benedict Biscop', '0628-01-01', '0689-01-01', 628, 689, 'Wearmouth, England', 'person', 'era-monks-missionaries', false),
  ('ceolfrith', 'Ceolfrith', '0642-01-01', '0716-01-01', 642, 716, 'Jarrow, England', 'person', 'era-monks-missionaries', false),
  ('eterius-osma', 'Eterius of Osma', '0750-01-01', '0800-01-01', 750, 800, 'Spain', 'person', 'era-monks-missionaries', false),
  ('hincmar-reims', 'Hincmar of Reims', '0806-01-01', '0882-01-01', 806, 882, 'Reims', 'person', 'era-monks-missionaries', false),
  ('berno-cluny', 'Berno of Cluny', '0850-01-01', '0927-01-01', 850, 927, 'Cluny, Burgundy', 'person', 'era-monks-missionaries', false),
  ('adalbero-reims', 'Adalbero of Reims', '0920-01-01', '0989-01-01', 920, 989, 'Reims', 'person', 'era-monks-missionaries', false),
  ('bruno-querfurt', 'Bruno of Querfurt', '0974-01-01', '1009-01-01', 974, 1009, 'Central/Eastern Europe', 'person', 'era-monks-missionaries', false),
  ('william-champeaux', 'William of Champeaux', '1070-01-01', '1121-01-01', 1070, 1121, 'Paris, France', 'person', 'era-scholastics', false),
  ('heloise', 'Heloise', '1100-01-01', '1164-01-01', 1100, 1164, 'Paris, France', 'person', 'era-scholastics', false),
  ('william-of-ware', 'William of Ware', '1275-01-01', '1305-01-01', 1275, 1305, 'England', 'person', 'era-scholastics', false),
  ('brunetto-latini', 'Brunetto Latini', '1220-01-01', '1294-01-01', 1220, 1294, 'Florence, Italy', 'person', 'era-scholastics', false),
  ('john-purvey', 'John Purvey', '1354-01-01', '1428-01-01', 1354, 1428, 'England', 'person', 'era-proto-reformers', false),
  ('margery-kempe', 'Margery Kempe', '1373-01-01', '1438-01-01', 1373, 1438, 'England', 'person', 'era-proto-reformers', false),
  ('florens-radewijns', 'Florens Radewijns', '1350-01-01', '1400-01-01', 1350, 1400, 'Deventer', 'person', 'era-proto-reformers', false),
  ('pope-eugenius-iv', 'Pope Eugenius IV', '1383-01-01', '1447-01-01', 1383, 1447, 'Rome', 'person', 'era-proto-reformers', false),
  ('tiedemann-giese', 'Tiedemann Giese', '1480-01-01', '1550-01-01', 1480, 1550, 'Prussia', 'person', 'era-proto-reformers', false),
  ('antonio-montesinos', 'Antonio de Montesinos', '1475-01-01', '1540-01-01', 1475, 1540, 'Hispaniola', 'person', 'era-proto-reformers', false),
  ('william-brewster', 'William Brewster', '1568-01-01', '1644-01-01', 1568, 1644, 'England / Plymouth', 'person', 'era-reformers', false),
  ('john-robinson', 'John Robinson (Separatist pastor)', '1576-01-01', '1625-01-01', 1576, 1625, 'Leiden', 'person', 'era-reformers', false),
  ('roman-augustus', 'Augustus', '-0030-01-01', '0014-01-01', -30, 14, 'Roman Empire', 'emperor', NULL, true),
  ('roman-tiberius', 'Tiberius', '0014-01-01', '0037-01-01', 14, 37, 'Roman Empire', 'emperor', NULL, true),
  ('roman-caligula', 'Caligula', '0037-01-01', '0041-01-01', 37, 41, 'Roman Empire', 'emperor', NULL, true),
  ('roman-claudius', 'Claudius', '0041-01-01', '0054-01-01', 41, 54, 'Roman Empire', 'emperor', NULL, true),
  ('roman-nero', 'Nero', '0054-01-01', '0068-01-01', 54, 68, 'Roman Empire', 'emperor', NULL, true),
  ('roman-galba-otho-vitellius', 'Galba, Otho & Aulus Vitellius', '0068-01-01', '0069-01-01', 68, 69, 'Roman Empire', 'emperor', NULL, true),
  ('roman-vespasian', 'Vespasian', '0069-01-01', '0079-01-01', 69, 79, 'Roman Empire', 'emperor', NULL, true),
  ('roman-titus', 'Titus', '0079-01-01', '0081-01-01', 79, 81, 'Roman Empire', 'emperor', NULL, true),
  ('roman-domitian', 'Domitian', '0081-01-01', '0096-01-01', 81, 96, 'Roman Empire', 'emperor', NULL, true),
  ('roman-nerva', 'Nerva', '0096-01-01', '0098-01-01', 96, 98, 'Roman Empire', 'emperor', NULL, true),
  ('roman-trajan', 'Trajan', '0098-01-01', '0117-01-01', 98, 117, 'Roman Empire', 'emperor', NULL, true),
  ('roman-hadrian', 'Hadrian', '0117-01-01', '0138-01-01', 117, 138, 'Roman Empire', 'emperor', NULL, true),
  ('roman-antoninus', 'Antoninus Pius', '0138-01-01', '0161-01-01', 138, 161, 'Roman Empire', 'emperor', NULL, true),
  ('roman-marcus-aurelius', 'Marcus Aurelius', '0161-01-01', '0180-01-01', 161, 180, 'Roman Empire', 'emperor', NULL, true),
  ('roman-commodus', 'Commodus', '0180-01-01', '0192-01-01', 180, 192, 'Roman Empire', 'emperor', NULL, true),
  ('roman-decius', 'Decius', '0249-01-01', '0251-01-01', 249, 251, 'Roman Empire', 'emperor', NULL, true),
  ('roman-diocletian-maximian', 'Diocletian/Maximian', '0284-01-01', '0305-01-01', 284, 305, 'Roman Empire', 'emperor', NULL, true),
  ('roman-constantine', 'Constantine', '0306-01-01', '0337-01-01', 306, 337, 'Roman Empire', 'emperor', NULL, true)
ON CONFLICT DO NOTHING;

-- ── CH_Events ──────────────────────────────────────────────────────────
INSERT INTO public."CH_Events" (event_id, name, event_type, event_date, end_date, location, description) VALUES
  ('council-nicaea', 'Council of Nicaea', 'council', '0325-01-01', NULL, 'Nicaea', NULL),
  ('council-constantinople-1', 'First Council of Constantinople', 'council', '0381-01-01', NULL, 'Constantinople', NULL),
  ('council-ephesus', 'Council of Ephesus', 'council', '0431-01-01', NULL, 'Ephesus', NULL),
  ('council-chalcedon', 'Council of Chalcedon', 'council', '0451-01-01', NULL, 'Chalcedon', NULL),
  ('council-frankfurt', 'Council (Synod) of Frankfurt', 'council', '0794-01-01', NULL, 'Frankfurt', NULL),
  ('doc-galatians', 'Paul''s letter to the Galatians', 'document', '0048-01-01', NULL, NULL, NULL),
  ('doc-philippians', 'Paul''s letter to the Philippians', 'document', '0062-01-01', NULL, NULL, NULL),
  ('doc-mark', 'Gospel of Mark completed', 'document', '0055-01-01', '0075-01-01', NULL, NULL),
  ('doc-clement-epistle', 'First epistle of Clement', 'document', '0096-01-01', NULL, NULL, NULL),
  ('doc-didache', 'The Didache composed', 'document', '0095-01-01', '0150-01-01', NULL, NULL),
  ('doc-john-fragment', 'Gospel of John fragment - P42', 'document', '0125-01-01', '0175-01-01', NULL, NULL),
  ('doc-pauline-p46', 'Pauline epistle fragment - P46', 'document', '0175-01-01', '0225-01-01', NULL, NULL),
  ('doc-muratorian', 'Muratorian Canon', 'document', '0170-01-01', NULL, NULL, NULL),
  ('doc-thomas-mentioned', 'Gospel of Thomas mentioned', 'document', '0230-01-01', NULL, NULL, NULL),
  ('doc-athanasius-canon', 'Athanasian canon', 'document', '0367-01-01', NULL, NULL, NULL),
  ('doc-book-kells', 'Book of Kells composed', 'document', '0800-01-01', NULL, NULL, NULL),
  ('event-rome-visigoths', 'Rome sacked by the Visigoths', 'event', '0410-01-01', NULL, 'Rome', NULL),
  ('event-west-empire-end', 'The end of the Western Roman Empire', 'event', '0476-01-01', NULL, 'Ravenna', NULL),
  ('event-east-west-schism', 'The Great East/West Schism', 'event', '1054-01-01', NULL, 'Constantinople', NULL),
  ('event-normans-england', 'Normans invade England', 'event', '1066-01-01', NULL, 'England', NULL),
  ('event-hussite-wars', 'The Hussite Wars', 'event', '1419-01-01', '1434-01-01', 'Bohemia', NULL),
  ('event-ottomans-constantinople', 'Constantinople taken by the Ottomans', 'event', '1453-01-01', NULL, 'Constantinople', NULL),
  ('event-diet-worms', 'Luther tried at the Diet of Worms', 'event', '1521-01-01', NULL, 'Worms, Germany', NULL)
ON CONFLICT DO NOTHING;

-- ── CH_Connections ─────────────────────────────────────────────────────
INSERT INTO public."CH_Connections" (person_id_1, person_id_2, connection_type) VALUES
  ('john-evangelist', 'polycarp', 'known'),
  ('john-evangelist', 'papias', 'known'),
  ('ignatius-antioch', 'polycarp', 'known'),
  ('papias', 'polycarp', 'known'),
  ('polycarp', 'irenaeus', 'known'),
  ('justin-martyr', 'tatians', 'known'),
  ('clement-alexandria', 'origen', 'known'),
  ('origen', 'gregory-thaumaturgus', 'known'),
  ('origen', 'dionysius-alexandria', 'known'),
  ('pope-cornelius', 'cyprian', 'known'),
  ('pope-stephen-1', 'cyprian', 'known'),
  ('alexander-alexandria', 'athanasius', 'known'),
  ('anthony-great', 'athanasius', 'known'),
  ('athanasius', 'basil-great', 'known'),
  ('macrina-younger', 'basil-great', 'known'),
  ('macrina-younger', 'gregory-nyssa', 'known'),
  ('basil-great', 'gregory-nazianzus', 'known'),
  ('basil-great', 'gregory-nyssa', 'known'),
  ('gregory-nazianzus', 'gregory-nyssa', 'known'),
  ('ambrose-milan', 'augustine', 'known'),
  ('pope-damasus-1', 'jerome', 'known'),
  ('didymus-blind', 'jerome', 'known'),
  ('didymus-blind', 'rufinus-aquileia', 'known'),
  ('jerome', 'rufinus-aquileia', 'known'),
  ('jerome', 'augustine', 'known'),
  ('monica', 'augustine', 'known'),
  ('augustine', 'alypius', 'known'),
  ('possidius', 'augustine', 'known'),
  ('john-chrysostom', 'olympias', 'known'),
  ('theophilus-alexandria', 'john-chrysostom', 'known'),
  ('germanus-auxerre', 'patrick', 'known'),
  ('pope-gregory-great', 'augustine-canterbury', 'known'),
  ('leander-seville', 'isidore-seville', 'known'),
  ('maximus-confessor', 'pope-martin-1', 'known'),
  ('pope-gregory-ii', 'boniface', 'known'),
  ('willibrord', 'boniface', 'known'),
  ('alcuin-york', 'charlemagne', 'known'),
  ('paulinus-aquileia', 'alcuin-york', 'known'),
  ('alcuin-york', 'rabanus-maurus', 'known'),
  ('photios-constantinople', 'cyril-methodius', 'known'),
  ('dunstan', 'oswald-worcester', 'known'),
  ('herluin-bec', 'lanfranc', 'known'),
  ('herluin-bec', 'anselm', 'known'),
  ('lanfranc', 'anselm', 'known'),
  ('bernard-clairvaux', 'hildegard-bingen', 'known'),
  ('pope-eugenius-iii', 'bernard-clairvaux', 'known'),
  ('pope-eugenius-iii', 'hildegard-bingen', 'known'),
  ('dominich', 'francis-assisi', 'known'),
  ('francis-assisi', 'clare-assisi', 'known'),
  ('william-moerbeke', 'thomas-aquinas', 'known'),
  ('bonaventure', 'thomas-aquinas', 'known'),
  ('savonarola', 'pico-mirandola', 'known'),
  ('desiderius-erasmus', 'thomas-more', 'known'),
  ('desiderius-erasmus', 'martin-luther', 'known'),
  ('martin-luther', 'philipp-melanchthon', 'known'),
  ('martin-luther', 'huldrych-zwingli', 'known'),
  ('william-farel', 'john-calvin', 'known'),
  ('ignatius-loyola', 'peter-faber', 'known'),
  ('ignatius-loyola', 'francis-xavier', 'known'),
  ('peter-faber', 'francis-xavier', 'known'),
  ('teresa-avila', 'john-cross', 'known'),
  ('john-owen', 'john-bunyan', 'known'),
  ('john-wesley', 'charles-wesley', 'known'),
  ('john-wesley', 'george-whitefield', 'known'),
  ('charles-wesley', 'george-whitefield', 'known'),
  ('saturus', 'perpetua', 'known'),
  ('callixtus-i', 'hippolytus', 'known'),
  ('augustine', 'prosper-aquitaine', 'known'),
  ('flavian-constantinople', 'pope-leo-1', 'known'),
  ('aeonius-arles', 'caesarius-arles', 'known'),
  ('benedict-nursia', 'maurus', 'known'),
  ('finnian-moville', 'columba', 'known'),
  ('hilda-whitby', 'caedmon', 'known'),
  ('itta-metz', 'gertrude-nivelles', 'known'),
  ('benedict-biscop', 'bede', 'known'),
  ('ceolfrith', 'bede', 'known'),
  ('eterius-osma', 'beatus-liebana', 'known'),
  ('hincmar-reims', 'john-scotus-eriugena', 'known'),
  ('berno-cluny', 'odo-cluny', 'known'),
  ('adalbero-reims', 'sylvester-ii', 'known'),
  ('adalbert-prague', 'bruno-querfurt', 'known'),
  ('anselm-laon', 'peter-abelard', 'known'),
  ('william-champeaux', 'peter-abelard', 'known'),
  ('peter-abelard', 'heloise', 'known'),
  ('william-of-ware', 'duns-scotus', 'known'),
  ('brunetto-latini', 'dante-alighieri', 'known'),
  ('john-wycliffe', 'john-purvey', 'known'),
  ('julian-norwich', 'margery-kempe', 'known'),
  ('florens-radewijns', 'thomas-kempis', 'known'),
  ('pope-eugenius-iv', 'nicholas-cusa', 'known'),
  ('tiedemann-giese', 'nicholas-copernicus', 'known'),
  ('antonio-montesinos', 'bartolome-las-casas', 'known'),
  ('william-brewster', 'william-bradford', 'known'),
  ('john-robinson', 'william-bradford', 'known')
ON CONFLICT DO NOTHING;

-- ── CH_Sources ─────────────────────────────────────────────────────────
INSERT INTO public."CH_Sources" (source_id, title, source_name, year, url, notes) VALUES
  ('src-irenaeus-ah-3-3', 'Irenaeus – Against Heresies 3.3 (succession list incl. Clement)', 'Early Christian Writings / ANF', '~180', 'https://www.earlychristianwritings.com/text/irenaeus-book3.html', 'Mentions Clement in apostolic succession tradition.'),
  ('src-tertullian-prescription-32', 'Tertullian – Prescription Against Heretics ch. 32 (Polycarp/John; Clement/Peter)', 'CCEL', '~200', 'https://www.ccel.org/ccel/schaff/anf03.v.iii.ii.xxxii.html', 'Names Polycarp as placed by John and Clement ordained by Peter (as recorded by churches).'),
  ('src-ignatius-to-polycarp', 'Ignatius – Epistle to Polycarp', 'New Advent (Church Fathers)', '~110', 'https://www.newadvent.org/fathers/0109.htm', 'Personal letter addressed to Polycarp.'),
  ('src-catholicculture-ignatius-polycarp', 'St. Ignatius of Antioch — Letter to Polycarp (commentary)', 'CatholicCulture.org', '2019', 'https://www.catholicculture.org/commentary/st-ignatius-antioch-letter-to-polycarp/', 'Commentary pointing to direct correspondence; also notes Polycarp’s role in transmitting Ignatius’ letters.'),
  ('src-newadvent-irenaeus-fragments', 'Irenaeus – Fragments (mentions Polycarp)', 'New Advent (Church Fathers)', NULL, 'https://www.newadvent.org/fathers/0134.htm', 'Primary/translation source for Irenaeus describing his connection to Polycarp.'),
  ('src-eusebius-eh-v-20', 'Eusebius – Ecclesiastical History V.20 (Irenaeus on Polycarp)', 'New Advent (Church Fathers)', '~325', 'https://www.newadvent.org/fathers/250105.htm', 'Preserves Irenaeus’ recollection of Polycarp.'),
  ('src-eusebius-papias', 'Eusebius on Papias as hearer of John and companion of Polycarp', 'CatholicLibrary.org', '~325', 'https://www.catholiclibrary.org/library/view?docId=Fathers-EN/eusebius_ChurchHistory.html', 'Traditional report tying Papias to John and Polycarp.'),
  ('src-dionysius-ce', 'Dionysius of Alexandria', 'New Advent (Catholic Encyclopedia)', '1909', 'https://www.newadvent.org/cathen/05011a.htm', 'Notes Dionysius studied under Origen.'),
  ('src-britannica-gregory-thaumaturgus', 'St. Gregory Thaumaturgus', 'Britannica', '2026', 'https://www.britannica.com/biography/Saint-Gregory-Thaumaturgus', 'Useful for dates + the Origen connection framing (as commonly presented).'),
  ('src-cna-gregory-thaumaturgus', 'St. Gregory Thaumaturgus (mentions meeting Origen & becoming his disciple)', 'Catholic News Agency', '2025', 'https://www.catholicnewsagency.com/resource/55582/st-gregory-thaumaturgus', 'Explicitly ties Gregory to Origen as disciple in the Caesarea narrative.'),
  ('src-cyprian-ep56', 'Cyprian – Epistle 56 (to Cornelius)', 'New Advent (Church Fathers)', '~252', 'https://www.newadvent.org/fathers/050656.htm', 'Direct correspondence.'),
  ('src-cyprian-to-pompey', 'Cyprian – To Pompey on baptism of heretics (context: dispute with Stephen)', 'Early Church Texts', '~256', 'https://earlychurchtexts.com/public/cyprian_to_pompey_on_heretical_baptism.htm', 'Primary letter in the rebaptism controversy.'),
  ('src-athanasius-ce', 'St. Athanasius (mentions service under Alexander)', 'New Advent (Catholic Encyclopedia)', '1907', 'https://www.newadvent.org/cathen/02035a.htm', 'Mentions Athanasius as deacon/assistant to Alexander.'),
  ('src-newadvent-basil-letter-66', 'Basil Letter 66 (to Athanasius)', 'New Advent (Church Fathers)', NULL, 'https://www.newadvent.org/fathers/3202066.htm', 'Concrete anchor for Basil ↔ Athanasius correspondence.'),
  ('src-basil-letters', 'Letters of Basil (collection; includes letters to Athanasius)', 'New Advent (Church Fathers)', '~370', 'https://www.newadvent.org/fathers/3202.htm', 'Epistolary relationship.'),
  ('src-oca-macrina-wiki', 'Macrina the Younger (siblings incl. Basil & Gregory of Nyssa)', 'Wikipedia', NULL, 'https://en.wikipedia.org/wiki/Macrina_the_Younger', 'Family/influence scaffold for Macrina ↔ Basil/Gregory of Nyssa.'),
  ('src-gregory-nyssa-fm', 'Gregory of Nyssa (raised by older brother Basil)', 'Franciscan Media', NULL, 'https://www.franciscanmedia.org/saint-of-the-day/saint-gregory-of-nyssa/', 'States Basil raised Gregory.'),
  ('src-confessions-book5', 'Augustine – Confessions Book V (encounter with Ambrose)', 'New Advent (Church Fathers)', '~400', 'https://www.newadvent.org/fathers/110105.htm', 'Primary narrative of Augustine’s relationship to Ambrose.'),
  ('src-confessions-book6', 'Augustine – Confessions Book VI (Monica & Alypius; Milan period)', 'New Advent (Church Fathers)', '~400', 'https://www.newadvent.org/fathers/110106.htm', 'Primary narrative of these relationships.'),
  ('src-possidius-vita', 'Possidius – Life of Augustine', 'Tertullian.org', '~430', 'https://www.tertullian.org/fathers/possidius_life_of_augustine_1_trans.htm', 'Biographer and close associate.'),
  ('src-jerome-britannica', 'St. Jerome (work under Damasus; biblical revision)', 'Britannica', NULL, 'https://www.britannica.com/biography/Saint-Jerome', 'Describes Jerome’s work for Damasus.'),
  ('src-wikipedia-didymus-blind', 'Didymus the Blind (overview; pupils incl. Jerome & Rufinus)', 'Wikipedia', NULL, 'https://en.wikipedia.org/wiki/Didymus_the_Blind', 'Convenient summary of pupil relationships; replace with stronger sources later if desired.'),
  ('src-newadvent-augustine-to-jerome', 'Augustine Letter 82 / Jerome 116 (Augustine → Jerome)', 'New Advent (Church Fathers)', NULL, 'https://www.newadvent.org/fathers/1102082.htm', 'Direct evidence of Augustine–Jerome correspondence (one example).'),
  ('src-svspress-letters-olympia', 'St John Chrysostom: Letters to Saint Olympia (ed./trans.)', 'SVS Press', '2022', 'https://svspress.com/saint-john-chrysostom-letters-to-saint-olympia/', 'Published collection attesting the correspondence/spiritual direction relationship.'),
  ('src-newadvent-theophilus', 'Theophilus of Alexandria', 'New Advent (Catholic Encyclopedia)', NULL, 'https://www.newadvent.org/cathen/14625b.htm', 'Covers Theophilus’ involvement in the Chrysostom controversy (incl. deposition).'),
  ('src-newadvent-council-ephesus', 'Council of Ephesus (A.D. 431) documents incl. Cyril letters re: Nestorius)', 'New Advent (Church Fathers)', NULL, 'https://www.newadvent.org/fathers/3810.htm', 'Primary/translation material for the Cyril–Nestorius conflict context.'),
  ('src-gregory-mission-chi', 'Gregory sends Augustine to evangelize England', 'Christian History Institute', NULL, 'https://christianhistoryinstitute.org/study/module/gregory-the-great-evangelizes-england', 'Narrative of mission and letters.'),
  ('src-maximus-oca', 'St. Maximus the Confessor (with Pope Martin)', 'OCA', NULL, 'https://www.oca.org/saints/lives/2024/01/21/100271-venerable-maximus-the-confessor', 'Notes collaboration in anti-Monothelite struggle.'),
  ('src-boniface-ce', 'St. Boniface (work with Willibrord; commission by Gregory II)', 'New Advent (Catholic Encyclopedia)', '1907', 'https://www.newadvent.org/cathen/02656a.htm', 'Describes collaboration and papal commissioning.'),
  ('src-alcuin-britannica', 'Alcuin (adviser to Charlemagne)', 'Britannica', NULL, 'https://www.britannica.com/biography/Alcuin', 'Court relationship.'),
  ('src-rabanus-britannica', 'Rabanus Maurus (student of Alcuin)', 'Britannica', NULL, 'https://www.britannica.com/biography/Rabanus-Maurus', 'Teacher-student.'),
  ('src-photios-oca', 'St. Photius (missions involving Cyril & Methodius)', 'OCA', NULL, 'https://www.oca.org/saints/lives/2024/02/06/100427-saint-photius-the-great-patriarch-of-constantinople', 'Mentions Photius guiding missions involving Cyril & Methodius.'),
  ('src-eugenius-newadvent', 'Pope Eugenius III (disciple of Bernard)', 'New Advent (Catholic Encyclopedia)', '1909', 'https://www.newadvent.org/cathen/05599a.htm', 'Describes the disciple relationship and Bernard’s letters.'),
  ('src-poor-clares-britannica', 'Poor Clares (cofounded by Clare and Francis)', 'Britannica', NULL, 'https://www.britannica.com/topic/Poor-Clares', 'States cofounded order.'),
  ('src-moerbeke-pims', 'William of Moerbeke and translation activity (Aquinas circle)', 'PIMS', NULL, 'https://pims.ca/wp-content/uploads/2017/02/Moerbeke-translation.pdf', 'Translator relationship (mechanics vary by scholarly account).'),
  ('src-pico-sep', 'Giovanni Pico della Mirandola', 'Stanford Encyclopedia of Philosophy', NULL, 'https://plato.stanford.edu/entries/pico-della-mirandola/', 'Notes Pico’s late-life turn toward Savonarola’s influence.'),
  ('src-erasmus-more-letter', 'Erasmus letter to Thomas More (preface to Praise of Folly)', 'OurCivilisation.com', '1509', 'https://www.ourcivilisation.com/smartboard/shop/erasmus/moore.htm', 'Primary evidence of friendship.'),
  ('src-lutheranreformation-marburg', 'The Marburg Colloquy (Oct 1–4, 1529)', 'LutheranReformation.org', '2017', 'https://lutheranreformation.org/history/the-marburg-colloquy/', 'Summary of the Luther–Zwingli encounter and dispute over the Lord’s Supper.'),
  ('src-calvin-farel-ligonier', 'William Farel (persuaded Calvin to stay in Geneva)', 'Ligonier', NULL, 'https://www.ligonier.org/learn/articles/william-farel', 'Narrative of decisive collaboration.'),
  ('src-melanchthon-britannica', 'Philipp Melanchthon (partnership with Luther)', 'Britannica', NULL, 'https://www.britannica.com/biography/Philipp-Melanchthon', 'Mentions partnership.'),
  ('src-scu-roommates-paris', 'Three Roommates in Paris', 'Santa Clara Magazine', '2006', 'https://magazine.scu.edu/magazines/summer-2006/three-roommates-in-paris/', 'Roommates at Paris (Ignatius, Xavier, Favre); early relationship context.'),
  ('src-jesuits-xavier', 'Heroes of the Ignatian Tradition: Francis Xavier', 'Jesuits.org', NULL, 'https://www.jesuits.org/stories/heroes-of-the-ignatian-tradition-francis-xavier/', 'States they met at the University of Paris; links friendship to early Jesuit founding.'),
  ('src-teresa-john-cross-aleteia', 'Teresa of Avila and John of the Cross reform collaboration', 'Aleteia', NULL, 'https://aleteia.org/2018/12/14/teresa-of-avila-and-john-of-the-cross-a-very-thorny-friendship/', 'Collaboration within Carmelite reform.'),
  ('src-ccel-perpetua', 'The Passion of Perpetua and Felicity (includes Saturus)', 'CCEL', NULL, 'https://www.ccel.org/ccel/pearse/morefathers/files/perpetua.htm', 'Primary narrative includes Perpetua’s martyr-companions, including Saturus.'),
  ('src-wikipedia-hippolytus', 'Hippolytus of Rome (conflict context with Callixtus)', 'Wikipedia', NULL, 'https://en.wikipedia.org/wiki/Hippolytus_of_Rome', 'Commonly summarized direct conflict (complicated but clearly connected).'),
  ('src-wikipedia-prosper', 'Prosper of Aquitaine (Augustinian disciple/ally)', 'Wikipedia', NULL, 'https://en.wikipedia.org/wiki/Prosper_of_Aquitaine', 'Often presented as an Augustinian ally; relationship is ‘disciple/circle’ more than face-to-face proof.'),
  ('src-wikipedia-tome-leo', 'Tome of Leo (letter to Flavian)', 'Wikipedia', NULL, 'https://en.wikipedia.org/wiki/Tome_of_Leo', 'Direct relationship: Leo’s doctrinal letter addressed to Flavian.'),
  ('src-wikipedia-caesarius', 'Caesarius of Arles (ordination/advancement under Aeonius)', 'Wikipedia', NULL, 'https://en.wikipedia.org/wiki/Caesarius_of_Arles', 'Often summarized as Aeonius promoting/ordaining Caesarius.'),
  ('src-wikipedia-maurus', 'Maurus (disciple in Benedictine tradition)', 'Wikipedia', NULL, 'https://en.wikipedia.org/wiki/Maurus', 'Hagiographical but classic monastic lineage: Benedict → Maurus.'),
  ('src-wikipedia-columba', 'Columba (traditions about Finnian as teacher)', 'Wikipedia', NULL, 'https://en.wikipedia.org/wiki/Columba', 'Traditional teacher-student link in Irish monastic biographies.'),
  ('src-fordham-bede-caedmon', 'Bede, Ecclesiastical History IV.24 (Caedmon at Whitby)', 'Fordham Medieval Sourcebook', NULL, 'https://sourcebooks.fordham.edu/basis/bede-book4.asp', 'Primary narrative anchor for Hilda–Caedmon.'),
  ('src-wikipedia-gertrude', 'Gertrude of Nivelles (daughter of Itta)', 'Wikipedia', NULL, 'https://en.wikipedia.org/wiki/Gertrude_of_Nivelles', 'Mother–daughter relationship.'),
  ('src-wikipedia-bede', 'Bede (formation under Benedict Biscop and Ceolfrith)', 'Wikipedia', NULL, 'https://en.wikipedia.org/wiki/Bede', 'Common biographical summary of formative relationships.'),
  ('src-wikipedia-beatus', 'Beatus of Liébana (collaboration with Eterius)', 'Wikipedia', NULL, 'https://en.wikipedia.org/wiki/Beatus_of_Li%C3%A9bana', 'Commonly presented as collaborator/co-author with Eterius.'),
  ('src-wikipedia-eriugena', 'John Scotus Eriugena (predestination controversy; Hincmar context)', 'Wikipedia', NULL, 'https://en.wikipedia.org/wiki/John_Scotus_Eriugena', 'Often summarized as Eriugena writing into Hincmar’s ecclesial controversy context.'),
  ('src-wikipedia-odo', 'Odo of Cluny (formation / relationship to Berno)', 'Wikipedia', NULL, 'https://en.wikipedia.org/wiki/Odo_of_Cluny', 'Monastic succession/formation within Cluny.'),
  ('src-wikipedia-sylvester-ii', 'Pope Sylvester II (Gerbert; education under Adalbero)', 'Wikipedia', NULL, 'https://en.wikipedia.org/wiki/Pope_Sylvester_II', 'Commonly reported formative relationship.'),
  ('src-wikipedia-bruno-querfurt', 'Bruno of Querfurt (missionary; association with Adalbert of Prague)', 'Wikipedia', NULL, 'https://en.wikipedia.org/wiki/Bruno_of_Querfurt', 'Missionary/hagiographic lineage connection to Adalbert.'),
  ('src-wikipedia-abelard', 'Peter Abelard (teachers and relationship with Heloise)', 'Wikipedia', NULL, 'https://en.wikipedia.org/wiki/Peter_Abelard', 'Single stable summary for Abelard’s teacher-chain and Heloise.'),
  ('src-wikipedia-scotus', 'John Duns Scotus (linked to William of Ware)', 'Wikipedia', NULL, 'https://en.wikipedia.org/wiki/Duns_Scotus', 'Often given as a formative teacher relationship.'),
  ('src-wikipedia-dante', 'Dante (teacher Brunetto Latini)', 'Wikipedia', NULL, 'https://en.wikipedia.org/wiki/Dante_Alighieri', 'Commonly reported teacher relationship.'),
  ('src-wikipedia-purvey', 'John Purvey (associate/disciple in Wycliffite circle)', 'Wikipedia', NULL, 'https://en.wikipedia.org/wiki/John_Purvey', 'Direct ‘disciple/associate’ framing in Wycliffite movement history.'),
  ('src-wikipedia-julian', 'Julian of Norwich (visited by Margery Kempe)', 'Wikipedia', NULL, 'https://en.wikipedia.org/wiki/Julian_of_Norwich', 'Direct visit relationship (via Kempe’s account/tradition).'),
  ('src-wikipedia-kempis', 'Thomas à Kempis (Devotio Moderna; Florens Radewijns)', 'Wikipedia', NULL, 'https://en.wikipedia.org/wiki/Thomas_%C3%A0_Kempis', 'Commonly reported formative relationship within Devotio Moderna.'),
  ('src-wikipedia-cusa', 'Nicholas of Cusa (papal service under Eugenius IV)', 'Wikipedia', NULL, 'https://en.wikipedia.org/wiki/Nicholas_of_Cusa', 'Clear ecclesial service relationship.'),
  ('src-wikipedia-copernicus', 'Copernicus (friend/bishop Tiedemann Giese)', 'Wikipedia', NULL, 'https://en.wikipedia.org/wiki/Nicolaus_Copernicus', 'Often described as a close friend and supporter within the Church context.'),
  ('src-wikipedia-montesinos', 'Antonio de Montesinos (influence on Las Casas)', 'Wikipedia', NULL, 'https://en.wikipedia.org/wiki/Antonio_de_Montesinos', 'Commonly credited as a pivotal influence on Las Casas.'),
  ('src-wikipedia-bradford', 'William Bradford (Robinson/Brewster as formative leaders)', 'Wikipedia', NULL, 'https://en.wikipedia.org/wiki/William_Bradford_(Plymouth_Colony)', 'Common biographical summary of ecclesial leadership relationships.')
ON CONFLICT DO NOTHING;

-- ── CH_Source_Figures ──────────────────────────────────────────────────
INSERT INTO public."CH_Source_Figures" (source_id, person_id, event_id) VALUES
  ('src-irenaeus-ah-3-3', 'peter', NULL),
  ('src-irenaeus-ah-3-3', 'clement-rome', NULL),
  ('src-tertullian-prescription-32', 'john-evangelist', NULL),
  ('src-tertullian-prescription-32', 'polycarp', NULL),
  ('src-tertullian-prescription-32', 'peter', NULL),
  ('src-tertullian-prescription-32', 'clement-rome', NULL),
  ('src-ignatius-to-polycarp', 'ignatius-antioch', NULL),
  ('src-ignatius-to-polycarp', 'polycarp', NULL),
  ('src-catholicculture-ignatius-polycarp', 'ignatius-antioch', NULL),
  ('src-catholicculture-ignatius-polycarp', 'polycarp', NULL),
  ('src-newadvent-irenaeus-fragments', 'polycarp', NULL),
  ('src-newadvent-irenaeus-fragments', 'irenaeus', NULL),
  ('src-eusebius-eh-v-20', 'polycarp', NULL),
  ('src-eusebius-eh-v-20', 'irenaeus', NULL),
  ('src-eusebius-papias', 'john-evangelist', NULL),
  ('src-eusebius-papias', 'papias', NULL),
  ('src-eusebius-papias', 'polycarp', NULL),
  ('src-dionysius-ce', 'origen', NULL),
  ('src-dionysius-ce', 'dionysius-alexandria', NULL),
  ('src-britannica-gregory-thaumaturgus', 'origen', NULL),
  ('src-britannica-gregory-thaumaturgus', 'gregory-thaumaturgus', NULL),
  ('src-cna-gregory-thaumaturgus', 'origen', NULL),
  ('src-cna-gregory-thaumaturgus', 'gregory-thaumaturgus', NULL),
  ('src-cyprian-ep56', 'cyprian', NULL),
  ('src-cyprian-ep56', 'pope-cornelius', NULL),
  ('src-cyprian-to-pompey', 'cyprian', NULL),
  ('src-cyprian-to-pompey', 'pope-stephen-1', NULL),
  ('src-athanasius-ce', 'alexander-alexandria', NULL),
  ('src-athanasius-ce', 'athanasius', NULL),
  ('src-newadvent-basil-letter-66', 'basil-great', NULL),
  ('src-newadvent-basil-letter-66', 'athanasius', NULL),
  ('src-basil-letters', 'basil-great', NULL),
  ('src-basil-letters', 'athanasius', NULL),
  ('src-oca-macrina-wiki', 'macrina-younger', NULL),
  ('src-oca-macrina-wiki', 'basil-great', NULL),
  ('src-oca-macrina-wiki', 'gregory-nyssa', NULL),
  ('src-gregory-nyssa-fm', 'basil-great', NULL),
  ('src-gregory-nyssa-fm', 'gregory-nyssa', NULL),
  ('src-confessions-book5', 'ambrose-milan', NULL),
  ('src-confessions-book5', 'augustine', NULL),
  ('src-confessions-book6', 'augustine', NULL),
  ('src-confessions-book6', 'monica', NULL),
  ('src-confessions-book6', 'alypius', NULL),
  ('src-possidius-vita', 'possidius', NULL),
  ('src-possidius-vita', 'augustine', NULL),
  ('src-jerome-britannica', 'pope-damasus-1', NULL),
  ('src-jerome-britannica', 'jerome', NULL),
  ('src-wikipedia-didymus-blind', 'didymus-blind', NULL),
  ('src-wikipedia-didymus-blind', 'jerome', NULL),
  ('src-wikipedia-didymus-blind', 'rufinus-aquileia', NULL),
  ('src-newadvent-augustine-to-jerome', 'augustine', NULL),
  ('src-newadvent-augustine-to-jerome', 'jerome', NULL),
  ('src-svspress-letters-olympia', 'john-chrysostom', NULL),
  ('src-svspress-letters-olympia', 'olympias', NULL),
  ('src-newadvent-theophilus', 'theophilus-alexandria', NULL),
  ('src-newadvent-theophilus', 'john-chrysostom', NULL),
  ('src-newadvent-council-ephesus', 'cyril-alexandria', NULL),
  ('src-gregory-mission-chi', 'pope-gregory-great', NULL),
  ('src-gregory-mission-chi', 'augustine-canterbury', NULL),
  ('src-maximus-oca', 'maximus-confessor', NULL),
  ('src-maximus-oca', 'pope-martin-1', NULL),
  ('src-boniface-ce', 'willibrord', NULL),
  ('src-boniface-ce', 'boniface', NULL),
  ('src-boniface-ce', 'pope-gregory-ii', NULL),
  ('src-alcuin-britannica', 'alcuin-york', NULL),
  ('src-alcuin-britannica', 'charlemagne', NULL),
  ('src-rabanus-britannica', 'alcuin-york', NULL),
  ('src-rabanus-britannica', 'rabanus-maurus', NULL),
  ('src-photios-oca', 'photios-constantinople', NULL),
  ('src-photios-oca', 'cyril-methodius', NULL),
  ('src-eugenius-newadvent', 'pope-eugenius-iii', NULL),
  ('src-eugenius-newadvent', 'bernard-clairvaux', NULL),
  ('src-poor-clares-britannica', 'francis-assisi', NULL),
  ('src-poor-clares-britannica', 'clare-assisi', NULL),
  ('src-moerbeke-pims', 'william-moerbeke', NULL),
  ('src-moerbeke-pims', 'thomas-aquinas', NULL),
  ('src-pico-sep', 'pico-mirandola', NULL),
  ('src-pico-sep', 'savonarola', NULL),
  ('src-erasmus-more-letter', 'desiderius-erasmus', NULL),
  ('src-erasmus-more-letter', 'thomas-more', NULL),
  ('src-lutheranreformation-marburg', 'martin-luther', NULL),
  ('src-lutheranreformation-marburg', 'huldrych-zwingli', NULL),
  ('src-calvin-farel-ligonier', 'william-farel', NULL),
  ('src-calvin-farel-ligonier', 'john-calvin', NULL),
  ('src-melanchthon-britannica', 'martin-luther', NULL),
  ('src-melanchthon-britannica', 'philipp-melanchthon', NULL),
  ('src-scu-roommates-paris', 'ignatius-loyola', NULL),
  ('src-scu-roommates-paris', 'francis-xavier', NULL),
  ('src-scu-roommates-paris', 'peter-faber', NULL),
  ('src-jesuits-xavier', 'ignatius-loyola', NULL),
  ('src-jesuits-xavier', 'francis-xavier', NULL),
  ('src-teresa-john-cross-aleteia', 'teresa-avila', NULL),
  ('src-teresa-john-cross-aleteia', 'john-cross', NULL),
  ('src-ccel-perpetua', 'perpetua', NULL),
  ('src-ccel-perpetua', 'saturus', NULL),
  ('src-wikipedia-hippolytus', 'hippolytus', NULL),
  ('src-wikipedia-hippolytus', 'callixtus-i', NULL),
  ('src-wikipedia-prosper', 'prosper-aquitaine', NULL),
  ('src-wikipedia-prosper', 'augustine', NULL),
  ('src-wikipedia-tome-leo', 'pope-leo-1', NULL),
  ('src-wikipedia-tome-leo', 'flavian-constantinople', NULL),
  ('src-wikipedia-caesarius', 'caesarius-arles', NULL),
  ('src-wikipedia-caesarius', 'aeonius-arles', NULL),
  ('src-wikipedia-maurus', 'benedict-nursia', NULL),
  ('src-wikipedia-maurus', 'maurus', NULL),
  ('src-wikipedia-columba', 'columba', NULL),
  ('src-wikipedia-columba', 'finnian-moville', NULL),
  ('src-fordham-bede-caedmon', 'hilda-whitby', NULL),
  ('src-fordham-bede-caedmon', 'caedmon', NULL),
  ('src-wikipedia-gertrude', 'gertrude-nivelles', NULL),
  ('src-wikipedia-gertrude', 'itta-metz', NULL),
  ('src-wikipedia-bede', 'bede', NULL),
  ('src-wikipedia-bede', 'benedict-biscop', NULL),
  ('src-wikipedia-bede', 'ceolfrith', NULL),
  ('src-wikipedia-beatus', 'beatus-liebana', NULL),
  ('src-wikipedia-beatus', 'eterius-osma', NULL),
  ('src-wikipedia-eriugena', 'john-scotus-eriugena', NULL),
  ('src-wikipedia-eriugena', 'hincmar-reims', NULL),
  ('src-wikipedia-odo', 'odo-cluny', NULL),
  ('src-wikipedia-odo', 'berno-cluny', NULL),
  ('src-wikipedia-sylvester-ii', 'sylvester-ii', NULL),
  ('src-wikipedia-sylvester-ii', 'adalbero-reims', NULL),
  ('src-wikipedia-bruno-querfurt', 'bruno-querfurt', NULL),
  ('src-wikipedia-bruno-querfurt', 'adalbert-prague', NULL),
  ('src-wikipedia-abelard', 'peter-abelard', NULL),
  ('src-wikipedia-abelard', 'anselm-laon', NULL),
  ('src-wikipedia-abelard', 'william-champeaux', NULL),
  ('src-wikipedia-abelard', 'heloise', NULL),
  ('src-wikipedia-scotus', 'duns-scotus', NULL),
  ('src-wikipedia-scotus', 'william-of-ware', NULL),
  ('src-wikipedia-dante', 'dante-alighieri', NULL),
  ('src-wikipedia-dante', 'brunetto-latini', NULL),
  ('src-wikipedia-purvey', 'john-wycliffe', NULL),
  ('src-wikipedia-purvey', 'john-purvey', NULL),
  ('src-wikipedia-julian', 'julian-norwich', NULL),
  ('src-wikipedia-julian', 'margery-kempe', NULL),
  ('src-wikipedia-kempis', 'thomas-kempis', NULL),
  ('src-wikipedia-kempis', 'florens-radewijns', NULL),
  ('src-wikipedia-cusa', 'nicholas-cusa', NULL),
  ('src-wikipedia-cusa', 'pope-eugenius-iv', NULL),
  ('src-wikipedia-copernicus', 'nicholas-copernicus', NULL),
  ('src-wikipedia-copernicus', 'tiedemann-giese', NULL),
  ('src-wikipedia-montesinos', 'antonio-montesinos', NULL),
  ('src-wikipedia-montesinos', 'bartolome-las-casas', NULL),
  ('src-wikipedia-bradford', 'william-bradford', NULL),
  ('src-wikipedia-bradford', 'william-brewster', NULL),
  ('src-wikipedia-bradford', 'john-robinson', NULL)
ON CONFLICT DO NOTHING;

-- ── CH_Works ───────────────────────────────────────────────────────────
INSERT INTO public."CH_Works" (person_id, name, text_url) VALUES
  ('john-evangelist', 'Gospel of John', 'https://www.biblegateway.com/passage/?search=John+1&version=ESV'),
  ('john-evangelist', 'First Epistle of John (1 John)', 'https://www.biblegateway.com/passage/?search=1+John+1&version=ESV'),
  ('john-evangelist', 'Second Epistle of John (2 John)', 'https://www.biblegateway.com/passage/?search=2+John+1&version=ESV'),
  ('john-evangelist', 'Third Epistle of John (3 John)', 'https://www.biblegateway.com/passage/?search=3+John+1&version=ESV'),
  ('john-evangelist', 'Revelation', 'https://www.biblegateway.com/passage/?search=Revelation+1&version=ESV'),
  ('paul', 'Epistle to the Romans', 'https://www.biblegateway.com/passage/?search=Romans+1&version=ESV'),
  ('paul', 'First Epistle to the Corinthians (1 Corinthians)', 'https://www.biblegateway.com/passage/?search=1+Corinthians+1&version=ESV'),
  ('paul', 'Second Epistle to the Corinthians (2 Corinthians)', 'https://www.biblegateway.com/passage/?search=2+Corinthians+1&version=ESV'),
  ('paul', 'Epistle to the Galatians', 'https://www.biblegateway.com/passage/?search=Galatians+1&version=ESV'),
  ('paul', 'Epistle to the Ephesians', 'https://www.biblegateway.com/passage/?search=Ephesians+1&version=ESV'),
  ('peter', 'First Epistle of Peter (1 Peter)', 'https://www.biblegateway.com/passage/?search=1+Peter+1&version=ESV'),
  ('peter', 'Second Epistle of Peter (2 Peter)', 'https://www.biblegateway.com/passage/?search=2+Peter+1&version=ESV'),
  ('papias', 'Exposition of the Sayings of the Lord (fragments)', 'https://ccel.org/ccel/schaff/anf-series/anf-series'),
  ('clement-rome', 'First Epistle of Clement to the Corinthians (1 Clement)', 'https://ccel.org/ccel/schaff/anf-series/anf-series'),
  ('ignatius-antioch', 'Letter to the Ephesians', 'https://ccel.org/ccel/schaff/anf-series/anf-series'),
  ('ignatius-antioch', 'Letter to the Magnesians', 'https://ccel.org/ccel/schaff/anf-series/anf-series'),
  ('ignatius-antioch', 'Letter to the Trallians', 'https://ccel.org/ccel/schaff/anf-series/anf-series'),
  ('ignatius-antioch', 'Letter to the Romans', 'https://ccel.org/ccel/schaff/anf-series/anf-series'),
  ('ignatius-antioch', 'Letter to Polycarp', 'https://ccel.org/ccel/schaff/anf-series/anf-series'),
  ('polycarp', 'Letter to the Philippians', 'https://ccel.org/ccel/schaff/anf-series/anf-series'),
  ('justin-martyr', 'First Apology', 'https://ccel.org/ccel/schaff/anf-series/anf-series'),
  ('justin-martyr', 'Second Apology', 'https://ccel.org/ccel/schaff/anf-series/anf-series'),
  ('justin-martyr', 'Dialogue with Trypho', 'https://ccel.org/ccel/schaff/anf-series/anf-series'),
  ('clement-alexandria', 'Protrepticus (Exhortation to the Greeks)', 'https://ccel.org/ccel/schaff/anf02.html'),
  ('clement-alexandria', 'Paedagogus (The Instructor)', 'https://ccel.org/ccel/schaff/anf02.html'),
  ('clement-alexandria', 'Stromata (Miscellanies)', 'https://ccel.org/ccel/schaff/anf02.html'),
  ('clement-alexandria', 'Who Is the Rich Man That Shall Be Saved? (Quis Dives Salvetur)', 'https://ccel.org/ccel/schaff/anf02.html'),
  ('tatians', 'Diatessaron', 'https://ccel.org/ccel/schaff/anf02.html'),
  ('tatians', 'Address to the Greeks', 'https://ccel.org/ccel/schaff/anf02.html'),
  ('irenaeus', 'Against Heresies', 'https://ccel.org/ccel/schaff/anf01'),
  ('irenaeus', 'Demonstration of the Apostolic Preaching (Proof of the Apostolic Preaching)', 'https://ccel.org/ccel/schaff/anf01'),
  ('tertullian', 'Apology', 'https://ccel.org/ccel/tertullian'),
  ('tertullian', 'Prescription Against Heretics', 'https://ccel.org/ccel/tertullian'),
  ('tertullian', 'Against Marcion', 'https://ccel.org/ccel/tertullian'),
  ('tertullian', 'On Baptism', 'https://ccel.org/ccel/tertullian'),
  ('tertullian', 'On the Flesh of Christ', 'https://ccel.org/ccel/tertullian'),
  ('hippolytus', 'Apostolic Tradition (attributed)', 'https://ccel.org/ccel/schaff/anf05'),
  ('hippolytus', 'Refutation of All Heresies', 'https://ccel.org/ccel/schaff/anf05'),
  ('hippolytus', 'Commentary on Daniel', 'https://ccel.org/ccel/schaff/anf05'),
  ('hippolytus', 'On Christ and Antichrist', 'https://ccel.org/ccel/schaff/anf05'),
  ('perpetua', 'The Passion of Perpetua and Felicity (Perpetua’s diary portion)', 'https://www.cambridge.org/core/journals/church-history/article/suicide-by-gladiator-the-acts-of-perpetua-and-felicitas-in-its-north-african-context/956AA0BD2ED4F9F14CF28071B1085CF9'),
  ('origen', 'On First Principles (De Principiis)', 'https://www.ccel.org/ccel/origen'),
  ('origen', 'Against Celsus', 'https://www.ccel.org/ccel/origen'),
  ('origen', 'On Prayer', 'https://www.ccel.org/ccel/origen'),
  ('origen', 'Commentary on the Gospel of John', 'https://www.ccel.org/ccel/origen'),
  ('origen', 'Homilies on Genesis', 'https://www.ccel.org/ccel/origen'),
  ('gregory-thaumaturgus', 'Address of Thanksgiving to Origen (Panegyric)', 'https://bkv.unifr.ch/works/cpg-1763/versions/the-oration-and-panegyric-addressed-to-origen/divisions'),
  ('gregory-thaumaturgus', 'Declaration of Faith (Creed) (traditional attribution)', 'https://orthodoxchurchfathers.com/fathers/anf06/anf0606.html'),
  ('dionysius-alexandria', 'On the Promises (as preserved in fragments/quotations)', 'https://www.ccel.org/ccel/feltoe/dionysius.dionysius.t.t1.html'),
  ('dionysius-alexandria', 'Letters (selected, as preserved in Eusebius)', 'https://ccel.org/ccel/feltoe/dionysius/dionysius.toc.html'),
  ('cyprian', 'On the Unity of the Catholic Church', 'https://ccel.org/ccel/cyprian'),
  ('cyprian', 'On the Lapsed', 'https://ccel.org/ccel/cyprian'),
  ('cyprian', 'On Mortality', 'https://ccel.org/ccel/cyprian'),
  ('cyprian', 'On the Lord’s Prayer', 'https://ccel.org/ccel/cyprian'),
  ('cyprian', 'Letters (Epistles)', 'https://ccel.org/ccel/cyprian'),
  ('alexander-alexandria', 'Letter(s) against Arianism (selected)', 'https://ccel.org/ccel/alexander_alexandria/heresy_and_deposition/anf06.x.iii.i.html'),
  ('athanasius', 'On the Incarnation', 'https://www.ccel.org/ccel/athanasius/incarnation'),
  ('athanasius', 'Life of Antony', 'https://ccel.org/ccel/athanasius'),
  ('athanasius', 'Orations Against the Arians', 'https://ccel.org/ccel/athanasius'),
  ('athanasius', 'Letters to Serapion on the Holy Spirit', 'https://ccel.org/ccel/athanasius'),
  ('athanasius', 'Festal Letters (selected)', 'https://ccel.org/ccel/athanasius'),
  ('basil-great', 'On the Holy Spirit', 'https://www.ccel.org/ccel/basil'),
  ('basil-great', 'Hexaemeron', 'https://www.ccel.org/ccel/basil'),
  ('basil-great', 'Longer Rules (Regulae Fusius Tractatae)', 'https://www.ccel.org/ccel/basil'),
  ('basil-great', 'Shorter Rules (Regulae Brevius Tractatae)', 'https://www.ccel.org/ccel/basil'),
  ('basil-great', 'Address to Young Men on How They Might Derive Benefit from Greek Literature', 'https://www.ccel.org/ccel/basil'),
  ('gregory-nazianzus', 'Theological Orations (Orations 27–31)', 'https://ccel.org/ccel/schaff/npnf207'),
  ('gregory-nazianzus', 'Orations (selected)', 'https://ccel.org/ccel/schaff/npnf207'),
  ('gregory-nazianzus', 'Letters (selected)', 'https://ccel.org/ccel/schaff/npnf207'),
  ('gregory-nazianzus', 'Poems (selected)', 'https://ccel.org/ccel/schaff/npnf207'),
  ('gregory-nazianzus', 'Oration 43: Funeral Oration on Basil', 'https://ccel.org/ccel/schaff/npnf207'),
  ('gregory-nyssa', 'Life of Moses', 'https://www.ccel.org/g/gregorynyssa/index.html'),
  ('gregory-nyssa', 'Great Catechism', 'https://www.ccel.org/g/gregorynyssa/index.html'),
  ('gregory-nyssa', 'On the Making of Man', 'https://www.ccel.org/g/gregorynyssa/index.html'),
  ('gregory-nyssa', 'On the Soul and the Resurrection', 'https://www.ccel.org/g/gregorynyssa/index.html'),
  ('gregory-nyssa', 'Against Eunomius', 'https://www.ccel.org/g/gregorynyssa/index.html'),
  ('ambrose-milan', 'On the Duties of the Clergy (De Officiis Ministrorum)', 'https://www.ccel.org/ccel/ambrose'),
  ('ambrose-milan', 'On the Mysteries (De Mysteriis)', 'https://www.ccel.org/ccel/ambrose'),
  ('ambrose-milan', 'On the Sacraments (De Sacramentis)', 'https://www.ccel.org/ccel/ambrose'),
  ('ambrose-milan', 'On the Holy Spirit (De Spiritu Sancto)', 'https://www.ccel.org/ccel/ambrose'),
  ('ambrose-milan', 'On Repentance (De Paenitentia)', 'https://www.ccel.org/ccel/ambrose'),
  ('jerome', 'On Illustrious Men (De Viris Illustribus)', 'https://ccel.org/ccel/jerome'),
  ('jerome', 'Against Jovinian (Adversus Jovinianum)', 'https://ccel.org/ccel/jerome'),
  ('jerome', 'Letter 22 to Eustochium', 'https://ccel.org/ccel/jerome'),
  ('jerome', 'Lives of the Hermits (Paul, Hilarion, Malchus)', 'https://ccel.org/ccel/jerome'),
  ('jerome', 'Commentary on Galatians', 'https://ccel.org/ccel/jerome'),
  ('john-chrysostom', 'On the Priesthood', 'https://www.ccel.org/ccel/chrysostom'),
  ('john-chrysostom', 'Homilies on Matthew', 'https://www.ccel.org/ccel/chrysostom'),
  ('john-chrysostom', 'Homilies on John', 'https://www.ccel.org/ccel/chrysostom'),
  ('john-chrysostom', 'Homilies on Romans', 'https://www.ccel.org/ccel/chrysostom'),
  ('john-chrysostom', 'Letters to Olympias', 'https://www.ccel.org/ccel/chrysostom'),
  ('augustine', 'Confessions', 'https://www.ccel.org/ccel/augustine/confessions.html'),
  ('augustine', 'The City of God', 'https://www.ccel.org/ccel/augustine/cityofgod.html'),
  ('augustine', 'On the Trinity (De Trinitate)', 'https://www.ccel.org/ccel/augustine'),
  ('augustine', 'On Christian Doctrine (De Doctrina Christiana)', 'https://www.ccel.org/ccel/augustine/doctrine.html'),
  ('augustine', 'Enchiridion (Handbook on Faith, Hope, and Love)', 'https://www.ccel.org/ccel/augustine/enchiridion.html'),
  ('didymus-blind', 'On the Holy Spirit (De Spiritu Sancto)', 'https://www.persee.fr/doc/rscir_0035-2217_1993_num_67_2_3230_t1_0122_0000_2'),
  ('didymus-blind', 'On the Trinity (De Trinitate) (attributed)', 'https://www.cambridge.org/core/books/making-of-orthodoxy/some-sources-used-in-the-de-trinitate-ascribed-to-didymus-the-blind/209888B8E20E469C12B7A288DC8317EB'),
  ('rufinus-aquileia', 'Commentary on the Apostles’ Creed', 'https://ccel.org/ccel/schaff/anf08/anf08.vi.iii.ii.html'),
  ('rufinus-aquileia', 'Church History (Latin continuation/translation of Eusebius) (traditional association)', 'https://ccel.org/ccel/schaff/anf08/anf08.vi.iii.ii.html'),
  ('rufinus-aquileia', 'Apology for Origen', 'https://ccel.org/ccel/schaff/anf08/anf08.vi.iii.ii.html'),
  ('theophilus-alexandria', 'Paschal Letters (selected)', 'https://www.newadvent.org/fathers/260196.htm'),
  ('theophilus-alexandria', 'Festal Letters (selected)', 'https://elmhurst.ecampus.com/theophilus-alexandria-1st-russell-norman/bk/9780415289146'),
  ('cyril-alexandria', 'Commentary on the Gospel of John', 'https://www.ccel.org/ccel/cyril'),
  ('cyril-alexandria', 'On the Unity of Christ', 'https://www.ccel.org/ccel/cyril'),
  ('cyril-alexandria', 'Five Tomes Against Nestorius', 'https://www.ccel.org/ccel/cyril'),
  ('cyril-alexandria', 'Festal Letters (selected)', 'https://www.ccel.org/ccel/cyril'),
  ('cyril-alexandria', 'Commentary on Luke (fragments/selected)', 'https://www.ccel.org/ccel/cyril'),
  ('patrick', 'Confessio', 'https://www.confessio.ie/etexts/confessio_english#'),
  ('patrick', 'Letter to the Soldiers of Coroticus', 'https://www.confessio.ie/etexts/epistola_english#'),
  ('prosper-aquitaine', 'Chronicle (Epitoma Chronicon)', 'https://openlibrary.org/works/OL4799175W/Prosperi_Tironis_Epitoma_chronicon'),
  ('prosper-aquitaine', 'Against the Ingrates (Carmen de Ingratis)', 'https://books.google.com/books?id=lN4PAAAAQAAJ'),
  ('prosper-aquitaine', 'Liber contra Collatorem', 'https://www.newadvent.org/cathen/12487a.htm'),
  ('pope-leo-1', 'Tome of Leo', 'https://ccel.org/ccel/leo'),
  ('pope-leo-1', 'Sermons (selected)', 'https://ccel.org/ccel/leo'),
  ('pope-leo-1', 'Letters (selected)', 'https://ccel.org/ccel/leo'),
  ('faustus-riez', 'On Grace (De Gratia) (traditional attribution)', 'https://www.britannica.com/biography/Faustus-of-Riez'),
  ('faustus-riez', 'Letters (selected)', 'https://scaife.perseus.org/library/urn:cts:latinLit:stoa0121g.stoa003/'),
  ('claudianus-mamertus', 'On the State of the Soul (De Statu Animae)', 'https://la.wikisource.org/wiki/De_statu_animae'),
  ('pope-simplicius', 'Letters (selected)', 'https://www.newadvent.org/cathen/14002a.htm'),
  ('benedict-nursia', 'Rule of St Benedict', 'https://www.penguinrandomhouse.com/books/630016/the-rule-of-saint-benedict-by-translated-with-an-introduction-by-anthony-c-meisel-and-m-l-del-mastro/'),
  ('caesarius-arles', 'Sermons (selected)', 'https://www.cuapress.org/9780813214047/sermons/'),
  ('caesarius-arles', 'Rule for Nuns', 'https://www.earlymedievalmonasticism.org/texts/Caesarius-Regula-ad-virgines.html'),
  ('caesarius-arles', 'Letters (selected)', 'https://epistolae.ctl.columbia.edu/people/26123.html'),
  ('pope-gregory-great', 'Pastoral Rule (Regula Pastoralis)', 'https://www.ccel.org/ccel/gregory'),
  ('pope-gregory-great', 'Moralia on Job', 'https://www.ccel.org/ccel/gregory'),
  ('pope-gregory-great', 'Dialogues', 'https://www.ccel.org/ccel/gregory'),
  ('pope-gregory-great', 'Homilies on Ezekiel', 'https://www.ccel.org/ccel/gregory'),
  ('pope-gregory-great', 'Homilies on the Gospels', 'https://www.ccel.org/ccel/gregory'),
  ('isidore-seville', 'Etymologies (Etymologiae)', 'https://la.wikisource.org/wiki/Etymologiarum_libri_XX'),
  ('isidore-seville', 'On the Nature of Things (De Natura Rerum)', 'https://en.wikisource.org/wiki/Author:Isidore_of_Seville'),
  ('isidore-seville', 'Sentences (Sententiae)', 'https://en.wikisource.org/wiki/Author:Isidore_of_Seville'),
  ('isidore-seville', 'On Ecclesiastical Offices (De Ecclesiasticis Officiis)', 'https://en.wikisource.org/wiki/Author:Isidore_of_Seville'),
  ('isidore-seville', 'History of the Goths, Vandals, and Suevi', 'https://en.wikisource.org/wiki/Author:Isidore_of_Seville'),
  ('maximus-confessor', 'Ambigua', 'https://www.ccel.org/ccel/maximus'),
  ('maximus-confessor', 'Mystagogia', 'https://www.ccel.org/ccel/maximus'),
  ('maximus-confessor', 'Questions to Thalassius', 'https://www.ccel.org/ccel/maximus'),
  ('maximus-confessor', 'Disputation with Pyrrhus', 'https://www.ccel.org/ccel/maximus'),
  ('maximus-confessor', 'Four Hundred Chapters on Love', 'https://www.ccel.org/ccel/maximus'),
  ('audoin', 'Life of Saint Eligius (Vita Sancti Eligii)', 'https://la.wikisource.org/wiki/Vita_S._Eligii'),
  ('boniface', 'Letters (Correspondence) (selected)', 'https://elfinspell.com/Boniface1.html'),
  ('bede', 'Ecclesiastical History of the English People', 'https://www.ccel.org/ccel/bede'),
  ('bede', 'On the Reckoning of Time (De Temporum Ratione)', 'https://www.ccel.org/ccel/bede'),
  ('bede', 'Lives of the Abbots of Wearmouth and Jarrow', 'https://www.ccel.org/ccel/bede'),
  ('bede', 'Commentary on Mark', 'https://www.ccel.org/ccel/bede'),
  ('bede', 'On the Temple (De Templo)', 'https://www.ccel.org/ccel/bede'),
  ('beatus-liebana', 'Commentary on the Apocalypse', 'https://www.themorgan.org/collection/commentary-apocalypse/112348/285'),
  ('paulinus-aquileia', 'Libellus Sacrosyllabus (against Adoptionism)', 'https://researchportal.helsinki.fi/en/publications/the-libellus-sacrosyllabus-of-paulinus-ii-of-aquileia-publishing-'),
  ('paulinus-aquileia', 'Letters (selected)', 'https://la.wikisource.org/wiki/Patrologia_Latina/99'),
  ('alcuin-york', 'On the Trinity and Incarnation (De Fide Sanctae Trinitatis)', 'https://en.wikisource.org/wiki/Author:Alcuin'),
  ('alcuin-york', 'De Virtutibus et Vitiis', 'https://en.wikisource.org/wiki/Author:Alcuin'),
  ('alcuin-york', 'Letters (selected)', 'https://en.wikisource.org/wiki/Author:Alcuin'),
  ('alcuin-york', 'Disputation with Pepin', 'https://en.wikisource.org/wiki/Author:Alcuin'),
  ('alcuin-york', 'Life of Willibrord (Vita Willibrordi)', 'https://en.wikisource.org/wiki/Author:Alcuin'),
  ('rabanus-maurus', 'On the Education of Clergy (De Institutione Clericorum)', 'https://books.google.com/books/about/Rabani_Mauri_de_Institutione_Clericorum.html?id=hpP3wwEACAAJ'),
  ('rabanus-maurus', 'On the Nature of Things (De Rerum Naturis)', 'https://books.google.com/books/about/De_rerum_naturis.html?id=Z1lr0QEACAAJ'),
  ('rabanus-maurus', 'On the Praises of the Holy Cross (De Laudibus Sanctae Crucis)', 'https://la.wikisource.org/wiki/De_laudibus_Sanctae_Crucis_(Rabanus_Maurus)'),
  ('rabanus-maurus', 'Commentary on Matthew (selected)', 'https://la.wikisource.org/wiki/Commentarium_in_Matthaeum_(Rabanus_Maurus)'),
  ('kassia-byzantium', 'Hymn: The Fallen Woman (Kassia’s Troparion)', 'https://www.musicale.gr/afieromata/kassiani/index_en.html'),
  ('kassia-byzantium', 'Hymns (selected)', 'https://byzantine.lib.princeton.edu/byzantine/translation/15956'),
  ('kassia-byzantium', 'Epigrams (selected)', 'https://byzantine.lib.princeton.edu/byzantine/translation/15956'),
  ('john-scotus-eriugena', 'Periphyseon (De Divisione Naturae)', 'https://www.booksamillion.com/p/Periphyseon/Johannes-Scotus-Eriugena/9780884024620'),
  ('john-scotus-eriugena', 'On Divine Predestination (De Praedestinatione)', 'https://www.barnesandnoble.com/w/treatise-on-divine-predestination-john-scottus-eriugena/1101996234'),
  ('john-scotus-eriugena', 'Homily on the Prologue of John', 'https://academic.oup.com/book/26478/chapter/194921583'),
  ('john-scotus-eriugena', 'Commentary on Pseudo-Dionysius (selected)', 'https://www.brepols.net/products/IS-9782503033112-1'),
  ('photios-constantinople', 'Bibliotheca (Myriobiblon)', 'https://ccel.org/ccel/pearse/morefathers/files/photius_bibliotheca_01.htm'),
  ('photios-constantinople', 'Mystagogy of the Holy Spirit', 'https://ccel.org/ccel/pearse/morefathers/files/photius_bibliotheca_01.htm'),
  ('photios-constantinople', 'Amphilochia (selected)', 'https://ccel.org/ccel/pearse/morefathers/files/photius_bibliotheca_01.htm'),
  ('photios-constantinople', 'Letters (selected)', 'https://ccel.org/ccel/pearse/morefathers/files/photius_bibliotheca_01.htm'),
  ('dhuoda-uzes', 'Liber Manualis (Handbook)', 'https://www.cambridge.org/core/journals/studies-in-church-history/article/god-and-man-in-dhuodas-liber-manualis/21C62FC0807D1866CB216FBF0B03D396'),
  ('cyril-methodius', 'Old Church Slavonic Translation of the Gospels (traditional attribution)', 'https://hrcak.srce.hr/265410'),
  ('cyril-methodius', 'Old Church Slavonic Liturgical Translations (selected, traditional attribution)', 'https://hrcak.srce.hr/22379'),
  ('cyril-methodius', 'Alphabet/Orthographic works (Glagolitic tradition) (traditional attribution)', 'https://en.wikipedia.org/wiki/Glagolitic_script'),
  ('remigius-auxerre', 'Commentary on Martianus Capella (attributed)', 'https://www.ccel.org/ccel/wace/biodict.html?term=Remigius%20of%20Auxerre'),
  ('remigius-auxerre', 'Commentary on Boethius (attributed)', 'https://www.cambridge.org/core/journals/traditio/article/remigian-commentaries-on-boethiuss-de-consolatione-philosophiae/B3B2B8E9E0A04C5B2A9B7E0D6E4A0D8B'),
  ('remigius-auxerre', 'Glosses/Commentaries on Priscian (attributed)', 'https://www.ccel.org/ccel/wace/biodict.html?term=Remigius%20of%20Auxerre'),
  ('odo-cluny', 'Vita Sancti Geraldi (Life of St Gerald of Aurillac)', 'https://la.wikisource.org/wiki/Vita_S._Geraldi_(Odo_Cluniacensis)'),
  ('odo-cluny', 'Collationes (Conferences) (attributed)', 'https://la.wikisource.org/wiki/Patrologia_Latina/133'),
  ('odo-cluny', 'De Musica (attributed)', 'https://books.google.com/books?id=R4YXvAEACAAJ&printsec=frontcover'),
  ('sylvester-ii', 'Letters (selected)', 'https://epistolae.ctl.columbia.edu/people/21350.html'),
  ('sylvester-ii', 'De Mensura Fistularum (On the Measure of Organ Pipes)', 'https://books.google.com/books?id=R4YXvAEACAAJ&printsec=frontcover'),
  ('lanfranc', 'On the Body and Blood of the Lord (De Corpore et Sanguine Domini)', 'https://brill.com/view/book/9789004330443/BP000012.xml'),
  ('lanfranc', 'Letters (selected)', 'https://books.google.com/books/about/The_Letters_of_Lanfranc.html?id=6vt3nQEACAAJ'),
  ('anselm', 'Proslogion', 'https://ccel.org/ccel/anselm'),
  ('anselm', 'Monologion', 'https://ccel.org/ccel/anselm'),
  ('anselm', 'Why God Became Man (Cur Deus Homo)', 'https://ccel.org/ccel/anselm'),
  ('anselm', 'On Truth (De Veritate)', 'https://ccel.org/ccel/anselm'),
  ('anselm', 'On the Freedom of the Will (De Libertate Arbitrii)', 'https://ccel.org/ccel/anselm'),
  ('anselm-laon', 'Glossa Ordinaria on the Bible (traditionally associated)', 'https://www.glossae.net/en/home/'),
  ('hildegard-bingen', 'Scivias', 'https://en.wikisource.org/wiki/Author:Hildegard_of_Bingen'),
  ('hildegard-bingen', 'Book of Life’s Merits (Liber Vitae Meritorum)', 'https://en.wikisource.org/wiki/Author:Hildegard_of_Bingen'),
  ('hildegard-bingen', 'Book of Divine Works (Liber Divinorum Operum)', 'https://en.wikisource.org/wiki/Author:Hildegard_of_Bingen'),
  ('hildegard-bingen', 'Physica', 'https://en.wikisource.org/wiki/Author:Hildegard_of_Bingen'),
  ('hildegard-bingen', 'Causae et Curae', 'https://en.wikisource.org/wiki/Author:Hildegard_of_Bingen'),
  ('bernard-clairvaux', 'On Loving God (De Diligendo Deo)', 'https://www.ccel.org/ccel/bernard'),
  ('bernard-clairvaux', 'Sermons on the Song of Songs (selected)', 'https://www.ccel.org/ccel/bernard'),
  ('bernard-clairvaux', 'On Consideration (De Consideratione)', 'https://www.ccel.org/ccel/bernard'),
  ('bernard-clairvaux', 'On Grace and Free Choice (De Gratia et Libero Arbitrio)', 'https://www.ccel.org/ccel/bernard'),
  ('bernard-clairvaux', 'Life of St Malachy (Vita Sancti Malachiae)', 'https://www.ccel.org/ccel/bernard'),
  ('william-auxerre', 'Summa Aurea', 'https://www.britannica.com/topic/Summa-aurea'),
  ('francis-assisi', 'Canticle of the Creatures', 'https://en.wikisource.org/wiki/Canticle_of_the_Sun'),
  ('francis-assisi', 'Earlier Rule (Regula non bullata)', 'https://www.ofm.org/franciscan-writings/earlier-rule'),
  ('francis-assisi', 'Later Rule (Regula bullata)', 'https://franciscan-archive.org/bullarium/TheRegulaBullataLSz.pdf'),
  ('francis-assisi', 'Testament', 'https://www.ofm.org/franciscan-writings/testament'),
  ('francis-assisi', 'Admonitions', 'https://www.franciscanarchive.org/franciscan-literature/assisi/admonitions/'),
  ('robert-grosseteste', 'On Light (De Luce)', 'https://la.wikisource.org/wiki/De_luce'),
  ('robert-grosseteste', 'Hexaemeron (Commentary on Six Days of Creation)', 'https://openlibrary.org/works/OL2878916W/Robert_Grosseteste_On_the_Six_Days_of_Creation'),
  ('robert-grosseteste', 'On Truth (De Veritate) (attributed/associated)', 'https://plato.stanford.edu/archives/sum2024/entries/grosseteste/'),
  ('robert-grosseteste', 'Letters (selected)', 'https://plato.stanford.edu/archives/sum2024/entries/grosseteste/'),
  ('nicephorus-blemmydes', 'Autobiography (attributed)', 'https://search.worldcat.org/title/Nicephori-Blemmydae-Autobiographia-sive-Curriculum-vitae-necnon-Epistula-universalior/oclc/1296420536'),
  ('nicephorus-blemmydes', 'Epitome of Logic', 'https://books.google.com/books/about/Nicephori_Blemmidae_opera_omnia.html?id=yfQUAAAAQAAJ'),
  ('nicephorus-blemmydes', 'Epitome of Physics', 'https://books.google.com/books/about/Nicephori_Blemmidae_opera_omnia.html?id=yfQUAAAAQAAJ'),
  ('william-moerbeke', 'Latin Translation of Aristotle’s Metaphysics (attributed)', 'https://www.brepols.net/products/IS-9782503534793-1'),
  ('william-moerbeke', 'Latin Translation of Proclus’ Elements of Theology', 'https://www.cambridge.org/core/journals/classical-review/article/abs/proclus-elementatio-theologica-translata-a-guillelmo-de-moerbecca-edited-by-h-boese-k-cm-thomas-bibliotheca-teubneriana-123-1-xvi-291-pp-leipzig-teubner-1980-dm-58/1D1CEB2AB74A979C6F3BC15A7F70CC69'),
  ('william-moerbeke', 'Latin Translation of Archimedes (selected) (attributed)', 'https://blogs.bl.uk/digitisedmanuscripts/2022/08/from-constantinople-to-canterbury-the-medieval-manuscript-that-contains-euclid-archimedes-and-aristotle.html'),
  ('thomas-aquinas', 'Summa Theologiae', 'https://www.newadvent.org/summa/'),
  ('thomas-aquinas', 'Summa Contra Gentiles', 'https://ccel.org/ccel/aquinas'),
  ('thomas-aquinas', 'Catena Aurea', 'https://ccel.org/ccel/aquinas'),
  ('thomas-aquinas', 'On Being and Essence (De Ente et Essentia)', 'https://ccel.org/ccel/aquinas'),
  ('thomas-aquinas', 'Compendium of Theology', 'https://ccel.org/ccel/aquinas'),
  ('duns-scotus', 'Ordinatio (Opus Oxoniense)', 'https://www.ccel.org/s/scotus/'),
  ('duns-scotus', 'Reportatio (Lectura/Reportationes)', 'https://www.ccel.org/s/scotus/'),
  ('duns-scotus', 'On the First Principle (De Primo Principio)', 'https://www.ccel.org/s/scotus/'),
  ('duns-scotus', 'Questions on the Metaphysics (Quaestiones super Metaphysicam)', 'https://www.ccel.org/s/scotus/'),
  ('duns-scotus', 'Theoremata (attributed)', 'https://www.ccel.org/s/scotus/'),
  ('dante-alighieri', 'The Divine Comedy', 'https://www.ccel.org/ccel/dante'),
  ('dante-alighieri', 'Vita Nuova', 'https://www.ccel.org/ccel/dante'),
  ('dante-alighieri', 'Convivio', 'https://www.ccel.org/ccel/dante'),
  ('dante-alighieri', 'De Vulgari Eloquentia', 'https://www.ccel.org/ccel/dante'),
  ('dante-alighieri', 'De Monarchia', 'https://www.ccel.org/ccel/dante'),
  ('thomas-bradwardine', 'On the Cause of God (De Causa Dei)', 'https://books.google.com/books/about/De_causa_Dei.html?id=FPxJAAAAcAAJ'),
  ('thomas-bradwardine', 'Tractatus de Proportionibus', 'https://www.britannica.com/biography/Thomas-Bradwardine'),
  ('thomas-bradwardine', 'De Continuo (attributed/associated)', 'https://academic.oup.com/book/33556/chapter/287947098/chapter-pdf/39827504/oso-9780198809647-chapter-4.pdf'),
  ('john-wycliffe', 'On the Truth of Holy Scripture (De Veritate Sacrae Scripturae)', 'https://en.wikisource.org/wiki/Author:John_Wycliffe'),
  ('john-wycliffe', 'On the Church (De Ecclesia)', 'https://en.wikisource.org/wiki/Author:John_Wycliffe'),
  ('john-wycliffe', 'On Civil Dominion (De Civili Dominio)', 'https://en.wikisource.org/wiki/Author:John_Wycliffe'),
  ('john-wycliffe', 'On the Eucharist (De Eucharistia) (attributed)', 'https://en.wikisource.org/wiki/Author:John_Wycliffe'),
  ('john-wycliffe', 'Trialogus (attributed)', 'https://en.wikisource.org/wiki/Author:John_Wycliffe'),
  ('julian-norwich', 'Revelations of Divine Love', 'https://ccel.org/ccel/julian/revelations'),
  ('christine-pisan', 'The Book of the City of Ladies', 'https://en.wikisource.org/wiki/Author:Christine_de_Pizan'),
  ('christine-pisan', 'The Treasure of the City of Ladies', 'https://en.wikisource.org/wiki/Author:Christine_de_Pizan'),
  ('christine-pisan', 'The Book of the Deeds and Good Morals of King Charles V', 'https://en.wikisource.org/wiki/Author:Christine_de_Pizan'),
  ('christine-pisan', 'Letter of the God of Love (Epistre au Dieu d’Amours)', 'https://en.wikisource.org/wiki/Author:Christine_de_Pizan'),
  ('jan-hus', 'On the Church (De Ecclesia)', 'https://ccel.org/ccel/hus'),
  ('jan-hus', 'Letters (selected)', 'https://ccel.org/ccel/hus'),
  ('jan-hus', 'On Simony', 'https://ccel.org/ccel/hus'),
  ('jan-hus', 'Exposition of the Faith (selected) (attributed)', 'https://ccel.org/ccel/hus'),
  ('thomas-kempis', 'The Imitation of Christ', 'https://www.ccel.org/ccel/kempis'),
  ('thomas-kempis', 'Prayers and Meditations (selected)', 'https://www.ccel.org/ccel/kempis'),
  ('thomas-kempis', 'Sermons (selected)', 'https://www.ccel.org/ccel/kempis'),
  ('nicholas-cusa', 'On Learned Ignorance (De Docta Ignorantia)', 'https://www.ccel.org/ccel/nicolas'),
  ('nicholas-cusa', 'On the Peace of Faith (De Pace Fidei)', 'https://www.ccel.org/ccel/nicolas'),
  ('nicholas-cusa', 'On the Vision of God (De Visione Dei)', 'https://www.ccel.org/ccel/nicolas'),
  ('nicholas-cusa', 'On Conjectures (De Coniecturis)', 'https://www.ccel.org/ccel/nicolas'),
  ('nicholas-cusa', 'Idiota de Mente (The Layman on Mind)', 'https://www.ccel.org/ccel/nicolas'),
  ('savonarola', 'Triumph of the Cross', 'https://www.gutenberg.org/ebooks/74508'),
  ('savonarola', 'Compendium of Revelations (Compendio di Rivelazioni) (attributed)', 'https://books.google.com/books/about/Compendio_di_rivelazioni.html?id=MM8FlIEZGysC'),
  ('savonarola', 'Sermons (selected)', 'https://oll.libertyfund.org/titles/savonarola-scelta-de-prediche-e-scritti'),
  ('desiderius-erasmus', 'In Praise of Folly', 'https://www.ccel.org/ccel/erasmus'),
  ('desiderius-erasmus', 'Handbook of the Christian Soldier (Enchiridion Militis Christiani)', 'https://www.ccel.org/ccel/erasmus'),
  ('desiderius-erasmus', 'Colloquies', 'https://www.ccel.org/ccel/erasmus'),
  ('desiderius-erasmus', 'On Free Will (De Libero Arbitrio)', 'https://www.ccel.org/ccel/erasmus'),
  ('desiderius-erasmus', 'Novum Instrumentum Omne (Greek New Testament, 1516) / New Testament Paraphrases (selected)', 'https://www.ccel.org/ccel/erasmus'),
  ('nicholas-copernicus', 'On the Revolutions of the Heavenly Spheres (De Revolutionibus Orbium Coelestium)', 'https://ads.harvard.edu/books/1543droc.book'),
  ('bartolome-las-casas', 'A Short Account of the Destruction of the Indies', 'https://en.wikisource.org/wiki/A_Short_Account_of_the_Destruction_of_the_Indies'),
  ('bartolome-las-casas', 'History of the Indies (Historia de las Indias)', 'https://en.wikisource.org/wiki/Author:Bartolom%C3%A9_de_las_Casas'),
  ('bartolome-las-casas', 'In Defense of the Indians (Apologia)', 'https://en.wikisource.org/wiki/Author:Bartolom%C3%A9_de_las_Casas'),
  ('bartolome-las-casas', 'Apologetic History Summary (Apologética Historia Sumaria)', 'https://en.wikisource.org/wiki/Author:Bartolom%C3%A9_de_las_Casas'),
  ('bartolome-las-casas', 'Memorial de Remedios (Remedies for the Indies) (attributed/associated)', 'https://en.wikisource.org/wiki/Author:Bartolom%C3%A9_de_las_Casas'),
  ('thomas-more', 'Utopia', 'https://ccel.org/ccel/more'),
  ('thomas-more', 'Dialogue of Comfort against Tribulation', 'https://ccel.org/ccel/more'),
  ('thomas-more', 'The Sadness of Christ (De Tristitia Christi)', 'https://ccel.org/ccel/more'),
  ('thomas-more', 'A Dialogue Concerning Heresies', 'https://ccel.org/ccel/more'),
  ('thomas-more', 'History of King Richard III', 'https://ccel.org/ccel/more'),
  ('martin-luther', 'Ninety-Five Theses', 'https://www.ccel.org/ccel/luther'),
  ('martin-luther', 'Small Catechism', 'https://www.ccel.org/ccel/luther'),
  ('martin-luther', 'Large Catechism', 'https://www.ccel.org/ccel/luther'),
  ('martin-luther', 'The Bondage of the Will', 'https://www.ccel.org/ccel/luther'),
  ('martin-luther', 'The Freedom of a Christian', 'https://www.ccel.org/ccel/luther'),
  ('huldrych-zwingli', 'Sixty-Seven Articles', 'https://ccel.org/ccel/z/zwingli'),
  ('huldrych-zwingli', 'Commentary on True and False Religion', 'https://ccel.org/ccel/z/zwingli'),
  ('huldrych-zwingli', 'On the Lord’s Supper', 'https://ccel.org/ccel/z/zwingli'),
  ('huldrych-zwingli', 'On the Providence of God (De Providentia Dei)', 'https://ccel.org/ccel/z/zwingli'),
  ('ignatius-loyola', 'Spiritual Exercises', 'https://ccel.org/ccel/ignatius/exercises'),
  ('ignatius-loyola', 'Constitutions of the Society of Jesus', 'https://ccel.org/ccel/ignatius/exercises'),
  ('ignatius-loyola', 'Letters (selected)', 'https://ccel.org/ccel/ignatius/exercises'),
  ('peter-faber', 'Memoriale (Spiritual Diary)', 'https://books.google.com/books/about/The_Letters_and_Instructions_of_Peter_Faber.html?id=8b7sAAAAMAAJ'),
  ('peter-faber', 'Letters (selected)', 'https://books.google.com/books/about/The_Letters_and_Instructions_of_Peter_Faber.html?id=8b7sAAAAMAAJ'),
  ('francis-xavier', 'Letters (selected)', 'https://books.google.com/books/about/The_Life_and_Letters_of_St_Francis_Xavie.html?id=gbJSAAAAcAAJ'),
  ('john-calvin', 'Institutes of the Christian Religion', 'https://www.ccel.org/ccel/calvin/institutes.html'),
  ('john-calvin', 'Commentary on Romans', 'https://www.ccel.org/ccel/calvin'),
  ('john-calvin', 'Commentary on the Gospel of John', 'https://www.ccel.org/ccel/calvin'),
  ('john-calvin', 'Reply to Sadoleto', 'https://www.ccel.org/ccel/calvin'),
  ('john-calvin', 'On the Necessity of Reforming the Church', 'https://www.ccel.org/ccel/calvin'),
  ('teresa-avila', 'The Life of Teresa of Jesus (Autobiography)', 'https://ccel.org/ccel/teresa'),
  ('teresa-avila', 'The Way of Perfection', 'https://ccel.org/ccel/teresa'),
  ('teresa-avila', 'The Interior Castle', 'https://ccel.org/ccel/teresa'),
  ('teresa-avila', 'The Book of the Foundations', 'https://ccel.org/ccel/teresa'),
  ('teresa-avila', 'Concepts of the Love of God', 'https://ccel.org/ccel/teresa'),
  ('john-cross', 'Ascent of Mount Carmel', 'https://www.ccel.org/ccel/john_cross'),
  ('john-cross', 'Dark Night of the Soul', 'https://www.ccel.org/ccel/john_cross'),
  ('john-cross', 'Spiritual Canticle', 'https://www.ccel.org/ccel/john_cross'),
  ('john-cross', 'Living Flame of Love', 'https://www.ccel.org/ccel/john_cross'),
  ('john-cross', 'Sayings of Light and Love (Dichos)', 'https://www.ccel.org/ccel/john_cross'),
  ('william-bradford', 'Of Plymouth Plantation', 'https://www.gutenberg.org/ebooks/24950'),
  ('john-owen', 'On the Mortification of Sin in Believers', 'https://www.ccel.org/ccel/owen'),
  ('john-owen', 'The Death of Death in the Death of Christ', 'https://www.ccel.org/ccel/owen'),
  ('john-owen', 'Communion with God', 'https://www.ccel.org/ccel/owen'),
  ('john-owen', 'The Glory of Christ', 'https://www.ccel.org/ccel/owen'),
  ('john-owen', 'A Discourse Concerning the Holy Spirit', 'https://www.ccel.org/ccel/owen'),
  ('john-bunyan', 'The Pilgrim’s Progress', 'https://ccel.org/ccel/bunyan'),
  ('john-bunyan', 'Grace Abounding to the Chief of Sinners', 'https://ccel.org/ccel/bunyan'),
  ('john-bunyan', 'The Holy War', 'https://ccel.org/ccel/bunyan'),
  ('john-bunyan', 'The Life and Death of Mr. Badman', 'https://ccel.org/ccel/bunyan'),
  ('john-bunyan', 'The Jerusalem Sinner Saved', 'https://ccel.org/ccel/bunyan'),
  ('thomas-traherne', 'Centuries of Meditations', 'https://ccel.org/ccel/traherne/centuries'),
  ('thomas-traherne', 'Thanksgivings (poems/prayers) (collected)', 'https://ccel.org/ccel/traherne/centuries'),
  ('thomas-traherne', 'Christian Ethicks (attributed)', 'https://ccel.org/ccel/traherne/centuries'),
  ('isaac-newton', 'Philosophiæ Naturalis Principia Mathematica', 'https://plato.stanford.edu/entries/newton-principia/index.html'),
  ('isaac-newton', 'Opticks', 'https://www.britannica.com/topic/Opticks-by-Newton'),
  ('isaac-newton', 'Observations upon the Prophecies of Daniel and the Apocalypse of St. John', 'https://dev.gutenberg.org/files/16878/16878-h/16878-h.htm'),
  ('charles-wesley', 'Hymns and Sacred Poems (selected collections)', 'https://ccel.org/ccel/wesley/hymns'),
  ('john-wesley', 'Hymns and Sacred Poems (selected collections)', 'https://ccel.org/ccel/wesley/hymns'),
  ('charles-wesley', 'Charles Wesley’s Hymns (selected)', 'https://ccel.org/ccel/wesley/hymns'),
  ('charles-wesley', 'Poems (selected)', 'https://ccel.org/ccel/wesley/hymns'),
  ('john-wesley', 'Journal (selected)', 'https://ccel.org/ccel/wesley/journal'),
  ('john-wesley', 'Sermons (selected)', 'https://ccel.org/ccel/wesley/journal'),
  ('john-wesley', 'Explanatory Notes upon the New Testament', 'https://ccel.org/ccel/wesley/journal'),
  ('george-whitefield', 'Journals (selected)', 'https://ccel.org/ccel/whitefield/sermons'),
  ('george-whitefield', 'Sermons (selected)', 'https://ccel.org/ccel/whitefield/sermons'),
  ('pope-damasus-1', 'Damasian Epigrams (selected inscriptions/poems)', 'https://books.google.com/books/about/The_epigrams_of_St_Damasus.html?id=Y_C7pwAACAAJ'),
  ('possidius', 'Life of Saint Augustine (Vita Augustini)', 'https://www.ccel.org/ccel/pearse/morefathers/files/possidius_life_of_augustine_02_text.htm'),
  ('pope-cornelius', 'Letters (selected, as preserved)', 'https://www.ccel.org/ccel/schaff/anf05.iv.iv.html'),
  ('pope-stephen-1', 'Letters (selected, as preserved)', 'https://www.ccel.org/ccel/schaff/anf05.iv.iv.html'),
  ('leander-seville', 'De Institutione Virginum (On the Instruction of Virgins)', 'https://ora-et-labora.net/ORATIO/LEANDRO.html'),
  ('pope-martin-1', 'Letters (selected)', 'https://la.wikisource.org/wiki/Patrologia_Latina/87'),
  ('pope-gregory-ii', 'Letters (selected)', 'https://la.wikisource.org/wiki/Epistolae_et_canones_(Gregorius_II)')
ON CONFLICT DO NOTHING;

commit;
