-- PersonPlaces expansion — comprehensive person-place connections with scripture.
-- UNIQUE(person_id, place_id, narrative_age_id) — one context per person/place/age.
-- Context strings standardized: born here, died here, settled, sojourned, passed through,
-- fled here, fled from, ruled here, prophesied, conquered, built here, exiled here, etc.

begin;

insert into public."BP_PersonPlaces" (person_id, place_id, narrative_age_id, context, scripture_verse) values

  -- ══════════════════════════════════════════════════════════════════════════
  -- CREATION & PRIMEVAL HISTORY
  -- ══════════════════════════════════════════════════════════════════════════
  ('adam',     'garden-of-eden',  'age-creation',  'placed by God',            'Genesis 2:8'),
  ('eve',      'garden-of-eden',  'age-creation',  'placed by God',            'Genesis 2:21-22'),
  ('cain',     'land-of-nod',     'age-creation',  'settled',                  'Genesis 4:16'),
  ('noah',     'mt-ararat',       'age-creation',  'ark came to rest',         'Genesis 8:4'),
  ('nimrod',   'babel',           'age-creation',  'built here',               'Genesis 10:10'),
  ('nimrod',   'erech',           'age-creation',  'built here',               'Genesis 10:10'),
  ('nimrod',   'accad',           'age-creation',  'built here',               'Genesis 10:10'),
  ('nimrod',   'nineveh',         'age-creation',  'built here',               'Genesis 10:11'),
  ('nimrod',   'calah',           'age-creation',  'built here',               'Genesis 10:11-12'),
  ('shem',     'mt-ararat',       'age-creation',  'survived the flood',       'Genesis 8:18'),
  ('ham',      'mt-ararat',       'age-creation',  'survived the flood',       'Genesis 8:18'),
  ('japheth',  'mt-ararat',       'age-creation',  'survived the flood',       'Genesis 8:18'),

  -- ══════════════════════════════════════════════════════════════════════════
  -- PATRIARCHS
  -- ══════════════════════════════════════════════════════════════════════════
  ('abraham',  'beersheba',       'age-patriarchs', 'settled; dug a well',     'Genesis 21:31-34'),
  ('abraham',  'mamre',           'age-patriarchs', 'settled; met three visitors', 'Genesis 13:18, 18:1'),
  ('abraham',  'egypt-goshen',    'age-patriarchs', 'sojourned during famine', 'Genesis 12:10'),
  ('abraham',  'bethel',          'age-patriarchs', 'built an altar',          'Genesis 12:8, 13:3'),
  ('sarah',    'ur',              'age-patriarchs', 'born here',               'Genesis 11:29-31'),
  ('sarah',    'haran',           'age-patriarchs', 'sojourned',               'Genesis 11:31'),
  ('sarah',    'beersheba',       'age-patriarchs', 'settled',                 'Genesis 21:31-34'),
  ('lot',      'haran',           'age-patriarchs', 'sojourned',               'Genesis 11:31'),
  ('lot',      'sodom',           'age-patriarchs', 'settled',                 'Genesis 13:12'),
  ('lot',      'zoar',            'age-patriarchs', 'fled to',                 'Genesis 19:20-23'),
  ('hagar',    'beer-lahai-roi',  'age-patriarchs', 'met the angel of God',    'Genesis 16:7-14'),
  ('hagar',    'wilderness-of-paran', 'age-patriarchs', 'settled with Ishmael','Genesis 21:21'),
  ('ishmael',  'wilderness-of-paran', 'age-patriarchs', 'grew up here',        'Genesis 21:20-21'),
  ('melchizedek','jerusalem',     'age-patriarchs', 'king of Salem',           'Genesis 14:18'),
  ('isaac',    'beersheba',       'age-patriarchs', 'settled',                 'Genesis 26:23-25'),
  ('isaac',    'hebron',          'age-patriarchs', 'died and buried',         'Genesis 35:27-29'),
  ('rebekah',  'haran',           'age-patriarchs', 'born here',               'Genesis 24:10'),
  ('rebekah',  'beersheba',       'age-patriarchs', 'settled',                 'Genesis 24:62-67'),
  ('rebekah',  'hebron',          'age-patriarchs', 'buried',                  'Genesis 49:31'),
  ('esau',     'edom',            'age-patriarchs', 'settled',                 'Genesis 36:6-8'),
  ('esau',     'beersheba',       'age-patriarchs', 'born here',               'Genesis 25:25-26'),
  ('jacob',    'beersheba',       'age-patriarchs', 'born here',               'Genesis 25:26'),
  ('jacob',    'penuel',          'age-patriarchs', 'wrestled with God',       'Genesis 32:22-32'),
  ('jacob',    'mamre',           'age-patriarchs', 'returned to father',      'Genesis 35:27'),
  ('jacob',    'egypt-goshen',    'age-patriarchs', 'settled in old age',      'Genesis 46:28-34'),
  ('jacob',    'hebron',          'age-patriarchs', 'buried',                  'Genesis 50:13'),
  ('rachel',   'haran',           'age-patriarchs', 'born here',               'Genesis 29:6'),
  ('rachel',   'bethlehem',       'age-patriarchs', 'died and buried nearby',  'Genesis 35:19'),
  ('leah',     'haran',           'age-patriarchs', 'born here',               'Genesis 29:16'),
  ('leah',     'hebron',          'age-patriarchs', 'buried',                  'Genesis 49:31'),
  ('laban',    'haran',           'age-patriarchs', 'settled',                 'Genesis 24:29, 29:4-5'),
  ('laban',    'paddan-aram',     'age-patriarchs', 'settled',                 'Genesis 28:5'),
  ('dinah',    'shechem',         'age-patriarchs', 'assaulted here',          'Genesis 34:1-2'),
  ('reuben',   'egypt-goshen',    'age-patriarchs', 'settled',                 'Genesis 46:8-9'),
  ('judah',    'timnah',          'age-patriarchs', 'sojourned',               'Genesis 38:12-14'),
  ('judah',    'egypt-goshen',    'age-patriarchs', 'settled',                 'Genesis 46:28'),
  ('tamar-genesis', 'timnah',     'age-patriarchs', 'posed as a prostitute',   'Genesis 38:14'),
  ('joseph',   'dothan',          'age-patriarchs', 'sold by brothers',        'Genesis 37:17-28'),
  ('potiphar', 'egypt-goshen',    'age-patriarchs', 'served Pharaoh',          'Genesis 39:1'),
  ('benjamin', 'bethlehem',       'age-patriarchs', 'born here',               'Genesis 35:16-19'),
  ('benjamin', 'egypt-goshen',    'age-patriarchs', 'settled',                 'Genesis 46:21'),

  -- ══════════════════════════════════════════════════════════════════════════
  -- EXODUS & WILDERNESS
  -- ══════════════════════════════════════════════════════════════════════════
  ('moses',    'raamses',         'age-exodus',  'led departure from here',    'Exodus 12:37'),
  ('moses',    'red-sea',         'age-exodus',  'parted the waters',          'Exodus 14:21'),
  ('moses',    'marah',           'age-exodus',  'sweetened bitter water',     'Exodus 15:23-25'),
  ('moses',    'elim',            'age-exodus',  'camped',                     'Exodus 15:27'),
  ('moses',    'rephidim',        'age-exodus',  'struck rock for water',      'Exodus 17:6'),
  ('moses',    'kadesh-barnea',   'age-exodus',  'sent the twelve spies',      'Numbers 13:26'),
  ('moses',    'mt-nebo',         'age-exodus',  'died here',                  'Deuteronomy 34:1-5'),
  ('moses',    'plains-of-moab',  'age-exodus',  'delivered farewell speeches', 'Deuteronomy 1:5'),
  ('aaron',    'egypt-goshen',    'age-exodus',  'spoke before Pharaoh',       'Exodus 5:1'),
  ('aaron',    'sinai',           'age-exodus',  'made the golden calf',       'Exodus 32:1-6'),
  ('aaron',    'mt-hor',          'age-exodus',  'died here',                  'Numbers 20:22-29'),
  ('miriam',   'red-sea',         'age-exodus',  'led worship with tambourine','Exodus 15:20-21'),
  ('miriam',   'hazeroth',        'age-exodus',  'struck with leprosy',        'Numbers 12:1-15'),
  ('miriam',   'kadesh-barnea',   'age-exodus',  'died here',                  'Numbers 20:1'),
  ('pharaoh-of-exodus', 'raamses','age-exodus',  'confronted by Moses',        'Exodus 5-12'),
  ('pharaoh-of-exodus', 'red-sea','age-exodus',  'army drowned',               'Exodus 14:23-28'),
  ('jethro',   'sinai',           'age-exodus',  'visited Moses',              'Exodus 18:1-5'),
  ('zipporah',  'sinai',          'age-exodus',  'reunited with Moses',        'Exodus 18:2-6'),
  ('caleb',    'kadesh-barnea',   'age-exodus',  'gave faithful report',       'Numbers 13:30, 14:6-9'),
  ('caleb',    'hebron',          'age-conquest', 'received as inheritance',   'Joshua 14:12-15'),
  ('korah',    'kadesh-barnea',   'age-exodus',  'swallowed by the earth',     'Numbers 16:31-33'),
  ('balaam',   'plains-of-moab',  'age-exodus',  'blessed Israel',             'Numbers 22-24'),
  ('balak',    'plains-of-moab',  'age-exodus',  'hired Balaam',               'Numbers 22:1-6'),
  ('phinehas-eleazar', 'shittim', 'age-exodus',  'zealous act',               'Numbers 25:7-8'),
  ('eleazar',  'mt-hor',          'age-exodus',  'received priesthood',        'Numbers 20:25-28'),
  ('eleazar',  'shiloh',          'age-conquest', 'distributed the land',     'Joshua 14:1'),
  ('nadab',    'sinai',           'age-exodus',  'died offering strange fire', 'Leviticus 10:1-2'),
  ('abihu',    'sinai',           'age-exodus',  'died offering strange fire', 'Leviticus 10:1-2'),
  ('bezalel',  'sinai',           'age-exodus',  'built the Tabernacle',       'Exodus 35:30-36:2'),
  ('dathan',   'kadesh-barnea',   'age-exodus',  'swallowed by the earth',     'Numbers 16:31-33'),
  ('abiram',   'kadesh-barnea',   'age-exodus',  'swallowed by the earth',     'Numbers 16:31-33'),
  ('og',       'edrei',           'age-exodus',  'defeated here',              'Numbers 21:33-35'),
  ('og',       'bashan',          'age-exodus',  'ruled here',                 'Deuteronomy 3:1'),
  ('sihon',    'heshbon',         'age-exodus',  'defeated here',              'Numbers 21:23-26'),
  ('joshua',   'kadesh-barnea',   'age-exodus',  'gave faithful spy report',   'Numbers 14:6-9'),
  ('joshua',   'sinai',           'age-exodus',  'accompanied Moses on mountain','Exodus 24:13'),
  ('joshua',   'shiloh',          'age-conquest', 'set up the Tabernacle',     'Joshua 18:1'),
  ('joshua',   'ai',              'age-conquest', 'conquered',                 'Joshua 8'),
  ('joshua',   'gibeon',          'age-conquest', 'sun stood still',           'Joshua 10:12'),
  ('joshua',   'hazor',           'age-conquest', 'conquered',                 'Joshua 11:10-11'),
  ('joshua',   'shechem',         'age-conquest', 'renewed covenant',          'Joshua 24'),
  ('joshua',   'bethel-gilgal',   'age-conquest', 'first camp in Canaan',      'Joshua 4:19-20'),
  ('joshua',   'mt-ebal',         'age-conquest', 'built altar; read the Law', 'Joshua 8:30-35'),

  -- ══════════════════════════════════════════════════════════════════════════
  -- CONQUEST & JUDGES
  -- ══════════════════════════════════════════════════════════════════════════
  ('rahab',    'jericho',         'age-conquest', 'hid the spies',             'Joshua 2:1-7'),
  ('achan',    'ai',              'age-conquest', 'caused defeat by theft',    'Joshua 7:1-26'),
  ('othniel',  'debir',           'age-conquest', 'conquered; won Caleb''s daughter', 'Joshua 15:16-17; Judges 1:12-13'),
  ('ehud',     'jericho',         'age-conquest', 'assassinated Eglon',        'Judges 3:15-26'),
  ('barak',    'kedesh',          'age-conquest', 'summoned by Deborah',       'Judges 4:6'),
  ('barak',    'mt-tabor',        'age-conquest', 'gathered troops',           'Judges 4:6, 12'),
  ('sisera',   'hazor',           'age-conquest', 'served Jabin king of Hazor','Judges 4:2'),
  ('jael',     'kedesh',          'age-conquest', 'killed Sisera',             'Judges 4:17-22'),
  ('deborah',  'bethel',          'age-conquest', 'judged Israel between Ramah and Bethel', 'Judges 4:4-5'),
  ('gideon',   'ophrah',          'age-conquest', 'called by the angel',       'Judges 6:11-24'),
  ('gideon',   'jezreel-spring',  'age-conquest', 'tested soldiers at the spring', 'Judges 7:1-7'),
  ('gideon',   'succoth',         'age-conquest', 'punished the men of Succoth','Judges 8:5-16'),
  ('gideon',   'penuel',          'age-conquest', 'destroyed the tower',       'Judges 8:8-9, 17'),
  ('abimelech','shechem',         'age-conquest', 'made king; destroyed city', 'Judges 9:1-49'),
  ('jephthah', 'mizpah',          'age-conquest', 'made his vow',              'Judges 11:30-31, 34'),
  ('jephthah', 'gilead',          'age-conquest', 'raised here',               'Judges 11:1'),
  ('samson',   'zorah',           'age-conquest', 'born here',                 'Judges 13:2, 24-25'),
  ('samson',   'timnah',          'age-conquest', 'married a Philistine woman','Judges 14:1-4'),
  ('samson',   'gaza',            'age-conquest', 'carried off the gates; died here', 'Judges 16:1-3, 21-30'),
  ('samson',   'ashkelon',        'age-conquest', 'killed thirty men',         'Judges 14:19'),
  ('delilah',  'timnah',          'age-conquest', 'betrayed Samson',           'Judges 16:4-22'),
  ('manoah',   'zorah',           'age-conquest', 'angel appeared to him',     'Judges 13:2-20'),
  ('ruth',     'moab',            'age-conquest', 'born here',                 'Ruth 1:4'),
  ('ruth',     'bethlehem',       'age-conquest', 'settled; gleaned in Boaz''s field', 'Ruth 1:22-2:23'),
  ('boaz',     'bethlehem',       'age-conquest', 'redeemed Ruth',             'Ruth 4:1-13'),
  ('naomi',    'bethlehem',       'age-conquest', 'returned from Moab',        'Ruth 1:19-22'),
  ('naomi',    'moab',            'age-conquest', 'sojourned during famine',   'Ruth 1:1-2'),
  ('eli',      'shiloh',          'age-conquest', 'served as priest',          '1 Samuel 1:3, 9'),
  ('phinehas-eli', 'shiloh',      'age-conquest', 'corrupted the priesthood', '1 Samuel 2:12-17'),
  ('phinehas-eli', 'aphek',       'age-conquest', 'died when Ark captured',   '1 Samuel 4:11'),
  ('hophni',   'shiloh',          'age-conquest', 'corrupted the priesthood',  '1 Samuel 2:12-17'),
  ('hophni',   'aphek',           'age-conquest', 'died when Ark captured',    '1 Samuel 4:11'),
  ('samuel',   'ramah',           'age-united-monarchy', 'hometown; judged Israel', '1 Samuel 7:17'),
  ('samuel',   'bethel-gilgal',   'age-united-monarchy', 'judged on circuit',  '1 Samuel 7:16'),
  ('samuel',   'mizpah',          'age-united-monarchy', 'led revival; anointed Saul', '1 Samuel 7:5-6, 10:17-25'),
  ('samuel',   'bethlehem',       'age-united-monarchy', 'anointed David',     '1 Samuel 16:1-13'),
  ('ibzan',    'bethlehem-north', 'age-conquest', 'judged Israel from here',   'Judges 12:8-10'),
  ('jair',     'gilead',          'age-conquest', 'judged Israel',             'Judges 10:3-5'),
  ('tola',     'shechem',         'age-conquest', 'judged Israel',             'Judges 10:1-2'),

  -- ══════════════════════════════════════════════════════════════════════════
  -- UNITED MONARCHY
  -- ══════════════════════════════════════════════════════════════════════════
  ('saul',     'gibeah',          'age-united-monarchy', 'hometown and capital',   '1 Samuel 10:26, 15:34'),
  ('saul',     'jabesh-gilead',   'age-united-monarchy', 'rescued from Ammonites', '1 Samuel 11'),
  ('saul',     'michmash',        'age-united-monarchy', 'battle with Philistines','1 Samuel 13-14'),
  ('saul',     'bethel-gilgal',   'age-united-monarchy', 'offered unlawful sacrifice', '1 Samuel 13:8-14'),
  ('saul',     'mt-gilboa',       'age-united-monarchy', 'died in battle',         '1 Samuel 31:1-6'),
  ('saul',     'endor',           'age-united-monarchy', 'consulted a medium',     '1 Samuel 28'),
  ('saul',     'nob',             'age-united-monarchy', 'massacred the priests',  '1 Samuel 22:16-19'),
  ('jonathan', 'michmash',        'age-united-monarchy', 'raided Philistine garrison','1 Samuel 14:1-15'),
  ('jonathan', 'mt-gilboa',       'age-united-monarchy', 'died in battle',         '1 Samuel 31:2'),
  ('michal',   'gibeah',          'age-united-monarchy', 'helped David escape',    '1 Samuel 19:11-17'),
  ('michal',   'jerusalem',       'age-united-monarchy', 'despised David',         '2 Samuel 6:16'),
  ('abigail',  'carmel-town',     'age-united-monarchy', 'lived here',             '1 Samuel 25:2-3'),
  ('nabal',    'carmel-town',     'age-united-monarchy', 'wealthy landowner',      '1 Samuel 25:2'),
  ('abner',    'hebron',          'age-united-monarchy', 'murdered by Joab',       '2 Samuel 3:27'),
  ('abner',    'mahanaim',        'age-united-monarchy', 'served Ish-bosheth',     '2 Samuel 2:8'),
  ('ish-bosheth','mahanaim',      'age-united-monarchy', 'briefly king here',      '2 Samuel 2:8-9'),
  ('joab',     'jerusalem',       'age-united-monarchy', 'served David',           '2 Samuel 8:16'),
  ('joab',     'hebron',          'age-united-monarchy', 'killed Abner',           '2 Samuel 3:27'),
  ('bathsheba','jerusalem',       'age-united-monarchy', 'lived here',             '2 Samuel 11:2-5'),
  ('uriah',    'jerusalem',       'age-united-monarchy', 'recalled from battle',   '2 Samuel 11:6-13'),
  ('uriah',    'rabbah',          'age-united-monarchy', 'killed in battle',       '2 Samuel 11:14-17'),
  ('absalom',  'hebron',          'age-united-monarchy', 'declared himself king',  '2 Samuel 15:10'),
  ('absalom',  'jerusalem',       'age-united-monarchy', 'seized the palace',      '2 Samuel 15:37-16:22'),
  ('amnon',    'jerusalem',       'age-united-monarchy', 'assaulted Tamar',        '2 Samuel 13:1-14'),
  ('tamar-david','jerusalem',     'age-united-monarchy', 'assaulted by Amnon',     '2 Samuel 13:1-20'),
  ('nathan-prophet', 'jerusalem', 'age-united-monarchy', 'confronted David',       '2 Samuel 12:1-15'),
  ('zadok',    'jerusalem',       'age-united-monarchy', 'served as priest',       '2 Samuel 15:24-36'),
  ('mephibosheth', 'lo-debar',    'age-united-monarchy', 'lived in hiding',        '2 Samuel 9:4-5'),
  ('mephibosheth', 'jerusalem',   'age-united-monarchy', 'honored by David',       '2 Samuel 9:6-13'),
  ('shimei',   'jerusalem',       'age-united-monarchy', 'cursed David on the road','2 Samuel 16:5-13'),
  ('adonijah', 'jerusalem',       'age-united-monarchy', 'attempted to seize throne','1 Kings 1'),
  ('hiram-tyre','tyre',           'age-united-monarchy', 'king of Tyre',           '1 Kings 5:1'),
  ('hiram-tyre','jerusalem',      'age-united-monarchy', 'supplied Temple materials','1 Kings 5:8-10'),
  ('queen-of-sheba','jerusalem',  'age-united-monarchy', 'visited Solomon',        '1 Kings 10:1-13'),
  ('david',    'valley-of-elah',  'age-united-monarchy', 'defeated Goliath',       '1 Samuel 17'),
  ('david',    'gath',            'age-united-monarchy', 'feigned madness',        '1 Samuel 21:10-15'),
  ('david',    'en-gedi',         'age-united-monarchy', 'hid from Saul',          '1 Samuel 24:1'),
  ('david',    'ziklag',          'age-united-monarchy', 'given by Philistines',   '1 Samuel 27:5-6'),
  ('david',    'nob',             'age-united-monarchy', 'received showbread',     '1 Samuel 21:1-6'),
  ('david',    'mahanaim',        'age-united-monarchy', 'fled during Absalom''s revolt', '2 Samuel 17:24'),
  ('david',    'ziph',            'age-united-monarchy', 'hid from Saul',          '1 Samuel 23:14-15'),
  ('david',    'mt-moriah',       'age-united-monarchy', 'purchased the threshing floor', '2 Samuel 24:18-25'),
  ('solomon',  'gibeon',          'age-united-monarchy', 'received wisdom from God','1 Kings 3:4-15'),
  ('solomon',  'ezion-geber',     'age-united-monarchy', 'built a fleet of ships', '1 Kings 9:26'),
  ('solomon',  'megiddo',         'age-united-monarchy', 'fortified',              '1 Kings 9:15'),
  ('solomon',  'hazor',           'age-united-monarchy', 'fortified',              '1 Kings 9:15'),
  ('solomon',  'gezer',           'age-united-monarchy', 'fortified',              '1 Kings 9:15-17'),
  ('rehoboam', 'shechem',         'age-divided-monarchy','lost the kingdom',       '1 Kings 12:1-17'),
  ('rehoboam', 'jerusalem',       'age-divided-monarchy','ruled Judah',            '1 Kings 14:21'),
  ('jeroboam-i','shechem',        'age-divided-monarchy','first capital',          '1 Kings 12:25'),
  ('jeroboam-i','dan',            'age-divided-monarchy','set up golden calf',     '1 Kings 12:28-30'),
  ('jeroboam-i','bethel',         'age-divided-monarchy','set up golden calf',     '1 Kings 12:28-30'),
  ('doeg',     'nob',             'age-united-monarchy', 'massacred the priests',  '1 Samuel 22:18-19'),
  ('hushai',   'jerusalem',       'age-united-monarchy', 'defeated Ahithophel''s counsel', '2 Samuel 17:5-14'),
  ('ahithophel','jerusalem',      'age-united-monarchy', 'counselor who betrayed David', '2 Samuel 15:12, 16:20-23'),

  -- ══════════════════════════════════════════════════════════════════════════
  -- DIVIDED MONARCHY
  -- ══════════════════════════════════════════════════════════════════════════
  ('ahab',     'samaria',         'age-divided-monarchy', 'ruled Israel',           '1 Kings 16:29'),
  ('ahab',     'jezreel',         'age-divided-monarchy', 'took Naboth''s vineyard','1 Kings 21'),
  ('ahab',     'ramoth-gilead',   'age-divided-monarchy', 'died in battle',         '1 Kings 22:29-37'),
  ('jezebel',  'sidon',           'age-divided-monarchy', 'born here',              '1 Kings 16:31'),
  ('jezebel',  'samaria',         'age-divided-monarchy', 'promoted Baal worship',  '1 Kings 16:31-33'),
  ('jezebel',  'jezreel',         'age-divided-monarchy', 'died here',              '2 Kings 9:30-37'),
  ('naboth',   'jezreel',         'age-divided-monarchy', 'owned vineyard; murdered','1 Kings 21:1-16'),
  ('omri',     'samaria',         'age-divided-monarchy', 'built new capital',      '1 Kings 16:24'),
  ('omri',     'tirzah',          'age-divided-monarchy', 'former capital',         '1 Kings 16:23'),
  ('jehu',     'ramoth-gilead',   'age-divided-monarchy', 'anointed king',          '2 Kings 9:1-13'),
  ('jehu',     'jezreel',         'age-divided-monarchy', 'executed house of Ahab', '2 Kings 9:14-10:11'),
  ('jehu',     'samaria',         'age-divided-monarchy', 'destroyed Baal worship', '2 Kings 10:18-28'),
  ('athaliah', 'jerusalem',       'age-divided-monarchy', 'seized Judah''s throne', '2 Kings 11:1-3'),
  ('joash-judah','jerusalem',     'age-divided-monarchy', 'restored as king; repaired Temple', '2 Kings 11:4-12:16'),
  ('micaiah',  'ramoth-gilead',   'age-divided-monarchy', 'prophesied Ahab''s death','1 Kings 22:13-28'),
  ('obadiah-steward','samaria',   'age-divided-monarchy', 'hid 100 prophets',       '1 Kings 18:3-4'),
  ('naaman',   'damascus',        'age-divided-monarchy', 'served king of Aram',    '2 Kings 5:1'),
  ('naaman',   'jordan-river',    'age-divided-monarchy', 'healed of leprosy',      '2 Kings 5:14'),
  ('gehazi',   'samaria',         'age-divided-monarchy', 'served Elisha',          '2 Kings 4:12'),
  ('gehazi',   'jordan-river',    'age-divided-monarchy', 'struck with leprosy',    '2 Kings 5:20-27'),
  ('amos',     'tekoa',           'age-divided-monarchy', 'hometown',               'Amos 1:1'),
  ('amos',     'bethel',          'age-divided-monarchy', 'prophesied; expelled',   'Amos 7:10-13'),
  ('hosea',    'samaria',         'age-divided-monarchy', 'prophesied',             'Hosea 1:1'),
  ('elijah',   'brook-cherith',   'age-divided-monarchy', 'fed by ravens',          '1 Kings 17:3-6'),
  ('elijah',   'zarephath',       'age-divided-monarchy', 'stayed with widow',      '1 Kings 17:8-24'),
  ('elijah',   'jezreel',         'age-divided-monarchy', 'confronted Ahab',        '1 Kings 21:17-24'),
  ('elijah',   'beersheba',       'age-divided-monarchy', 'fled from Jezebel',      '1 Kings 19:3'),
  ('elijah',   'jordan-river',    'age-divided-monarchy', 'taken up to heaven',     '2 Kings 2:6-12'),
  ('elisha',   'jericho',         'age-divided-monarchy', 'purified the spring',    '2 Kings 2:19-22'),
  ('elisha',   'shunem',          'age-divided-monarchy', 'raised dead son',        '2 Kings 4:8-37'),
  ('elisha',   'dothan',          'age-divided-monarchy', 'angelic army revealed',  '2 Kings 6:13-17'),
  ('elisha',   'jordan-river',    'age-divided-monarchy', 'parted the waters',      '2 Kings 2:13-14'),
  ('jeroboam-ii','samaria',       'age-divided-monarchy', 'ruled Israel',           '2 Kings 14:23'),
  ('uzziah',   'jerusalem',       'age-divided-monarchy', 'ruled Judah; struck with leprosy', '2 Chronicles 26:3-21'),
  ('ahaz',     'jerusalem',       'age-divided-monarchy', 'ruled Judah',            '2 Kings 16:1-2'),
  ('ahaz',     'damascus',        'age-divided-monarchy', 'met Tiglath-Pileser; copied pagan altar', '2 Kings 16:10-12'),
  ('ben-hadad','damascus',        'age-divided-monarchy', 'ruled Aram',             '1 Kings 20:1'),
  ('ben-hadad','samaria',         'age-divided-monarchy', 'besieged',               '1 Kings 20:1-21'),
  ('baasha',   'tirzah',          'age-divided-monarchy', 'ruled Israel',           '1 Kings 15:33'),
  ('asa',      'jerusalem',       'age-divided-monarchy', 'ruled Judah',            '1 Kings 15:9-10'),
  ('jehoshaphat','jerusalem',     'age-divided-monarchy', 'ruled Judah',            '1 Kings 22:41-42'),
  ('jehoshaphat','ramoth-gilead', 'age-divided-monarchy', 'joined Ahab in battle',  '1 Kings 22:29'),
  ('hazael',   'damascus',        'age-divided-monarchy', 'seized throne of Aram',  '2 Kings 8:15'),
  ('shalmaneser','samaria',       'age-divided-monarchy', 'besieged for three years','2 Kings 17:3-6'),
  ('tiglath-pileser','dan',       'age-divided-monarchy', 'deported northern tribes','2 Kings 15:29'),
  ('tiglath-pileser','hazor',     'age-divided-monarchy', 'conquered',              '2 Kings 15:29'),
  ('jonah',    'joppa',           'age-divided-monarchy', 'fled by ship',           'Jonah 1:3'),
  ('jonah',    'nineveh',         'age-divided-monarchy', 'preached; city repented','Jonah 3'),
  ('micah-prophet','jerusalem',   'age-divided-monarchy', 'prophesied',             'Micah 1:1'),
  ('isaiah',   'jerusalem',       'age-divided-monarchy', 'prophesied',             'Isaiah 1:1'),
  ('hezekiah', 'jerusalem',       'age-judah-exile',     'ruled Judah; dug tunnel','2 Kings 18:1-2, 20:20'),
  ('hezekiah', 'lachish',         'age-judah-exile',     'sent tribute',           '2 Kings 18:14'),
  ('sennacherib','nineveh',       'age-judah-exile',     'ruled Assyria',          '2 Kings 19:36'),
  ('sennacherib','lachish',       'age-judah-exile',     'besieged',               '2 Kings 18:14, 17'),
  ('sennacherib','jerusalem',     'age-judah-exile',     'besieged; army destroyed','2 Kings 19:35'),

  -- ══════════════════════════════════════════════════════════════════════════
  -- JUDAH ALONE & EXILE
  -- ══════════════════════════════════════════════════════════════════════════
  ('manasseh', 'jerusalem',       'age-judah-exile', 'ruled Judah; filled with blood', '2 Kings 21:1-16'),
  ('manasseh', 'babylon',         'age-judah-exile', 'taken captive; repented',  '2 Chronicles 33:11-13'),
  ('josiah',   'jerusalem',       'age-judah-exile', 'ruled Judah; found Book of Law', '2 Kings 22:1-2, 8'),
  ('josiah',   'megiddo',         'age-judah-exile', 'killed in battle',         '2 Kings 23:29'),
  ('josiah',   'bethel',          'age-judah-exile', 'destroyed the high place', '2 Kings 23:15'),
  ('zedekiah', 'jerusalem',       'age-judah-exile', 'last king of Judah',       '2 Kings 24:17-18'),
  ('zedekiah', 'riblah',          'age-judah-exile', 'judged by Nebuchadnezzar', '2 Kings 25:6-7'),
  ('jehoiakim','jerusalem',       'age-judah-exile', 'ruled; burned Jeremiah''s scroll', 'Jeremiah 36:23'),
  ('jehoiachin','jerusalem',      'age-judah-exile', 'deported to Babylon',      '2 Kings 24:12-15'),
  ('jehoiachin','babylon',        'age-judah-exile', 'imprisoned; later released','2 Kings 25:27-30'),
  ('nebuchadnezzar','babylon',    'age-judah-exile', 'ruled Babylon',            'Daniel 1:1'),
  ('nebuchadnezzar','jerusalem',  'age-judah-exile', 'destroyed city and Temple','2 Kings 25:8-10'),
  ('nebuchadnezzar','riblah',     'age-judah-exile', 'judged Zedekiah',          '2 Kings 25:6'),
  ('nebuchadnezzar','carchemish', 'age-judah-exile', 'defeated Pharaoh Neco',    'Jeremiah 46:2'),
  ('jeremiah', 'anathoth',        'age-judah-exile', 'hometown',                 'Jeremiah 1:1'),
  ('jeremiah', 'tahpanhes',       'age-judah-exile', 'taken to Egypt',           'Jeremiah 43:5-7'),
  ('jeremiah', 'mizpah',          'age-judah-exile', 'stayed with Gedaliah',     'Jeremiah 40:5-6'),
  ('daniel',   'jerusalem',       'age-judah-exile', 'taken captive as youth',   'Daniel 1:1-6'),
  ('daniel',   'susa',            'age-judah-exile', 'received vision',          'Daniel 8:2'),
  ('ezekiel',  'jerusalem',       'age-judah-exile', 'taken captive',            'Ezekiel 1:1-3'),
  ('baruch',   'jerusalem',       'age-judah-exile', 'read Jeremiah''s scroll',  'Jeremiah 36:8-10'),
  ('baruch',   'tahpanhes',       'age-judah-exile', 'taken to Egypt',           'Jeremiah 43:6'),
  ('ebed-melech','jerusalem',     'age-judah-exile', 'rescued Jeremiah',         'Jeremiah 38:7-13'),
  ('gedaliah', 'mizpah',          'age-judah-exile', 'governed; assassinated',   'Jeremiah 40:5-41:3'),
  ('shadrach', 'babylon',         'age-judah-exile', 'survived fiery furnace',   'Daniel 3'),
  ('meshach',  'babylon',         'age-judah-exile', 'survived fiery furnace',   'Daniel 3'),
  ('abednego', 'babylon',         'age-judah-exile', 'survived fiery furnace',   'Daniel 3'),
  ('belshazzar','babylon',        'age-judah-exile', 'saw writing on the wall',  'Daniel 5'),
  ('huldah',   'jerusalem',       'age-judah-exile', 'prophesied about the Book','2 Kings 22:14-20'),
  ('pharaoh-neco','carchemish',   'age-judah-exile', 'defeated by Nebuchadnezzar','Jeremiah 46:2'),
  ('pharaoh-neco','megiddo',      'age-judah-exile', 'killed Josiah',            '2 Kings 23:29'),
  ('ishmael-nethaniah','mizpah',  'age-judah-exile', 'assassinated Gedaliah',    'Jeremiah 41:1-3'),
  ('nebuzaradan','jerusalem',     'age-judah-exile', 'destroyed the Temple',     '2 Kings 25:8-12'),

  -- ══════════════════════════════════════════════════════════════════════════
  -- RETURN & RESTORATION
  -- ══════════════════════════════════════════════════════════════════════════
  ('zerubbabel','babylon',        'age-return', 'lived in exile',               'Ezra 2:2'),
  ('zerubbabel','jerusalem',      'age-return', 'led return; rebuilt Temple',   'Ezra 3:2-8'),
  ('haggai',   'jerusalem',       'age-return', 'prophesied',                   'Haggai 1:1'),
  ('zechariah-prophet','jerusalem','age-return', 'prophesied',                  'Zechariah 1:1'),
  ('malachi',  'jerusalem',       'age-return', 'prophesied',                   'Malachi 1:1'),
  ('cyrus',    'babylon',         'age-return', 'conquered Babylon',            'Daniel 5:30-31'),
  ('cyrus',    'susa',            'age-return', 'issued decree of return',      'Ezra 1:1-4'),
  ('cyrus',    'ecbatana',        'age-return', 'decree found here',            'Ezra 6:2'),
  ('darius-i', 'susa',            'age-return', 'confirmed decree of Cyrus',    'Ezra 6:1-12'),
  ('darius-i', 'persepolis',      'age-return', 'ruled Persian Empire',         'Ezra 6:1'),
  ('artaxerxes','susa',           'age-return', 'authorized Ezra and Nehemiah', 'Ezra 7:1; Nehemiah 2:1'),
  ('nehemiah', 'susa',            'age-return', 'served the king',              'Nehemiah 1:1'),
  ('ezra',     'babylon',         'age-return', 'led second return',            'Ezra 7:6-9'),
  ('sanballat', 'samaria',        'age-return', 'opposed rebuilding',           'Nehemiah 2:10, 4:1-2'),
  ('tobiah',   'ammon',           'age-return', 'opposed rebuilding',           'Nehemiah 2:10'),
  ('tobiah',   'jerusalem',       'age-return', 'given room in the Temple',     'Nehemiah 13:4-9'),
  ('geshem',   'jerusalem',       'age-return', 'opposed Nehemiah',             'Nehemiah 2:19, 6:1-6'),
  ('esther',   'susa',            'age-return', 'queen; saved her people',      'Esther 2:16-17'),
  ('mordecai', 'susa',            'age-return', 'uncovered assassination plot', 'Esther 2:5-7, 21-23'),
  ('haman',    'susa',            'age-return', 'plotted; hanged',              'Esther 3-7'),
  ('xerxes',   'susa',            'age-return', 'ruled; married Esther',        'Esther 1:2'),
  ('jeshua-priest','jerusalem',   'age-return', 'rebuilt the altar',            'Ezra 3:2'),
  ('sheshbazzar','jerusalem',     'age-return', 'laid Temple foundation',       'Ezra 5:16'),
  ('eliashib', 'jerusalem',       'age-return', 'built Sheep Gate; compromised','Nehemiah 3:1, 13:4-9')

on conflict (person_id, place_id, narrative_age_id) do nothing;

commit;
